### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  id: UpdateMode
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
  langs:
  - csharp
  name: UpdateMode
  nameWithType: UpdateMode
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  type: Enum
  summary: "응용 프로그램이 업데이트를 확인 하는 방법을 지정 합니다."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public enum UpdateMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
  id: Background
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  langs:
  - csharp
  name: Background
  nameWithType: UpdateMode.Background
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "응용 프로그램이 시작 된 후 백그라운드에서 업데이트를 확인 합니다."
  syntax:
    content: Background
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
  id: Foreground
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  langs:
  - csharp
  name: Foreground
  nameWithType: UpdateMode.Foreground
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "응용 프로그램이 시작 되기 전에 포그라운드에서 업데이트를 확인 합니다."
  syntax:
    content: Foreground
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  isExternal: false
  name: Background
  nameWithType: UpdateMode.Background
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: UpdateMode
  nameWithType: UpdateMode
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  isExternal: false
  name: Foreground
  nameWithType: UpdateMode.Foreground
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
