### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  id: CantStartSingleInstanceException
  children:
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: CantStartSingleInstanceException
  nameWithType: CantStartSingleInstanceException
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  type: Class
  summary: "단일 인스턴스 응용 프로그램의 후속 인스턴스가 첫 번째 응용 프로그램 인스턴스에 연결할 수 없는 경우이 예외가 throw 됩니다."
  remarks: "단일 인스턴스 응용 프로그램을 일반 응용 프로그램에서 응용 프로그램의 인스턴스 하나만 실행할 수 있습니다 한 번에 차이가 있습니다. 후속 응용 프로그램 인스턴스가 시작 되 면 명령줄 인수를 전달 하 여 첫 번째 인스턴스 응용 프로그램을 연결할 시도 합니다. 첫 번째 인스턴스를 연결할 수 없는 경우는 CantStartSingleInstanceException 후속 응용 프로그램 인스턴스에서 발생 합니다. Visual Basic 응용 프로그램 모델 예외에 대 한 컨텍스트 정보를 제공 하지 않습니다.       자세한 내용은 참조 [Visual Basic 응용 프로그램 모델의 개요](~/add/includes/ajax-current-ext-md.md)합니다."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class CantStartSingleInstanceException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException()
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException()
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref> 클래스입니다."
  remarks: "단일 인스턴스 응용 프로그램을 일반 응용 프로그램에서 응용 프로그램의 인스턴스 하나만 실행할 수 있습니다 한 번에 차이가 있습니다. 후속 응용 프로그램 인스턴스가 시작 되 면 명령줄 인수를 전달 하 여 첫 번째 인스턴스 응용 프로그램을 연결할 시도 합니다. 첫 번째 인스턴스를 연결할 수 없는 경우는 <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>인스턴스에서 후속 응용 프로그램에서 발생 합니다.</xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException> 자세한 내용은 참조 [Visual Basic 응용 프로그램 모델의 개요](~/add/includes/ajax-current-ext-md.md)합니다.       다음 표에서 <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>안내 하십시오.</xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException> 인스턴스에 대 한 초기 속성 값을 보여 줍니다.      |||   |-|-|   | 속성 | 값 |   | <xref:System.Exception.InnerException%2A>| Null 참조 (`Nothing` Visual basic에서). |   | <xref:System.Exception.Message%2A>| 지역화 된 오류 메시지 문자열입니다. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CantStartSingleInstanceException ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(String)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref> 지정된 된 오류 메시지를 사용 하 여 클래스입니다."
  remarks: "콘텐츠는 `message` 매개 변수는 이해를 돕기 위한 것입니다. 이 생성자의 호출자는이 문자열이 현재 시스템 문화권에 맞게 지역화 되었는지 확인 해야 합니다.       <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException><xref:System.Exception>.</xref:System.Exception> 에서 상속</xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException> 속성을 설정 하는이 생성자는 <xref:System.Exception>개체는 다음 표에 나와 있는 것 처럼.</xref:System.Exception>      |||   |-|-|   | 속성 | 값 |   | <xref:System.Exception.InnerException%2A>| Null 참조 (`Nothing` Visual basic에서) |   | <xref:System.Exception.Message%2A>| `message` 문자열. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CantStartSingleInstanceException (string message);
    parameters:
    - id: message
      type: System.String
      description: "오류를 설명 하는 메시지입니다."
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref> serialize 된 데이터 클래스입니다."
  remarks: "이 생성자는 스트림을 통해 전송 된 예외 개체를 다시 구성 하기 위해 역직렬화 하는 동안 호출 됩니다."
  syntax:
    content: protected CantStartSingleInstanceException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> throw 되는 예외에 대 한 직렬화 된 개체 데이터를 보유 하는 개체입니다."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>소스 또는 대상에 대 한 컨텍스트 정보를 포함 하는 개체입니다.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(String,Exception)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref> 지정된 된 오류 메시지와 해당 예외의 원인인 내부 예외에 대 한 참조를 사용 하 여 클래스입니다."
  remarks: "콘텐츠는 `message` 매개 변수는 이해를 돕기 위한 것입니다. 이 생성자의 호출자는이 문자열이 현재 시스템 문화권에 맞게 지역화 되었는지 확인 해야 합니다.       이전 예외의 직접적인 결과에 이전 예외에 대 한 참조가 들어 있어야 throw 되는 예외는 <xref:System.Exception.InnerException%2A>속성.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>경우 null 참조 또는 생성자에 전달 되는 동일한 값을 반환 하는 속성의 <xref:System.Exception.InnerException%2A>속성이 생성자에 내부 예외 값을 제공 하지 않습니다.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       다음 표에서 <xref:System.ApplicationException>안내 하십시오.</xref:System.ApplicationException> 인스턴스에 대 한 초기 속성 값을 보여 줍니다.      |||   |-|-|   | 속성 | 값 |   | <xref:System.Exception.InnerException%2A>| `inner` 참조 합니다. |   | <xref:System.Exception.Message%2A>| `message` 문자열. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CantStartSingleInstanceException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>오류를 설명 하는 개체입니다.</xref:System.String>"
    - id: inner
      type: System.Exception
      description: "<xref:System.Exception>현재 예외의 원인이 되는 개체입니다.</xref:System.Exception> 경우는 <xref:System.Exception.InnerException*>매개 변수가 null 참조 하지 않습니다. (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> Visual basic에서)에서 현재 예외가 발생 한 <xref uid=&quot;langword_csharp_Catch&quot; name=&quot;Catch&quot; href=&quot;&quot;> </xref> 내부 예외를 처리 하는 블록.</xref:System.Exception.InnerException*>"
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException()
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException()
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException()
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(String)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(String,Exception)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException
