### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser
  id: WebUser
  children:
  - Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  - Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  langs:
  - csharp
  name: WebUser
  nameWithType: WebUser
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser
  type: Class
  summary: "현재 사용자에 대 한 정보에 대 한 액세스를 제공합니다."
  remarks: "의해 노출 되는 메서드와 속성은 `My.User` 개체는 현재 사용자에 대 한 정보에 대 한 액세스를 제공 합니다. &quot;현재 사용자&quot;의 의미는 Windows 및 웹 응용 프로그램 간에 약간 다릅니다. Windows 응용 프로그램에서 현재 사용자는 응용 프로그램을 실행 하는 사용자가 있습니다. 웹 응용 프로그램에서 현재 사용자는 사용자 응용 프로그램에 액세스입니다.       `My.User` 속성에 액세스할 수도 <xref:System.Security.Principal.IPrincipal>현재 사용자에 대 한.</xref:System.Security.Principal.IPrincipal> Principal 개체를 해당 사용자의 id 및 사용자가 속한 모든 역할을 포함 하 여 사용자의 보안 컨텍스트를 나타냅니다.       Windows 응용 프로그램의 경우이 속성은 동일한 기능을 제공 된 <xref:System.Threading.Thread.CurrentPrincipal%2A>속성.</xref:System.Threading.Thread.CurrentPrincipal%2A> 웹 응용 프로그램에서는이 속성은 동일한 기능을 제공 된 <xref:System.Web.HttpContext.User%2A>반환 되는 개체의 속성은 <xref:System.Web.HttpContext.Current%2A>속성.</xref:System.Web.HttpContext.Current%2A> </xref:System.Web.HttpContext.User%2A>      > [!NOTE] >에 대 한 Windows 응용 프로그램을 기반으로 하는 프로젝트만는 **Windows 응용 프로그램** 서식 파일 초기화는 `My.User` 기본적으로는 개체입니다. 다른 모든 Windows 프로젝트 형식에 초기화 해야 합니다는 `My.User` 호출 하 여 개체는 <xref:Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser%2A>메서드 <xref:System.Threading.Thread.CurrentPrincipal%2A>.</xref:System.Threading.Thread.CurrentPrincipal%2A> 값을 할당 하 여 명시적으로 또는</xref:Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser%2A>      > [!NOTE] >는 `My.User` 개체 이러한 운영 체제 로그온 한 사용자의 개념을 지원 하지 않으므로 Windows 95, Windows 98에서 실행 될 경우 현재 Windows 사용자에 대 한 정보를 보고할 수 없습니다. 사용 하려면 사용자 지정 인증을 구현 해야 합니다는 `My.User` 이러한 운영 체제에는 개체입니다."
  example:
  - "This example checks if the application is using Windows or custom authentication, and uses that information to parse the `My.User.Name` property.  \n  \n [!code-vb[VbVbalrMyUser#3](~/add/codesnippet/visualbasic/VbVbalrMyUser/Class1.vb#3)]"
  syntax:
    content: 'public class WebUser : Microsoft.VisualBasic.ApplicationServices.User'
  inheritance:
  - System.Object
  - Microsoft.VisualBasic.ApplicationServices.User
  implements: []
  inheritedMembers:
  - Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal
  - Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser
  - Microsoft.VisualBasic.ApplicationServices.User.IsAuthenticated
  - Microsoft.VisualBasic.ApplicationServices.User.IsInRole(Microsoft.VisualBasic.ApplicationServices.BuiltInRole)
  - Microsoft.VisualBasic.ApplicationServices.User.IsInRole(System.String)
  - Microsoft.VisualBasic.ApplicationServices.User.Name
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  langs:
  - csharp
  name: WebUser()
  nameWithType: WebUser.WebUser()
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.WebUser()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.WebUser&quot;> </xref> 클래스입니다."
  remarks: "의해 노출 되는 메서드와 속성은 `My.User` 개체는 현재 사용자에 대 한 정보에 대 한 액세스를 제공 합니다."
  syntax:
    content: public WebUser ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  id: InternalPrincipal
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  langs:
  - csharp
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "현재 사용자를 나타내는 principal 개체를 가져오거나 설정 합니다."
  remarks: "에 <xref:Microsoft.VisualBasic.ApplicationServices.WebUser>개체를이 속성을 래핑하는 <xref:System.Web.HttpContext.User%2A>속성의는 <xref:System.Web.HttpContext.Current%2A?displayProperty=fullName>속성.</xref:System.Web.HttpContext.Current%2A?displayProperty=fullName> </xref:System.Web.HttpContext.User%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WebUser>       자세한 내용은 참조는 <xref:Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal%2A>속성.</xref:Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal%2A>"
  syntax:
    content: protected override System.Security.Principal.IPrincipal InternalPrincipal { get; set; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "<xref:System.Security.Principal.IPrincipal>현재 사용자를 나타내는 개체입니다.</xref:System.Security.Principal.IPrincipal>"
  overload: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.VisualBasic.ApplicationServices.User
  isExternal: false
  name: Microsoft.VisualBasic.ApplicationServices.User
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: WebUser()
  nameWithType: WebUser.WebUser()
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.WebUser()
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: WebUser
  nameWithType: WebUser.WebUser
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal*
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
