### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings
  id: ProjectLoadSettings
  children:
  - Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  - Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  langs:
  - csharp
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings
  type: Enum
  summary: "MSBuild는 프로젝트를 로드 하는 방식을 정의 합니다."
  syntax:
    content: >-
      [System.Flags]

      public enum ProjectLoadSettings
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  id: IgnoreMissingImports
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  langs:
  - csharp
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "프로젝트를 로드할 때 존재 하지 않는.targets 파일을 무시 합니다."
  syntax:
    content: IgnoreMissingImports
    return:
      type: Microsoft.Build.BuildEngine.ProjectLoadSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  id: None
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  langs:
  - csharp
  name: None
  nameWithType: ProjectLoadSettings.None
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "일반적으로 프로젝트를 로드 합니다."
  syntax:
    content: None
    return:
      type: Microsoft.Build.BuildEngine.ProjectLoadSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  isExternal: false
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings
  parent: Microsoft.Build.BuildEngine
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  isExternal: false
  name: None
  nameWithType: ProjectLoadSettings.None
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
