### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  id: ApplicationIdentity
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  langs:
  - csharp
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  type: Class
  summary: "ClickOnce 응용 프로그램에 대 한 고유 식별자를 제공 합니다."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationIdentity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  id: '#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity&quot;> </xref> 클래스입니다."
  syntax:
    content: public ApplicationIdentity (string url, Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity deployManifestIdentity, Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity applicationManifestIdentity);
    parameters:
    - id: url
      type: System.String
      description: "매니페스트에 ClickOnce 배포에 대 한 배포 공급자 URL입니다."
    - id: deployManifestIdentity
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: "ClickOnce 배포 매니페스트의 어셈블리 id입니다."
    - id: applicationManifestIdentity
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: "ClickOnce 응용 프로그램 매니페스트의 어셈블리 id입니다."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ApplicationIdentity(String,String,String)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,String,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,String,String)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity&quot;> </xref> 클래스입니다."
  syntax:
    content: public ApplicationIdentity (string url, string deployManifestPath, string applicationManifestPath);
    parameters:
    - id: url
      type: System.String
      description: "매니페스트에 ClickOnce 배포에 대 한 배포 공급자 URL입니다."
    - id: deployManifestPath
      type: System.String
      description: "ClickOnce 배포 매니페스트에 대 한 경로입니다. 어셈블리 id는 지정된 된 파일에서 가져옵니다."
    - id: applicationManifestPath
      type: System.String
      description: "ClickOnce 응용 프로그램 매니페스트에 대 한 경로입니다. 어셈블리 id는 지정된 된 파일에서 가져옵니다."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  id: ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ToString()
  nameWithType: ApplicationIdentity.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "전체 ClickOnce 응용 프로그램 id를 반환합니다."
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "ClickOnce 응용 프로그램 id를 포함 하는 문자열입니다."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity(String,String,String)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,String,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,String,String)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ToString()
  nameWithType: ApplicationIdentity.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity.ApplicationIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ToString
  nameWithType: ApplicationIdentity.ToString
