### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  id: VisualBasicSettingsConverter
  children:
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.#ctor
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: VisualBasicSettingsConverter
  nameWithType: VisualBasicSettingsConverter
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  type: Class
  summary: "변환 된 <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> 지정된 된 형식으로 인스턴스."
  remarks: "VisualBasicSettingsConverter는 XAML에서 Visual Basic 식의 deserialization를 지원합니다."
  syntax:
    content: 'public sealed class VisualBasicSettingsConverter : System.ComponentModel.TypeConverter'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  name: VisualBasicSettingsConverter()
  nameWithType: VisualBasicSettingsConverter.VisualBasicSettingsConverter()
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.VisualBasicSettingsConverter()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter&quot;> </xref> 클래스입니다."
  syntax:
    content: public VisualBasicSettingsConverter ();
    parameters: []
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  name: CanConvertFrom(ITypeDescriptorContext,Type)
  nameWithType: VisualBasicSettingsConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: "지정 된 형식의 개체를 변환할 수 있는지 여부를 결정 한 <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> 인스턴스."
  remarks: "경우 `sourceType` 는 <xref:System.String>,이 메서드가 반환 `true`, 그렇지 않으면 <xref:System.ComponentModel.TypeConverter.CanConvertFrom%2A>.</xref:System.ComponentModel.TypeConverter.CanConvertFrom%2A> 기본 클래스 메서드를 호출 하 여 결정</xref:System.String>"
  syntax:
    content: public override bool CanConvertFrom (System.ComponentModel.ITypeDescriptorContext context, Type sourceType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    - id: sourceType
      type: System.Type
      description: "변환할 원본 형식입니다."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>지정된 된 형식;에서 변환할 수 있는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  name: CanConvertTo(ITypeDescriptorContext,Type)
  nameWithType: VisualBasicSettingsConverter.CanConvertTo(ITypeDescriptorContext,Type)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo(ITypeDescriptorContext,Type)
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: "결정 여부는 <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> 인스턴스를 지정 된 형식의 인스턴스로 변환할 수 있습니다."
  remarks: "이 메서드가 반환 `false` 경우는 `destinationType` 는 <xref:System.String> <xref:System.ComponentModel.TypeConverter.CanConvertTo%2A>.</xref:System.ComponentModel.TypeConverter.CanConvertTo%2A> 기본 클래스 메서드를 호출 하 여 결정이 이루어집니다 고, 그러지 않으면</xref:System.String>"
  syntax:
    content: public override bool CanConvertTo (System.ComponentModel.ITypeDescriptorContext context, Type destinationType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    - id: destinationType
      type: System.Type
      description: "변환할 대상 형식입니다."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>경우는 <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> 인스턴스 수의 지정된 된 형식 인스턴스로 변환 없으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: VisualBasicSettingsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: "지정된 된 개체를 변환는 <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> 인스턴스."
  remarks: "변환이 <xref:System.ComponentModel.TypeConverter.ConvertFrom%2A>.</xref:System.ComponentModel.TypeConverter.ConvertFrom%2A> 기본 클래스 메서드를 호출 하 여 이루어집니다. 변환을 만들 수 없는 경우는 <xref:System.NotSupportedException>throw 됩니다.</xref:System.NotSupportedException>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    - id: culture
      type: System.Globalization.CultureInfo
      description: "선택적 <xref:System.Globalization.CultureInfo>.</xref:System.Globalization.CultureInfo> 이 제공 되지 않으면 현재 문화권이 사용 됩니다."
    - id: value
      type: System.Object
      description: "변환할 개체입니다."
    return:
      type: System.Object
      description: "변환 된 값을 나타내는 개체입니다."
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: VisualBasicSettingsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  summary: "변환 된 <xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> 지정된 된 형식으로 인스턴스."
  remarks: "변환이 <xref:System.ComponentModel.TypeConverter.ConvertTo%2A>.</xref:System.ComponentModel.TypeConverter.ConvertTo%2A> 기본 클래스 메서드를 호출 하 여 이루어집니다. 변환을 만들 수 없는 경우는 <xref:System.NotSupportedException>throw 됩니다.</xref:System.NotSupportedException>"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, Type destinationType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    - id: culture
      type: System.Globalization.CultureInfo
      description: "선택적 <xref:System.Globalization.CultureInfo>.</xref:System.Globalization.CultureInfo> 이 제공 되지 않으면 현재 문화권이 사용 됩니다."
    - id: value
      type: System.Object
      description: "<xref href=&quot;Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;> </xref> 인스턴스를 변환 합니다."
    - id: destinationType
      type: System.Type
      description: "변환할 대상 형식입니다."
    return:
      type: System.Object
      description: "변환 된 값입니다."
  overload: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.TypeConverter
  isExternal: false
  name: System.ComponentModel.TypeConverter
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.#ctor
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: VisualBasicSettingsConverter()
  nameWithType: VisualBasicSettingsConverter.VisualBasicSettingsConverter()
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.VisualBasicSettingsConverter()
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: CanConvertFrom(ITypeDescriptorContext,Type)
  nameWithType: VisualBasicSettingsConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom(ITypeDescriptorContext,Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: CanConvertTo(ITypeDescriptorContext,Type)
  nameWithType: VisualBasicSettingsConverter.CanConvertTo(ITypeDescriptorContext,Type)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo(ITypeDescriptorContext,Type)
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: VisualBasicSettingsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: VisualBasicSettingsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.#ctor*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: VisualBasicSettingsConverter
  nameWithType: VisualBasicSettingsConverter.VisualBasicSettingsConverter
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: CanConvertFrom
  nameWithType: VisualBasicSettingsConverter.CanConvertFrom
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: CanConvertTo
  nameWithType: VisualBasicSettingsConverter.CanConvertTo
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: VisualBasicSettingsConverter.ConvertFrom
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo*
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: ConvertTo
  nameWithType: VisualBasicSettingsConverter.ConvertTo
