### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  id: ComClass
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
  langs:
  - csharp
  name: ComClass
  nameWithType: ComClass
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  type: Class
  summary: "매니페스트에 설명 하는 COM 클래스를 나타냅니다."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public class ComClass
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: ComClass()
  nameWithType: ComClass.ComClass()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ComClass()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "새 인스턴스를 초기화는 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;> </xref> 클래스입니다."
  syntax:
    content: public ComClass ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
  id: ClsId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: ClsId
  nameWithType: ComClass.ClsId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "에 대 한 클래스 식별자 (ClsId)를 가져옵니다는 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;> </xref> 개체입니다."
  syntax:
    content: public string ClsId { get; }
    return:
      type: System.String
      description: "A <xref:System.String>패턴 {xxxxxxxx-xxxx-xxxx-개의 자릿수}에서 GUID의 값은 일련의 8, 4, 4, 4의 그룹에 16 진수 소문자 및 12 자로로 표시 하 고 하이픈으로 구분 된 서식이 지정 된.</xref:System.String> 반환 값의 예로 &quot;{382c74c3-721d-4f34-80e5-57657b6cbc27}&quot;."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
  id: Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: Description
  nameWithType: ComClass.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "에 대 한 설명을 가져옵니다는 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;> </xref> 개체입니다."
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "에 대 한 설명을 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;> </xref> 개체입니다."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
  id: ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: ProgId
  nameWithType: ComClass.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "ProgId (프로그래밍 식별자)의 가져옵니다는 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;> </xref> 개체입니다."
  syntax:
    content: public string ProgId { get; }
    return:
      type: System.String
      description: "프로그래밍 식별자는 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;> </xref> 개체입니다."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
  id: ThreadingModel
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: ThreadingModel
  nameWithType: ComClass.ThreadingModel
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "스레딩 모델을 가져옵니다는 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;> </xref> 개체입니다."
  syntax:
    content: public string ThreadingModel { get; }
    return:
      type: System.String
      description: "&quot;Apartment&quot;와 같은 문자열입니다."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
  id: TlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: TlbId
  nameWithType: ComClass.TlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "클래스에 대 한 형식 정보를 포함 하는 형식 라이브러리의 식별자는 값을 가져옵니다."
  syntax:
    content: public string TlbId { get; }
    return:
      type: System.String
      description: "클래스에 대 한 형식 정보를 포함 하는 형식 라이브러리의 식별자입니다. A <xref:System.String>패턴 {xxxxxxxx-xxxx-xxxx-개의 자릿수}에서 GUID의 값은 일련의 8, 4, 4, 4의 그룹에 16 진수 소문자 및 12 자로로 표시 하 고 하이픈으로 구분 된 서식이 지정 된.</xref:System.String> 반환 값의 예로 &quot;{382c74c3-721d-4f34-80e5-57657b6cbc27}&quot;."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
  id: XmlClsId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlClsId
  nameWithType: ComClass.XmlClsId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Serialize 하는 데 사용 되는 속성을 가져오거나 설정 합니다.는 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId*>속성을 XML 파일로.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId*>"
  syntax:
    content: public string XmlClsId { get; set; }
    return:
      type: System.String
      description: "값은 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId*>속성.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
  id: XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlDescription
  nameWithType: ComClass.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Serialize 하는 데 사용 되는 속성을 가져오거나 설정 합니다.는 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description*>속성을 XML 파일로.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description*>"
  syntax:
    content: public string XmlDescription { get; set; }
    return:
      type: System.String
      description: "값은 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description*>속성.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
  id: XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlProgId
  nameWithType: ComClass.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Serialize 하는 데 사용 되는 속성을 가져오거나 설정 합니다.는 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId*>속성을 XML 파일로.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId*>"
  syntax:
    content: public string XmlProgId { get; set; }
    return:
      type: System.String
      description: "값은 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId*>속성.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
  id: XmlThreadingModel
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlThreadingModel
  nameWithType: ComClass.XmlThreadingModel
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Serialize 하는 데 사용 되는 속성을 가져오거나 설정 합니다.는 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel*>속성을 XML 파일로.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel*>"
  syntax:
    content: public string XmlThreadingModel { get; set; }
    return:
      type: System.String
      description: "값은 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel*>속성.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
  id: XmlTlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlTlbId
  nameWithType: ComClass.XmlTlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Serialize 하는 데 사용 되는 속성을 가져오거나 설정 합니다.는 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId*>속성을 XML 파일로.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId*>"
  syntax:
    content: public string XmlTlbId { get; set; }
    return:
      type: System.String
      description: "값은 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId*>속성.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ComClass()
  nameWithType: ComClass.ComClass()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ComClass()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ClsId
  nameWithType: ComClass.ClsId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: Description
  nameWithType: ComClass.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ProgId
  nameWithType: ComClass.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ThreadingModel
  nameWithType: ComClass.ThreadingModel
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: TlbId
  nameWithType: ComClass.TlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlClsId
  nameWithType: ComClass.XmlClsId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlDescription
  nameWithType: ComClass.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlProgId
  nameWithType: ComClass.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlThreadingModel
  nameWithType: ComClass.XmlThreadingModel
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlTlbId
  nameWithType: ComClass.XmlTlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ComClass
  nameWithType: ComClass.ComClass
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ClsId
  nameWithType: ComClass.ClsId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: Description
  nameWithType: ComClass.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ProgId
  nameWithType: ComClass.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ThreadingModel
  nameWithType: ComClass.ThreadingModel
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: TlbId
  nameWithType: ComClass.TlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlClsId
  nameWithType: ComClass.XmlClsId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlDescription
  nameWithType: ComClass.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlProgId
  nameWithType: ComClass.XmlProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlThreadingModel
  nameWithType: ComClass.XmlThreadingModel
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlTlbId
  nameWithType: ComClass.XmlTlbId
