### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebPartsSection
  id: WebPartsSection
  children:
  - System.Web.Configuration.WebPartsSection.#ctor
  - System.Web.Configuration.WebPartsSection.EnableExport
  - System.Web.Configuration.WebPartsSection.GetRuntimeObject
  - System.Web.Configuration.WebPartsSection.Personalization
  - System.Web.Configuration.WebPartsSection.Properties
  - System.Web.Configuration.WebPartsSection.Transformers
  langs:
  - csharp
  name: WebPartsSection
  nameWithType: WebPartsSection
  fullName: System.Web.Configuration.WebPartsSection
  type: Class
  summary: "프로그래밍 방식으로 액세스 하는 <xref uid=&quot;langword_csharp_webParts&quot; name=&quot;webParts&quot; href=&quot;&quot;> </xref> 구성 파일 섹션. 이 클래스는 상속 될 수 없습니다."
  remarks: "`webParts` 구성 파일 섹션을 사용 하면, 웹 파트 개인 설정 공급자를 지정 하 고, 개인 설정 권한을 설정 하 고, 확장 하는 사용자 지정 클래스를 추가할 수 있습니다는 <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer>웹 파트 연결에서 사용할 수 있도록 클래스.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer>"
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `webParts` section, which can also be accessed as members of the WebPartsSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `webParts` section.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <personalization  \n      defaultProvider=\" AspNetSqlPersonalizationProvider \">  \n        <!—- Providers may only be defined at the   \n            application level -->  \n      <providers>  \n        <add name=\"AspNetSqlPersonalizationProvider\"  \ntype=\"System.Web.UI.WebControls.WebParts.SqlPersonalizationProvider\"  \n        connectionStringName=\"LocalSqlServer\"  \n        applicationName=\"/\" />        \n      </providers>  \n      <authorization>  \n        <deny users=\"*\" verbs=\"enterSharedScope\" />  \n        <allow users=\"Admin\" verbs=\"modifyState\" />  \n      </authorization>  \n    </personalization>  \n    <transformers>  \n      <add name=\"RowToFieldTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFieldTransformer\" />  \n      <add name=\"RowToFilterTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFilterTransformer\" />  \n      <add name=\"RowToParametersTransformer\"  \ntype=\"System.Web.UI.WebControls.WebParts.RowToParametersTransformer\" />  \n    </transformers>  \n  </webParts>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the WebPartsSection class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#1](~/add/codesnippet/csharp/t-system.web.configurati_23_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_23_1.vb)]"
  syntax:
    content: 'public sealed class WebPartsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: WebPartsSection()
  nameWithType: WebPartsSection.WebPartsSection()
  fullName: System.Web.Configuration.WebPartsSection.WebPartsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Web.Configuration.WebPartsSection&quot;> </xref> 클래스 기본 설정을 사용 합니다."
  remarks: "사용자 코드에서 직접 사용할 WebPartsSection 생성자를 사용 하는 것이 없습니다. ASP.NET 구성 시스템에 의해 호출 됩니다. 인스턴스를 가져올 수는 <xref:System.Web.Configuration.WebPartsSection>클래스를 사용 하 여는 <xref:System.Configuration.Configuration.GetSection%2A>메서드.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.WebPartsSection>       이 생성자는 사용자 코드에서 직접 사용할 수 없습니다. ASP.NET 구성 시스템에 의해 호출 됩니다.       다음 표에서이 생성자에 사용 되는 기본 설정을 보여 줍니다.      | 설정 | 기본 값 |   |-------------|-------------------|   | <xref:System.Web.Configuration.WebPartsSection.Personalization%2A>| 빈 <xref:System.Web.Configuration.WebPartsPersonalization>개체입니다. |   | <xref:System.Web.Configuration.WebPartsSection.Transformers%2A>| A <xref:System.Web.Configuration.TransformerInfoCollection>기본값을 포함 하는 컬렉션 <xref:System.Web.Configuration.TransformerInfo>개체입니다. |</xref:System.Web.Configuration.TransformerInfo> </xref:System.Web.Configuration.TransformerInfoCollection> </xref:System.Web.Configuration.WebPartsSection.Transformers%2A> </xref:System.Web.Configuration.WebPartsPersonalization> </xref:System.Web.Configuration.WebPartsSection.Personalization%2A>"
  syntax:
    content: public WebPartsSection ();
    parameters: []
  overload: System.Web.Configuration.WebPartsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.EnableExport
  id: EnableExport
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
  fullName: System.Web.Configuration.WebPartsSection.EnableExport
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "컨트롤 데이터를 XML 설명 파일을 내보낼 수 있도록 설정 여부를 나타내는 값을 가져오거나 설정 합니다."
  syntax:
    content: public bool EnableExport { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>컨트롤 데이터를 XML 설명 파일을 내보낼 수 있도록 설정 하려면 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Web.Configuration.WebPartsSection.EnableExport*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject
  id: GetRuntimeObject
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: GetRuntimeObject()
  nameWithType: WebPartsSection.GetRuntimeObject()
  fullName: System.Web.Configuration.WebPartsSection.GetRuntimeObject()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override object GetRuntimeObject ();
    parameters: []
    return:
      type: System.Object
      description: "추가할 수 있습니다."
  overload: System.Web.Configuration.WebPartsSection.GetRuntimeObject*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.Personalization
  id: Personalization
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Personalization
  nameWithType: WebPartsSection.Personalization
  fullName: System.Web.Configuration.WebPartsSection.Personalization
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.Web.Configuration.WebPartsPersonalization&quot;> </xref> 웹 파트 개인 설정 공급자를 지정 하 고 웹 파트 개인 설정 권한을 설정할 수 있는 개체입니다."
  remarks: ''
  example:
  - "The following code example shows how to use the Personalization property.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/csharp/p-system.web.configurati_218_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_218_1.vb)]"
  syntax:
    content: public System.Web.Configuration.WebPartsPersonalization Personalization { get; }
    return:
      type: System.Web.Configuration.WebPartsPersonalization
      description: "A <xref href=&quot;System.Web.Configuration.WebPartsPersonalization&quot;> </xref> 개인 설정 공급자를 지정 하 고 개인 설정 권한을 설정할 수 있는 개체입니다."
  overload: System.Web.Configuration.WebPartsSection.Personalization*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.Properties
  id: Properties
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Properties
  nameWithType: WebPartsSection.Properties
  fullName: System.Web.Configuration.WebPartsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Web.Configuration.WebPartsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.Transformers
  id: Transformers
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Transformers
  nameWithType: WebPartsSection.Transformers
  fullName: System.Web.Configuration.WebPartsSection.Transformers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "컬렉션을 가져옵니다 <xref href=&quot;System.Web.Configuration.TransformerInfo&quot;> </xref> 개체입니다."
  remarks: "<xref:System.Web.Configuration.TransformerInfo>개체를 확장 하는 사용자 지정 클래스를 지정할 수는 <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer>ASP.NET 응용 프로그램 구성 파일의 영향을 받는 웹 파트 연결에서 사용할 수 있도록 클래스.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer></xref:System.Web.Configuration.TransformerInfo> 이러한 변환기 클래스 다리 역할을 수행 간의 연결 된 웹 파트, 웹 파트 호환 되지 않는 연결 지점 사이 데이터를 변환 합니다."
  example:
  - "The following code example shows how to use the Transformers property.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/csharp/p-system.web.configurati_303_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_303_1.vb)]"
  syntax:
    content: public System.Web.Configuration.TransformerInfoCollection Transformers { get; }
    return:
      type: System.Web.Configuration.TransformerInfoCollection
      description: "A <xref href=&quot;System.Web.Configuration.TransformerInfoCollection&quot;> </xref> 컬렉션 <xref href=&quot;System.Web.Configuration.TransformerInfo&quot;> </xref> 개체입니다."
  overload: System.Web.Configuration.WebPartsSection.Transformers*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.WebPartsSection.#ctor
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: WebPartsSection()
  nameWithType: WebPartsSection.WebPartsSection()
  fullName: System.Web.Configuration.WebPartsSection.WebPartsSection()
- uid: System.Web.Configuration.WebPartsSection.EnableExport
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
  fullName: System.Web.Configuration.WebPartsSection.EnableExport
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: GetRuntimeObject()
  nameWithType: WebPartsSection.GetRuntimeObject()
  fullName: System.Web.Configuration.WebPartsSection.GetRuntimeObject()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebPartsSection.Personalization
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Personalization
  nameWithType: WebPartsSection.Personalization
  fullName: System.Web.Configuration.WebPartsSection.Personalization
- uid: System.Web.Configuration.WebPartsPersonalization
  parent: System.Web.Configuration
  isExternal: false
  name: WebPartsPersonalization
  nameWithType: WebPartsPersonalization
  fullName: System.Web.Configuration.WebPartsPersonalization
- uid: System.Web.Configuration.WebPartsSection.Properties
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Properties
  nameWithType: WebPartsSection.Properties
  fullName: System.Web.Configuration.WebPartsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebPartsSection.Transformers
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Transformers
  nameWithType: WebPartsSection.Transformers
  fullName: System.Web.Configuration.WebPartsSection.Transformers
- uid: System.Web.Configuration.TransformerInfoCollection
  parent: System.Web.Configuration
  isExternal: false
  name: TransformerInfoCollection
  nameWithType: TransformerInfoCollection
  fullName: System.Web.Configuration.TransformerInfoCollection
- uid: System.Web.Configuration.WebPartsSection.#ctor*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: WebPartsSection
  nameWithType: WebPartsSection.WebPartsSection
- uid: System.Web.Configuration.WebPartsSection.EnableExport*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: GetRuntimeObject
  nameWithType: WebPartsSection.GetRuntimeObject
- uid: System.Web.Configuration.WebPartsSection.Personalization*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Personalization
  nameWithType: WebPartsSection.Personalization
- uid: System.Web.Configuration.WebPartsSection.Properties*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Properties
  nameWithType: WebPartsSection.Properties
- uid: System.Web.Configuration.WebPartsSection.Transformers*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Transformers
  nameWithType: WebPartsSection.Transformers
