### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  id: PeerCustomResolverSettings
  children:
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  langs:
  - csharp
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  type: Class
  summary: "사용자 지정 피어 확인자 서비스의 인스턴스에 대 한 특정 설정을 포함합니다."
  remarks: "이 형식은 서비스 및 모든 특정 바인딩 설정을 호스팅하는 피어의 끝점 주소를 포함 하 여 사용자 지정 피어 확인자 서비스에 대 한 기본 설정을 정의 합니다. 이러한 설정은에 일반적으로 제공 되는 <xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A>속성.</xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A>"
  syntax:
    content: public class PeerCustomResolverSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.PeerResolvers.PeerCustomResolverSettings&quot;> </xref> 클래스입니다."
  syntax:
    content: public PeerCustomResolverSettings ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  id: Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "사용자 지정 피어 확인자 서비스를 호스팅하는 피어 노드의 끝점 주소를 가져오거나 설정 합니다."
  syntax:
    content: public System.ServiceModel.EndpointAddress Address { get; set; }
    return:
      type: System.ServiceModel.EndpointAddress
      description: "<xref:System.ServiceModel.EndpointAddress>사용자 지정 피어 확인자 서비스를 실행 하는 피어 노드의 끝점 주소를 포함 하는입니다.</xref:System.ServiceModel.EndpointAddress>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  id: Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "사용자 지정 피어 확인자 서비스에서 사용 되는 채널 바인딩을 가져오거나 설정 합니다."
  remarks: "이 바인딩 요소에는 클라이언트와 서비스 채널 수신기에서 채널 팩터리를 빌드하기 위한 사양을 제공 합니다. 이 채널 팩터리는 사용자 지정 피어 확인자 서비스에 대 한 채널을 생성 하기 위해 사용 됩니다."
  syntax:
    content: public System.ServiceModel.Channels.Binding Binding { get; set; }
    return:
      type: System.ServiceModel.Channels.Binding
      description: "<xref:System.ServiceModel.Channels.Binding>이 서비스에 대 한 바인딩 설정이 들어 있는입니다.</xref:System.ServiceModel.Channels.Binding>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  id: IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "가져옵니다 여부는 <xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>속성을 설정 합니다.</xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>"
  syntax:
    content: public bool IsBindingSpecified { get; }
    return:
      type: System.Boolean
      description: "True 이면은 <xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>속성 설정 되지 않은 경우 false입니다.</xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  id: Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "이 서비스에 대 한 사용자 지정 피어 확인자 인스턴스를 가져오거나 설정 합니다."
  syntax:
    content: public System.ServiceModel.PeerResolver Resolver { get; set; }
    return:
      type: System.ServiceModel.PeerResolver
      description: "<xref href=&quot;System.ServiceModel.PeerResolver&quot;></xref>서비스에서 사용 되는 인스턴스."
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
- uid: System.ServiceModel.EndpointAddress
  parent: System.ServiceModel
  isExternal: true
  name: EndpointAddress
  nameWithType: EndpointAddress
  fullName: System.ServiceModel.EndpointAddress
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
- uid: System.ServiceModel.PeerResolver
  parent: System.ServiceModel
  isExternal: false
  name: PeerResolver
  nameWithType: PeerResolver
  fullName: System.ServiceModel.PeerResolver
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
