### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.ApplicationInfo
  id: ApplicationInfo
  children:
  - System.Web.Hosting.ApplicationInfo.ID
  - System.Web.Hosting.ApplicationInfo.PhysicalPath
  - System.Web.Hosting.ApplicationInfo.VirtualPath
  langs:
  - csharp
  name: ApplicationInfo
  nameWithType: ApplicationInfo
  fullName: System.Web.Hosting.ApplicationInfo
  type: Class
  summary: "실행 중인 응용 프로그램에 대 한 정보를 제공합니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "Applicationinfo의 일부 개체에서 사용 되는 <xref:System.Web.Hosting.ApplicationManager>응용 프로그램을 실행 하는 방법에 대 한 정보에 대 한 클래스입니다.</xref:System.Web.Hosting.ApplicationManager>"
  example:
  - "The following code example gets an array of ApplicationInfo objects from the <xref:System.Web.Hosting.ApplicationManager> object associated with the current process.  \n  \n [!code-vb[System.Web.Hosting.ApplicationInfo#1](~/add/codesnippet/visualbasic/t-system.web.hosting.app_1.aspx)]\n [!code-cs[System.Web.Hosting.ApplicationInfo#1](~/add/codesnippet/csharp/t-system.web.hosting.app_1.aspx)]"
  syntax:
    content: public sealed class ApplicationInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.ID
  id: ID
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: ID
  nameWithType: ApplicationInfo.ID
  fullName: System.Web.Hosting.ApplicationInfo.ID
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "응용 프로그램에 대 한 고유 식별자를 가져옵니다."
  remarks: "Microsoft 인터넷 정보 서비스 (IIS)에서 실행 하는 응용 프로그램, 응용 프로그램 ID가 응용 프로그램 루트 /LM/W3SVC/1/Root/application 같은 메타 베이스 경로입니다."
  syntax:
    content: public string ID { get; }
    return:
      type: System.String
      description: "응용 프로그램에 대 한 고유 식별자를 사용 하 여 응용 프로그램을 만들 때 지정 된 <xref:System.Web.Hosting.ApplicationManager.CreateObject*>메서드.</xref:System.Web.Hosting.ApplicationManager.CreateObject*>"
  overload: System.Web.Hosting.ApplicationInfo.ID*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath
  id: PhysicalPath
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
  fullName: System.Web.Hosting.ApplicationInfo.PhysicalPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "응용 프로그램의 루트에 해당 하는 실제 경로 가져옵니다."
  remarks: "PhysicalPath 속성은에 전달 된 경로 <xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>메서드는 응용 프로그램을 만들 때.</xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>"
  syntax:
    content: public string PhysicalPath { get; }
    return:
      type: System.String
      description: "응용 프로그램의 루트에 해당 하는 실제 경로입니다."
  overload: System.Web.Hosting.ApplicationInfo.PhysicalPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath
  id: VirtualPath
  parent: System.Web.Hosting.ApplicationInfo
  langs:
  - csharp
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
  fullName: System.Web.Hosting.ApplicationInfo.VirtualPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "에 해당 하는 응용 프로그램의 루트 가상 경로 가져옵니다."
  remarks: "VirtualPath 속성은에 전달 된 가상 경로 <xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>메서드는 응용 프로그램을 만들 때.</xref:System.Web.Hosting.ApplicationManager.CreateObject%2A>"
  syntax:
    content: public string VirtualPath { get; }
    return:
      type: System.String
      description: "응용 프로그램의 루트에 해당 하는 가상 경로입니다."
  overload: System.Web.Hosting.ApplicationInfo.VirtualPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Hosting.ApplicationInfo.ID
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: ID
  nameWithType: ApplicationInfo.ID
  fullName: System.Web.Hosting.ApplicationInfo.ID
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
  fullName: System.Web.Hosting.ApplicationInfo.PhysicalPath
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
  fullName: System.Web.Hosting.ApplicationInfo.VirtualPath
- uid: System.Web.Hosting.ApplicationInfo.ID*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: ID
  nameWithType: ApplicationInfo.ID
- uid: System.Web.Hosting.ApplicationInfo.PhysicalPath*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: PhysicalPath
  nameWithType: ApplicationInfo.PhysicalPath
- uid: System.Web.Hosting.ApplicationInfo.VirtualPath*
  parent: System.Web.Hosting.ApplicationInfo
  isExternal: false
  name: VirtualPath
  nameWithType: ApplicationInfo.VirtualPath
