### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory
  id: IInternalConfigSettingsFactory
  children:
  - System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit
  - System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(System.Configuration.Internal.IInternalConfigSystem,System.Boolean)
  langs:
  - csharp
  name: IInternalConfigSettingsFactory
  nameWithType: IInternalConfigSettingsFactory
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory
  type: Interface
  summary: "구성 시스템에서 설정 하는 데 사용 하는 인터페이스를 정의 고 <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> 클래스입니다."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigSettingsFactory
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit
  id: CompleteInit
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  langs:
  - csharp
  name: CompleteInit()
  nameWithType: IInternalConfigSettingsFactory.CompleteInit()
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "해당 초기화를 나타내는 시스템 구성의 완료 합니다."
  syntax:
    content: public void CompleteInit ();
    parameters: []
  overload: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(System.Configuration.Internal.IInternalConfigSystem,System.Boolean)
  id: SetConfigurationSystem(System.Configuration.Internal.IInternalConfigSystem,System.Boolean)
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  langs:
  - csharp
  name: SetConfigurationSystem(IInternalConfigSystem,Boolean)
  nameWithType: IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem,Boolean)
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem,Boolean)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "계층적 구성 설정 및 특정 확장 프로그램의 asp.net 구성 시스템에 제공합니다."
  syntax:
    content: public void SetConfigurationSystem (System.Configuration.Internal.IInternalConfigSystem internalConfigSystem, bool initComplete);
    parameters:
    - id: internalConfigSystem
      type: System.Configuration.Internal.IInternalConfigSystem
      description: "<xref href=&quot;System.Configuration.Internal.IInternalConfigSystem&quot;> </xref> 에서 사용 하는 개체는 <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> 클래스입니다."
    - id: initComplete
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>구성 시스템의 초기화 프로세스가 완료 되 면 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  isExternal: false
  name: CompleteInit()
  nameWithType: IInternalConfigSettingsFactory.CompleteInit()
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit()
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(System.Configuration.Internal.IInternalConfigSystem,System.Boolean)
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  isExternal: false
  name: SetConfigurationSystem(IInternalConfigSystem,Boolean)
  nameWithType: IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem,Boolean)
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem,Boolean)
- uid: System.Configuration.Internal.IInternalConfigSystem
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigSystem
  nameWithType: IInternalConfigSystem
  fullName: System.Configuration.Internal.IInternalConfigSystem
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit*
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  isExternal: false
  name: CompleteInit
  nameWithType: IInternalConfigSettingsFactory.CompleteInit
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem*
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  isExternal: false
  name: SetConfigurationSystem
  nameWithType: IInternalConfigSettingsFactory.SetConfigurationSystem
