### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.MailSettingsSectionGroup
  id: MailSettingsSectionGroup
  children:
  - System.Net.Configuration.MailSettingsSectionGroup.#ctor
  - System.Net.Configuration.MailSettingsSectionGroup.Smtp
  langs:
  - csharp
  name: MailSettingsSectionGroup
  nameWithType: MailSettingsSectionGroup
  fullName: System.Net.Configuration.MailSettingsSectionGroup
  type: Class
  summary: "MailSettingsSectionGroup 클래스의 새 인스턴스를 초기화합니다."
  remarks: "This class corresponds to the [\\&lt;mailSettings\\&gt; Element (Network Settings)](../Topic/%3CmailSettings%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to access information about SMTP settings for the local computer.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class MailSettingsSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Net.Configuration.MailSettingsSectionGroup.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.MailSettingsSectionGroup
  langs:
  - csharp
  name: MailSettingsSectionGroup()
  nameWithType: MailSettingsSectionGroup.MailSettingsSectionGroup()
  fullName: System.Net.Configuration.MailSettingsSectionGroup.MailSettingsSectionGroup()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Net.Configuration.MailSettingsSectionGroup&quot;> </xref> 클래스입니다."
  syntax:
    content: public MailSettingsSectionGroup ();
    parameters: []
  overload: System.Net.Configuration.MailSettingsSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.MailSettingsSectionGroup.Smtp
  id: Smtp
  parent: System.Net.Configuration.MailSettingsSectionGroup
  langs:
  - csharp
  name: Smtp
  nameWithType: MailSettingsSectionGroup.Smtp
  fullName: System.Net.Configuration.MailSettingsSectionGroup.Smtp
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "로컬 컴퓨터에 대 한 SMTP 설정을 가져옵니다."
  remarks: "메일 설정 <xref:System.Net.Mail.SmtpClient>클래스</xref:System.Net.Mail.SmtpClient> 의 동작에 영향을 줄합니다"
  syntax:
    content: public System.Net.Configuration.SmtpSection Smtp { get; }
    return:
      type: System.Net.Configuration.SmtpSection
      description: "A <xref href=&quot;System.Net.Configuration.SmtpSection&quot;> </xref> 로컬 컴퓨터에 대 한 구성 정보를 포함 하는 개체입니다."
  overload: System.Net.Configuration.MailSettingsSectionGroup.Smtp*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Net.Configuration.MailSettingsSectionGroup.#ctor
  parent: System.Net.Configuration.MailSettingsSectionGroup
  isExternal: false
  name: MailSettingsSectionGroup()
  nameWithType: MailSettingsSectionGroup.MailSettingsSectionGroup()
  fullName: System.Net.Configuration.MailSettingsSectionGroup.MailSettingsSectionGroup()
- uid: System.Net.Configuration.MailSettingsSectionGroup.Smtp
  parent: System.Net.Configuration.MailSettingsSectionGroup
  isExternal: false
  name: Smtp
  nameWithType: MailSettingsSectionGroup.Smtp
  fullName: System.Net.Configuration.MailSettingsSectionGroup.Smtp
- uid: System.Net.Configuration.SmtpSection
  parent: System.Net.Configuration
  isExternal: false
  name: SmtpSection
  nameWithType: SmtpSection
  fullName: System.Net.Configuration.SmtpSection
- uid: System.Net.Configuration.MailSettingsSectionGroup.#ctor*
  parent: System.Net.Configuration.MailSettingsSectionGroup
  isExternal: false
  name: MailSettingsSectionGroup
  nameWithType: MailSettingsSectionGroup.MailSettingsSectionGroup
- uid: System.Net.Configuration.MailSettingsSectionGroup.Smtp*
  parent: System.Net.Configuration.MailSettingsSectionGroup
  isExternal: false
  name: Smtp
  nameWithType: MailSettingsSectionGroup.Smtp
