### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingAttribute
  id: SettingAttribute
  children:
  - System.Configuration.SettingAttribute.#ctor
  langs:
  - csharp
  name: SettingAttribute
  nameWithType: SettingAttribute
  fullName: System.Configuration.SettingAttribute
  type: Class
  summary: "설정 속성을 설정 정보를 연결 하는 사용자 지정 설정을 특성을 나타냅니다."
  remarks: "SettingAttribute 클래스 설정 속성을 설정 정보를 연결합니다. <xref:System.Configuration.ApplicationSettingsBase>클래스가 또는 파생된 특성으로 표시 되어 있지는 모든 속성을 무시 합니다.</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public class SettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingAttribute
  langs:
  - csharp
  name: SettingAttribute()
  nameWithType: SettingAttribute.SettingAttribute()
  fullName: System.Configuration.SettingAttribute.SettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.SettingAttribute&quot;> </xref> 클래스입니다."
  syntax:
    content: public SettingAttribute ();
    parameters: []
  overload: System.Configuration.SettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingAttribute.#ctor
  parent: System.Configuration.SettingAttribute
  isExternal: false
  name: SettingAttribute()
  nameWithType: SettingAttribute.SettingAttribute()
  fullName: System.Configuration.SettingAttribute.SettingAttribute()
- uid: System.Configuration.SettingAttribute.#ctor*
  parent: System.Configuration.SettingAttribute
  isExternal: false
  name: SettingAttribute
  nameWithType: SettingAttribute.SettingAttribute
