### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement
  id: PrivacyNoticeElement
  children:
  - System.ServiceModel.Configuration.PrivacyNoticeElement.#ctor
  - System.ServiceModel.Configuration.PrivacyNoticeElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.PrivacyNoticeElement.BindingElementType
  - System.ServiceModel.Configuration.PrivacyNoticeElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.PrivacyNoticeElement.CreateBindingElement
  - System.ServiceModel.Configuration.PrivacyNoticeElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.PrivacyNoticeElement.Properties
  - System.ServiceModel.Configuration.PrivacyNoticeElement.Url
  - System.ServiceModel.Configuration.PrivacyNoticeElement.Version
  langs:
  - csharp
  name: PrivacyNoticeElement
  nameWithType: PrivacyNoticeElement
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement
  type: Class
  summary: "사용 되는 개인 정보 알림을 지정 하는 구성 요소를 나타냅니다 <xref uid=&quot;langword_csharp_wsFederationHttp&quot; name=&quot;wsFederationHttp&quot; href=&quot;&quot;> </xref> 바인딩."
  syntax:
    content: 'public class PrivacyNoticeElement : System.ServiceModel.Configuration.BindingElementExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BindingElementExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: PrivacyNoticeElement()
  nameWithType: PrivacyNoticeElement.PrivacyNoticeElement()
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.PrivacyNoticeElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.PrivacyNoticeElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public PrivacyNoticeElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  id: ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: ApplyConfiguration(BindingElement)
  nameWithType: PrivacyNoticeElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.ApplyConfiguration(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정 된 바인딩 요소의 내용을이 바인딩 구성 요소에 적용 됩니다."
  syntax:
    content: public override void ApplyConfiguration (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "바인딩 요소입니다."
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.ApplyConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: PrivacyNoticeElement.BindingElementType
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "가져옵니다는 <xref:System.Type>이 사용자 지정 바인딩 요소를 나타내는 개체입니다.</xref:System.Type>"
  syntax:
    content: public override Type BindingElementType { get; }
    return:
      type: System.Type
      description: "A <xref:System.Type>이 사용자 지정 바인딩 형식을 나타내는 개체입니다.</xref:System.Type>"
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.BindingElementType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: PrivacyNoticeElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정 된 구성 요소의 내용을이 구성 요소에 복사합니다."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "복사할 구성 요소입니다."
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.CreateBindingElement
  id: CreateBindingElement
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: CreateBindingElement()
  nameWithType: PrivacyNoticeElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.CreateBindingElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "사용자 지정 바인딩 요소 개체를이 구성 요소의 설정에 따라 새를 만듭니다."
  syntax:
    content: protected override System.ServiceModel.Channels.BindingElement CreateBindingElement ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.BindingElement
      description: "사용자 지정 <xref:System.ServiceModel.Channels.BindingElement>개체 속성을 가진이 구성 요소의 설정을 기반.</xref:System.ServiceModel.Channels.BindingElement>"
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.CreateBindingElement*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  id: InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: InitializeFrom(BindingElement)
  nameWithType: PrivacyNoticeElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.InitializeFrom(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정된 된 바인딩 요소의 내용 사용 하 여이 바인딩 구성 요소를 초기화합니다."
  syntax:
    content: protected override void InitializeFrom (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "바인딩 요소입니다."
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.InitializeFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: Properties
  nameWithType: PrivacyNoticeElement.Properties
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 의 컬렉션을 포함 하는 인스턴스 <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> 특성 일 수 있는 개체 또는 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 이 구성 요소 개체입니다."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 의 컬렉션을 포함 하는 인스턴스 <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> 특성 일 수 있는 개체 또는 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 이 구성 요소 개체입니다."
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Url
  id: Url
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: Url
  nameWithType: PrivacyNoticeElement.Url
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.Url
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "개인 정보 알림이 있는 URI를 가져오거나 설정 합니다."
  syntax:
    content: public Uri Url { get; set; }
    return:
      type: System.Uri
      description: "<xref:System.Uri>개인 정보 알림이 위치한.</xref:System.Uri>"
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.Url*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Version
  id: Version
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  langs:
  - csharp
  name: Version
  nameWithType: PrivacyNoticeElement.Version
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.Version
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "이 개인 정보 알림의 버전을 가져오거나 설정 합니다."
  syntax:
    content: public int Version { get; set; }
    return:
      type: System.Int32
      description: "이 개인 정보 알림의 버전을 지정 하는 정수입니다."
  overload: System.ServiceModel.Configuration.PrivacyNoticeElement.Version*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BindingElementExtensionElement
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.#ctor
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: PrivacyNoticeElement()
  nameWithType: PrivacyNoticeElement.PrivacyNoticeElement()
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.PrivacyNoticeElement()
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: ApplyConfiguration(BindingElement)
  nameWithType: PrivacyNoticeElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.ApplyConfiguration(BindingElement)
- uid: System.ServiceModel.Channels.BindingElement
  parent: System.ServiceModel.Channels
  isExternal: true
  name: BindingElement
  nameWithType: BindingElement
  fullName: System.ServiceModel.Channels.BindingElement
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.BindingElementType
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: BindingElementType
  nameWithType: PrivacyNoticeElement.BindingElementType
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: PrivacyNoticeElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.CreateBindingElement
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: CreateBindingElement()
  nameWithType: PrivacyNoticeElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.CreateBindingElement()
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: InitializeFrom(BindingElement)
  nameWithType: PrivacyNoticeElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.InitializeFrom(BindingElement)
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Properties
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: Properties
  nameWithType: PrivacyNoticeElement.Properties
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Url
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: Url
  nameWithType: PrivacyNoticeElement.Url
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.Url
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Version
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: Version
  nameWithType: PrivacyNoticeElement.Version
  fullName: System.ServiceModel.Configuration.PrivacyNoticeElement.Version
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.#ctor*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: PrivacyNoticeElement
  nameWithType: PrivacyNoticeElement.PrivacyNoticeElement
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: PrivacyNoticeElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.BindingElementType*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: BindingElementType
  nameWithType: PrivacyNoticeElement.BindingElementType
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.CopyFrom*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: CopyFrom
  nameWithType: PrivacyNoticeElement.CopyFrom
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.CreateBindingElement*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: CreateBindingElement
  nameWithType: PrivacyNoticeElement.CreateBindingElement
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: InitializeFrom
  nameWithType: PrivacyNoticeElement.InitializeFrom
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Properties*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: Properties
  nameWithType: PrivacyNoticeElement.Properties
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Url*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: Url
  nameWithType: PrivacyNoticeElement.Url
- uid: System.ServiceModel.Configuration.PrivacyNoticeElement.Version*
  parent: System.ServiceModel.Configuration.PrivacyNoticeElement
  isExternal: false
  name: Version
  nameWithType: PrivacyNoticeElement.Version
