### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CallbackDebugElement
  id: CallbackDebugElement
  children:
  - System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  - System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  - System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  - System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  - System.ServiceModel.Configuration.CallbackDebugElement.Properties
  langs:
  - csharp
  name: CallbackDebugElement
  nameWithType: CallbackDebugElement
  fullName: System.ServiceModel.Configuration.CallbackDebugElement
  type: Class
  summary: "Windows Communication Foundation (WCF) 콜백 개체에 대 한 서비스 측 디버깅을 지정 하는 구성 요소를 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "설정 하는 경우는 <xref:System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults%2A>속성을 `true` 디버깅 목적으로 서비스에는 클라이언트 콜백 개체의 관리 되는 예외 정보 흐름을 프로그래밍 방식으로 설정할 수 있습니다.</xref:System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults%2A>      > [!CAUTION] > 관리 되는 예외 정보를 클라이언트에는 보안상 위험할 수 있습니다를 반환 합니다. 권한이 없는 클라이언트에서 사용할 수 있는 내부 서비스 구현에 대 한 정보를 노출 하는 때문입니다."
  syntax:
    content: 'public sealed class CallbackDebugElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CallbackDebugElement()
  nameWithType: CallbackDebugElement.CallbackDebugElement()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CallbackDebugElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.CallbackDebugElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public CallbackDebugElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.CallbackDebugElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "이 동작 요소의 형식을 가져옵니다."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "동작 요소의 형식입니다."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정 된 구성 요소의 내용을이 구성 요소에 복사합니다."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "복사할 구성 요소입니다."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: CallbackDebugElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  id: IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "반환 하는지 여부를 클라이언트 콜백 개체가 관리 되는 예외 정보를 SOAP 오류의 형태로 서비스에 다시 지정 하는 값을 가져오거나 설정 합니다."
  syntax:
    content: public bool IncludeExceptionDetailInFaults { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Windows Communication Foundation (WCF) 관리 되는 클라이언트 콜백 예외 정보를 SOAP 오류 형태로 반환; 양방향 통신에서 서비스 측 디버깅 목적 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다. 기본값은 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: Properties
  nameWithType: CallbackDebugElement.Properties
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CallbackDebugElement()
  nameWithType: CallbackDebugElement.CallbackDebugElement()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CallbackDebugElement()
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: CallbackDebugElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: Properties
  nameWithType: CallbackDebugElement.Properties
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CallbackDebugElement
  nameWithType: CallbackDebugElement.CallbackDebugElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CopyFrom
  nameWithType: CallbackDebugElement.CopyFrom
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CreateBehavior
  nameWithType: CallbackDebugElement.CreateBehavior
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: Properties
  nameWithType: CallbackDebugElement.Properties
