### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.StreamChangeCallback
  id: StreamChangeCallback
  langs:
  - csharp
  name: StreamChangeCallback
  nameWithType: StreamChangeCallback
  fullName: System.Configuration.Internal.StreamChangeCallback
  type: Delegate
  summary: "모니터링 되는 스트림이 변경 될 때 호출 하는 호스트에 대 한 메서드를 나타냅니다."
  syntax:
    content: public delegate void StreamChangeCallback(string streamName);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
