### YamlMime:ManagedReference
items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  langs:
  - csharp
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  summary: "Set 또는 get 작업에서 환경 변수를 저장 하거나 검색할 위치를 지정 합니다."
  remarks: "EnvironmentVariableTarget 열거형의 특정 오버 로드에서 사용 되는 <xref:System.Environment.SetEnvironmentVariable%2A>, <xref:System.Environment.GetEnvironmentVariable%2A>, 및 <xref:System.Environment.GetEnvironmentVariables%2A>위치 또는 대상으로 지정 하는 메서드 이름 및 환경 변수 값을 저장 하거나 검색할 위치.</xref:System.Environment.GetEnvironmentVariables%2A> </xref:System.Environment.GetEnvironmentVariable%2A> </xref:System.Environment.SetEnvironmentVariable%2A>       대상 세 위치 중 하나일 수 있습니다: 현재 프로세스, 현재 사용자와 연결 된 환경 변수에 대 한 예약 된 Windows 운영 체제 레지스트리 키 또는 로컬 컴퓨터에서 모든 사용자와 관련 된 환경 변수에 대 한 예약 된 레지스트리 키와 연결 된 환경 블록입니다."
  example:
  - "The following code example demonstrates the EnvironmentVariableTarget enumeration in methods that create, modify, and delete environment variables.  \n  \n [!code-cpp[environment.getsetenvar#1](~/add/codesnippet/cpp/t-system.environmentvari_1.cpp)]\n [!code-vb[environment.getsetenvar#1](~/add/codesnippet/visualbasic/t-system.environmentvari_1.vb)]\n [!code-cs[environment.getsetenvar#1](~/add/codesnippet/csharp/t-system.environmentvari_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentVariableTarget
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "환경 변수에 저장 되어 있거나에서 검색 된 <xref uid=&quot;langword_csharp_HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; name=&quot;HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; href=&quot;&quot;> </xref> Windows 운영 체제 레지스트리에서 키입니다."
  remarks: "집합 작업에서 환경 변수를 만들 때 시스템 레지스트리에 있지만 현재 프로세스에 없는 운영 체제 환경 변수를 저장 합니다. 새 프로세스를 시작 하는 로컬 컴퓨터의 모든 사용자, 운영 체제 환경 변수를 레지스트리에서 해당 프로세스 복사 합니다.       운영 체제 프로세스가 종료 되 면 해당 프로세스에서 환경 변수를 제거 합니다. 그러나 레지스트리에서는 환경 변수는 사용자가 프로그래밍 방식으로 또는 운영 체제 도구를 사용 하 여 제거할 때까지 유지 합니다."
  syntax:
    content: Machine
    return:
      type: System.EnvironmentVariableTarget
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "환경 변수 저장 되었거나 현재 프로세스와 연결 된 환경 블록에서 검색 됩니다."
  remarks: "사용자 설정 작업에서 환경 변수를 만듭니다.       운영 체제 프로세스가 종료 되 면 해당 프로세스에서 환경 변수를 제거 합니다."
  syntax:
    content: Process
    return:
      type: System.EnvironmentVariableTarget
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "환경 변수에 저장 되어 있거나에서 검색 된 <xref uid=&quot;langword_csharp_HKEY_CURRENT_USER\\Environment&quot; name=&quot;HKEY_CURRENT_USER\\Environment&quot; href=&quot;&quot;> </xref> Windows 운영 체제 레지스트리에서 키입니다."
  remarks: "사용자가 set 작업에서 환경 변수를 만들면 시스템 레지스트리에 있지만 현재 프로세스에 없는 운영 체제 환경 변수를 저장 합니다. 새 프로세스를 시작 하는 사용자, 운영 체제 환경 변수를 레지스트리에서 해당 프로세스 복사 합니다.       운영 체제 프로세스가 종료 되 면 해당 프로세스에서 환경 변수를 제거 합니다. 그러나 레지스트리에서 환경 변수는 사용자가 프로그래밍 방식으로 또는 운영 체제 도구를 사용 하 여 제거 될 때까지 유지 합니다."
  syntax:
    content: User
    return:
      type: System.EnvironmentVariableTarget
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.EnvironmentVariableTarget.Machine
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
- uid: System.EnvironmentVariableTarget.User
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
