### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventHandler
  id: SettingChangingEventHandler
  langs:
  - csharp
  name: SettingChangingEventHandler
  nameWithType: SettingChangingEventHandler
  fullName: System.Configuration.SettingChangingEventHandler
  type: Delegate
  summary: "처리 하는 메서드를 나타냅니다는 <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> 이벤트입니다."
  remarks: "<xref:System.Configuration.ApplicationSettingsBase.SettingChanging>응용 프로그램 설정 속성의 값이 변경 되기 전에, 일반적으로 호출을 통해 이벤트 발생는 <xref:System.Configuration.ApplicationSettingsBase.Item%2A>메서드.</xref:System.Configuration.ApplicationSettingsBase.Item%2A> </xref:System.Configuration.ApplicationSettingsBase.SettingChanging> <xref:System.Configuration.ApplicationSettingsBase.SettingChanging><xref:System.Configuration.SettingChangingEventArgs>이벤트 데이터 클래스</xref:System.Configuration.SettingChangingEventArgs> 를 통해 취소할 수 있습니다.</xref:System.Configuration.ApplicationSettingsBase.SettingChanging>"
  syntax:
    content: public delegate void SettingChangingEventHandler(object sender, SettingChangingEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
