### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement
  id: WebScriptEnablingElement
  children:
  - System.ServiceModel.Configuration.WebScriptEnablingElement.#ctor
  - System.ServiceModel.Configuration.WebScriptEnablingElement.BehaviorType
  - System.ServiceModel.Configuration.WebScriptEnablingElement.CreateBehavior
  langs:
  - csharp
  name: WebScriptEnablingElement
  nameWithType: WebScriptEnablingElement
  fullName: System.ServiceModel.Configuration.WebScriptEnablingElement
  type: Class
  summary: "사용 하도록 설정 된 <xref href=&quot;System.ServiceModel.Description.WebScriptEnablingBehavior&quot;> </xref> 구성을 통해 끝점에 대 한 합니다."
  remarks: "WebScriptEnablingElement은는 <xref:System.ServiceModel.Configuration.BehaviorExtensionElement>포함 하도록 사용할 수 있는 하위 형식에서 <xref:System.ServiceModel.Description.WebScriptEnablingBehavior>구성을 통해 끝점에.</xref:System.ServiceModel.Description.WebScriptEnablingBehavior> </xref:System.ServiceModel.Configuration.BehaviorExtensionElement> 이 요소에 대해 구성 가능한 속성이 있습니다.       <xref:System.ServiceModel.Description.WebScriptEnablingBehavior>, 하면 <xref:System.ServiceModel.WebHttpBinding>.</xref:System.ServiceModel.WebHttpBinding> 으로 구성 된 경우 ASP.NET AJAX 웹 페이지에서 액세스할 수에 대 한 끝점</xref:System.ServiceModel.Description.WebScriptEnablingBehavior>       [!INCLUDE[crabout](~/add/includes/ajax-current-ext-md.md)]사용 하도록 설정 하는 방법 한 [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] 서비스에서 ASP.NET AJAX 클라이언트에 응답, 참조를 [ASP.NET AJAX 용 WCF 서비스를 만드는](~/add/includes/ajax-current-ext-md.md)합니다."
  example:
  - "The following is an example of using this configuration element to configure a [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] endpoint to be accessed by ASP.NET AJAX Web page.  \n  \n```  \n<system.serviceModel>  \n<services>  \n        <service name=\"Microsoft.Ajax.Samples.CalculatorService\">  \n            <endpoint address=\"\"  \n                behaviorConfiguration=\"AspNetAjaxBehavior\"   \n                binding=\"webHttpBinding\"  \n                contract=\"Microsoft.Ajax.Samples.ICalculator\" />  \n        </service>  \n    </services>  \n    <behaviors>  \n        <endpointBehaviors>  \n            <behavior name=\"AspNetAjaxBehavior\">  \n                <enableWebScript />  \n            </behavior>  \n        </endpointBehaviors>  \n    </behaviors>  \n</system.serviceModel>  \n```"
  syntax:
    content: 'public sealed class WebScriptEnablingElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  langs:
  - csharp
  name: WebScriptEnablingElement()
  nameWithType: WebScriptEnablingElement.WebScriptEnablingElement()
  fullName: System.ServiceModel.Configuration.WebScriptEnablingElement.WebScriptEnablingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.WebScriptEnablingElement&quot;> </xref> 클래스입니다."
  remarks: ''
  example:
  - "The following sample returns the type <xref:System.ServiceModel.Description.WebScriptEnablingBehavior>.  \n  \n```  \nusing System;  \nusing System.ServiceModel;  \nusing System.ServiceModel.Web;  \nusing System.ServiceModel.Configuration;  \n  \n    class Program  \n    {  \n        static void Main(string[] args)  \n        {  \n            WebScriptEnablingElement wSEB = new WebScriptEnablingElement();  \n            Console.WriteLine(\"The type is: {0}\",wSEB.BehaviorType );  \n            Console.WriteLine(\"Press <ENTER> to terminate the program.\");  \n            Console.ReadLine();  \n        }  \n    }  \n```"
  syntax:
    content: public WebScriptEnablingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WebScriptEnablingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: WebScriptEnablingElement.BehaviorType
  fullName: System.ServiceModel.Configuration.WebScriptEnablingElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "이 구성 요소에서 사용 하도록 설정 하는 동작의 유형을 가져옵니다."
  remarks: ''
  example:
  - "The following sample returns the type <xref:System.ServiceModel.Description.WebScriptEnablingBehavior>.  \n  \n```  \nusing System;  \nusing System.ServiceModel;  \nusing System.ServiceModel.Web;  \nusing System.ServiceModel.Configuration;  \n  \n    class Program  \n    {  \n        static void Main(string[] args)  \n        {  \n            WebScriptEnablingElement wSEB = new WebScriptEnablingElement();  \n            Console.WriteLine(\"The type is: {0}\",wSEB.BehaviorType );  \n            Console.WriteLine(\"Press <ENTER> to terminate the program.\");  \n            Console.ReadLine();  \n        }  \n    }  \n  \n```"
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: '<xref:System.Type>동작을 구성 요소와 사용에 대 한: <xref href=&quot;System.ServiceModel.Description.WebScriptEnablingBehavior&quot;> </xref>.</xref:System.Type>'
  overload: System.ServiceModel.Configuration.WebScriptEnablingElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: WebScriptEnablingElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.WebScriptEnablingElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.WebScriptEnablingElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.#ctor
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  isExternal: false
  name: WebScriptEnablingElement()
  nameWithType: WebScriptEnablingElement.WebScriptEnablingElement()
  fullName: System.ServiceModel.Configuration.WebScriptEnablingElement.WebScriptEnablingElement()
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.BehaviorType
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  isExternal: false
  name: BehaviorType
  nameWithType: WebScriptEnablingElement.BehaviorType
  fullName: System.ServiceModel.Configuration.WebScriptEnablingElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.CreateBehavior
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: WebScriptEnablingElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.WebScriptEnablingElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.#ctor*
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  isExternal: false
  name: WebScriptEnablingElement
  nameWithType: WebScriptEnablingElement.WebScriptEnablingElement
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.BehaviorType*
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  isExternal: false
  name: BehaviorType
  nameWithType: WebScriptEnablingElement.BehaviorType
- uid: System.ServiceModel.Configuration.WebScriptEnablingElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.WebScriptEnablingElement
  isExternal: false
  name: CreateBehavior
  nameWithType: WebScriptEnablingElement.CreateBehavior
