### YamlMime:ManagedReference
items:
- uid: System.Configuration.CommaDelimitedStringCollectionConverter
  id: CommaDelimitedStringCollectionConverter
  children:
  - System.Configuration.CommaDelimitedStringCollectionConverter.#ctor
  - System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: CommaDelimitedStringCollectionConverter
  nameWithType: CommaDelimitedStringCollectionConverter
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter
  type: Class
  summary: "쉼표로 구분 된 문자열 값을 인스턴스 간에 변환는 <xref href=&quot;System.Configuration.CommaDelimitedStringCollection&quot;> </xref> 개체입니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: 'public sealed class CommaDelimitedStringCollectionConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  langs:
  - csharp
  name: CommaDelimitedStringCollectionConverter()
  nameWithType: CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter()
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.CommaDelimitedStringCollectionConverter&quot;> </xref> 클래스입니다."
  syntax:
    content: public CommaDelimitedStringCollectionConverter ();
    parameters: []
  overload: System.Configuration.CommaDelimitedStringCollectionConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "변환 된 <xref:System.String>개체는 <xref href=&quot;System.Configuration.CommaDelimitedStringCollection&quot;> </xref> 개체.</xref:System.String>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> 형식 변환에 사용 합니다."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>변환 하는 동안 사용 되는.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "쉼표로 구분 된 <xref:System.String>변환할.</xref:System.String>"
    return:
      type: System.Object
      description: "A <xref href=&quot;System.Configuration.CommaDelimitedStringCollection&quot;> </xref> 변환 된 값이 들어 있는입니다."
  overload: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "변환 된 <xref href=&quot;System.Configuration.CommaDelimitedStringCollection&quot;> </xref> 개체는 <xref:System.String>개체.</xref:System.String>"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> 형식 변환에 사용 합니다."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>변환 하는 동안 사용 되는.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "변환할 값입니다."
    - id: type
      type: System.Type
      description: "변환 형식입니다."
    return:
      type: System.Object
      description: "<xref:System.String>변환 된 나타내는 <code> value </code> 매개 변수는 <xref href=&quot;System.Configuration.CommaDelimitedStringCollection&quot;> </xref>.</xref:System.String>"
  overload: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.#ctor
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: CommaDelimitedStringCollectionConverter()
  nameWithType: CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter()
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter()
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.#ctor*
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: CommaDelimitedStringCollectionConverter
  nameWithType: CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom*
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertFrom
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo*
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: ConvertTo
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertTo
