### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationCompletedEventArgs
  id: WorkflowApplicationCompletedEventArgs
  children:
  - System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  - System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  - System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  langs:
  - csharp
  name: WorkflowApplicationCompletedEventArgs
  nameWithType: WorkflowApplicationCompletedEventArgs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs
  type: Class
  summary: "실행이 완료 하는 워크플로 인스턴스에 대 한 정보를 제공 합니다."
  remarks: ''
  example:
  - "The following code example inspects the WorkflowApplicationCompletedEventArgs passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#4](~/add/codesnippet/csharp/t-system.activities.work_5_1.cs)]"
  syntax:
    content: 'public class WorkflowApplicationCompletedEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  id: CompletionState
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "있는지 여부를 워크플로 인스턴스가 성공적으로 완료, 취소 되었거나 오류가 발생 한 나타내는 워크플로 인스턴스의 완료 상태를 가져옵니다."
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#4](~/add/codesnippet/csharp/p-system.activities.work_8_1.cs)]"
  syntax:
    content: public System.Activities.ActivityInstanceState CompletionState { get; }
    return:
      type: System.Activities.ActivityInstanceState
      description: "있는지 여부를 워크플로 인스턴스가 성공적으로 완료, 취소 되었거나 오류가 발생 한 나타내는 워크플로 인스턴스의 완료 상태입니다."
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  id: Outputs
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "값을 포함 하는 사전을 가져옵니다 <xref href=&quot;System.Activities.OutArgument&quot;> </xref>인수 이름으로 키가 지정 된 워크플로 인스턴스의 루트 활동의 s입니다."
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#4](~/add/codesnippet/csharp/p-system.activities.work_5_1.cs)]"
  syntax:
    content: public System.Collections.Generic.IDictionary<string,object> Outputs { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: "값을 포함 하는 사전 <xref href=&quot;System.Activities.OutArgument&quot;> </xref>인수 이름으로 키가 지정 된 워크플로 인스턴스의 루트 활동의 s입니다."
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  id: TerminationException
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "워크플로 인스턴스의 종료와 관련 된 예외를 가져옵니다."
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#4](~/add/codesnippet/csharp/p-system.activities.work_9_1.cs)]"
  syntax:
    content: public Exception TerminationException { get; }
    return:
      type: System.Exception
      description: "워크플로 인스턴스의 종료와 관련 된 예외입니다."
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
- uid: System.Activities.ActivityInstanceState
  parent: System.Activities
  isExternal: false
  name: ActivityInstanceState
  nameWithType: ActivityInstanceState
  fullName: System.Activities.ActivityInstanceState
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<String,Object>
  nameWithType: IDictionary<String,Object>
  fullName: System.Collections.Generic.IDictionary<System.String,System.Object>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.String,System.Object>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: Object
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
