### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsAuthenticationCredentials
  id: FormsAuthenticationCredentials
  children:
  - System.Web.Configuration.FormsAuthenticationCredentials.#ctor
  - System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
  - System.Web.Configuration.FormsAuthenticationCredentials.Properties
  - System.Web.Configuration.FormsAuthenticationCredentials.Users
  langs:
  - csharp
  name: FormsAuthenticationCredentials
  nameWithType: FormsAuthenticationCredentials
  fullName: System.Web.Configuration.FormsAuthenticationCredentials
  type: Class
  summary: "양식 기반 인증을 사용 하는 ASP.NET 응용 프로그램에 대 한 사용자 자격 증명을 구성 합니다."
  remarks: "FormsAuthenticationCredentials 클래스에는 프로그래밍 방식으로 액세스 하 고 수정 하는 방법을 제공는 `credentials` 의 요소는 `forms` 섹션은 `authentication` 구성 파일의 섹션입니다. 이 형식은 포함 하는 그룹의 일부는 <xref:System.Web.Configuration.FormsAuthenticationConfiguration>, <xref:System.Web.Configuration.FormsAuthenticationUserCollection>, 및 <xref:System.Web.Configuration.FormsAuthenticationUser>형식.</xref:System.Web.Configuration.FormsAuthenticationUser> </xref:System.Web.Configuration.FormsAuthenticationUserCollection> </xref:System.Web.Configuration.FormsAuthenticationConfiguration> 컬렉션 형식을 제외 하 고 다른 모든에 직접적인 영향을 내부 구성 태그입니다.      > [!NOTE] > The FormsAuthenticationCredentials <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> 에 정의 된 제한에 따라 구성 파일의 관련된 섹션에 정보를 쓸 수 있습니다 데이터를 계층 구조에서 사용할 수 없습니다 수준에서 구성 파일에 쓸 파서에서 생성 하는 오류가 발생 합니다. 그러나 계층의 모든 수준에서 구성 정보를 읽을이 클래스를 사용할 수 있습니다. 안정성과 확장성을 위해 사용자의 자격 증명을 유지 하는 데이터베이스와 같은 외부 저장소를 사용 하는 것이 좋습니다."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `credentials` section, which can also be accessed as members of the FormsAuthenticationCredentials class.  \n  \n The following configuration file example shows how to specify values declaratively for the `credentials` section.  \n  \n```  \n<credentials passwordFormat=\"SHA1\">  \n  <user name=\"aspnetuser1\"  \n    password=\"5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8\"/>  \n  <user name=\"aspnetuser2\"  \n    password=\"E38AD214943DAAD1D64C102FAEC29DE4AFE9DA3D\"/>  \n</credentials>  \n```  \n  \n> [!NOTE]\n>  If you use the `credentials` section, be sure to follow the guidelines explained at [ASP.NET Authentication](~/add/includes/ajax-current-ext-md.md). For scalability and better security, it is recommended that you use an external database to store the users' credentials. For more information about building secure ASP.NET applications, search the Microsoft MSDN Web site (http://msdn.microsoft.com) for \"Securing Your ASP.NET Application\" and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication.\"  \n  \n The following code example demonstrates how to use the FormsAuthenticationCredentials class.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#1](~/add/codesnippet/visualbasic/t-system.web.configurati_12_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#1](~/add/codesnippet/csharp/t-system.web.configurati_12_1.cs)]"
  syntax:
    content: 'public sealed class FormsAuthenticationCredentials : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationCredentials.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  langs:
  - csharp
  name: FormsAuthenticationCredentials()
  nameWithType: FormsAuthenticationCredentials.FormsAuthenticationCredentials()
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.FormsAuthenticationCredentials()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Web.Configuration.FormsAuthenticationCredentials&quot;> </xref> 클래스입니다."
  remarks: ''
  example:
  - "The following code example shows how to create a <xref:System.Web.Configuration.FormsAuthenticationCredentials> object.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#2](~/add/codesnippet/visualbasic/m-system.web.configurati_2_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#2](~/add/codesnippet/csharp/m-system.web.configurati_2_1.cs)]"
  syntax:
    content: public FormsAuthenticationCredentials ();
    parameters: []
  overload: System.Web.Configuration.FormsAuthenticationCredentials.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
  id: PasswordFormat
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  langs:
  - csharp
  name: PasswordFormat
  nameWithType: FormsAuthenticationCredentials.PasswordFormat
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "암호 형식을 가져오거나 설정 합니다."
  remarks: ''
  example:
  - "The following code example shows how to access the PasswordFormat property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationCredentials> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#3](~/add/codesnippet/visualbasic/p-system.web.configurati_386_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#3](~/add/codesnippet/csharp/p-system.web.configurati_386_1.cs)]"
  syntax:
    content: public System.Web.Configuration.FormsAuthPasswordFormat PasswordFormat { get; set; }
    return:
      type: System.Web.Configuration.FormsAuthPasswordFormat
      description: "중 하나는 <xref href=&quot;System.Web.Configuration.FormsAuthPasswordFormat&quot;> </xref> 값입니다."
  overload: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Properties
  id: Properties
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  langs:
  - csharp
  name: Properties
  nameWithType: FormsAuthenticationCredentials.Properties
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Web.Configuration.FormsAuthenticationCredentials.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Users
  id: Users
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  langs:
  - csharp
  name: Users
  nameWithType: FormsAuthenticationCredentials.Users
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.Users
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "사용자의 이름 및 암호 자격 증명을 가져옵니다."
  remarks: ''
  example:
  - "The following code example shows how to use the Users property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationCredentials> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#4](~/add/codesnippet/visualbasic/p-system.web.configurati_181_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#4](~/add/codesnippet/csharp/p-system.web.configurati_181_1.cs)]"
  syntax:
    content: public System.Web.Configuration.FormsAuthenticationUserCollection Users { get; }
    return:
      type: System.Web.Configuration.FormsAuthenticationUserCollection
      description: "A <xref href=&quot;System.Web.Configuration.FormsAuthenticationUserCollection&quot;> </xref> 사용자의 이름 및 암호 자격 증명을 포함 합니다."
  overload: System.Web.Configuration.FormsAuthenticationCredentials.Users*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FormsAuthenticationCredentials.#ctor
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: FormsAuthenticationCredentials()
  nameWithType: FormsAuthenticationCredentials.FormsAuthenticationCredentials()
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.FormsAuthenticationCredentials()
- uid: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: PasswordFormat
  nameWithType: FormsAuthenticationCredentials.PasswordFormat
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat
- uid: System.Web.Configuration.FormsAuthPasswordFormat
  parent: System.Web.Configuration
  isExternal: false
  name: FormsAuthPasswordFormat
  nameWithType: FormsAuthPasswordFormat
  fullName: System.Web.Configuration.FormsAuthPasswordFormat
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Properties
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationCredentials.Properties
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Users
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: Users
  nameWithType: FormsAuthenticationCredentials.Users
  fullName: System.Web.Configuration.FormsAuthenticationCredentials.Users
- uid: System.Web.Configuration.FormsAuthenticationUserCollection
  parent: System.Web.Configuration
  isExternal: false
  name: FormsAuthenticationUserCollection
  nameWithType: FormsAuthenticationUserCollection
  fullName: System.Web.Configuration.FormsAuthenticationUserCollection
- uid: System.Web.Configuration.FormsAuthenticationCredentials.#ctor*
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: FormsAuthenticationCredentials
  nameWithType: FormsAuthenticationCredentials.FormsAuthenticationCredentials
- uid: System.Web.Configuration.FormsAuthenticationCredentials.PasswordFormat*
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: PasswordFormat
  nameWithType: FormsAuthenticationCredentials.PasswordFormat
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Properties*
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationCredentials.Properties
- uid: System.Web.Configuration.FormsAuthenticationCredentials.Users*
  parent: System.Web.Configuration.FormsAuthenticationCredentials
  isExternal: false
  name: Users
  nameWithType: FormsAuthenticationCredentials.Users
