### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ExtensionElementCollection
  id: ExtensionElementCollection
  children:
  - System.ServiceModel.Configuration.ExtensionElementCollection.#ctor
  - System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
  langs:
  - csharp
  name: ExtensionElementCollection
  nameWithType: ExtensionElementCollection
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection
  type: Class
  summary: "컬렉션을 나타냅니다 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElement&quot;> </xref> 인스턴스."
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Configuration.ExtensionElement), CollectionType=System.Configuration.ConfigurationElementCollectionType.BasicMap)]

      public class ExtensionElementCollection : System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Configuration.ExtensionElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Add(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Clear
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CollectionType
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ContainsKey(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CopyTo(`0[],System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ElementName
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.IndexOf(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Remove(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Object)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: ExtensionElementCollection()
  nameWithType: ExtensionElementCollection.ExtensionElementCollection()
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.ExtensionElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElementCollection&quot;> </xref> 클래스입니다."
  syntax:
    content: public ExtensionElementCollection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  id: BaseAdd(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: BaseAdd(ConfigurationElement)
  nameWithType: ExtensionElementCollection.BaseAdd(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "구성 요소를 추가 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElementCollection&quot;> </xref>합니다."
  remarks: "에 추가할 때는 요소 키는 동일한 데 값이 다른 경우에 중복 요소로 간주 됩니다. 동일한 키와 값 요소 들은 서로 충돌 하지 않으므로 오류 없이 추가할 합니다. 그러나 키는 동일한 요소의 다른 값을 결정 하는 경쟁 값 중 어떤 해야 논리가 때문에 추가할 수 없습니다."
  syntax:
    content: protected override void BaseAdd (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "The <xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref> to add."
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "동일한 확장와 이름이 나 형식이 <code> element </code> 컬렉션에 이미 있습니다."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  id: BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: BaseAdd(Int32,ConfigurationElement)
  nameWithType: ExtensionElementCollection.BaseAdd(Int32,ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(Int32,ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "구성 요소를 추가 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElementCollection&quot;> </xref>, 지정된 된 위치에 있습니다."
  remarks: "에 추가할 때는 요소 키는 동일한 데 값이 다른 경우에 중복 요소로 간주 됩니다. 동일한 키와 값 요소 들은 서로 충돌 하지 않으므로 오류 없이 추가할 합니다. 그러나 키는 동일한 요소의 다른 값을 결정 하는 경쟁 값 중 어떤 해야 논리가 때문에 추가할 수 없습니다."
  syntax:
    content: protected override void BaseAdd (int index, System.Configuration.ConfigurationElement element);
    parameters:
    - id: index
      type: System.Int32
      description: "인덱스 위치를 추가할 `element`합니다."
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "The <xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref> to add."
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "동일한 확장와 이름이 나 형식이 <code> element </code> 컬렉션에 이미 있습니다."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: ExtensionElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정 된 구성 요소에 대 한 요소 키를 가져옵니다."
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "<xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 에 대 한 키를 반환할 합니다."
    return:
      type: System.Object
      description: "<xref:System.Object>지정 된 구성 요소에 대 한 키로 사용 하는.</xref:System.Object>"
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>element</code><xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> 이거나 비어 있습니다."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
  id: ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: ThrowOnDuplicate
  nameWithType: ExtensionElementCollection.ThrowOnDuplicate
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "중복을 추가 하려고 하는지 여부를 나타내는 값을 가져옵니다 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 에 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElementCollection&quot;> </xref> 를 throw 하면 예외가 발생 합니다."
  syntax:
    content: protected override bool ThrowOnDuplicate { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>중복을 추가 하려고 하는 경우 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 에 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElementCollection&quot;> </xref> 하 고, 그러지 않으면 throw 된 예외가 발생 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Configuration.ExtensionElement>
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.#ctor
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: ExtensionElementCollection()
  nameWithType: ExtensionElementCollection.ExtensionElementCollection()
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.ExtensionElementCollection()
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: BaseAdd(ConfigurationElement)
  nameWithType: ExtensionElementCollection.BaseAdd(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: BaseAdd(Int32,ConfigurationElement)
  nameWithType: ExtensionElementCollection.BaseAdd(Int32,ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(Int32,ConfigurationElement)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: ExtensionElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ExtensionElementCollection.ThrowOnDuplicate
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.#ctor*
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: ExtensionElementCollection
  nameWithType: ExtensionElementCollection.ExtensionElementCollection
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd*
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: BaseAdd
  nameWithType: ExtensionElementCollection.BaseAdd
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey*
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: GetElementKey
  nameWithType: ExtensionElementCollection.GetElementKey
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate*
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ExtensionElementCollection.ThrowOnDuplicate
