### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSettings
  id: ConfigurationSettings
  children:
  - System.Configuration.ConfigurationSettings.AppSettings
  - System.Configuration.ConfigurationSettings.GetConfig(System.String)
  langs:
  - csharp
  name: ConfigurationSettings
  nameWithType: ConfigurationSettings
  fullName: System.Configuration.ConfigurationSettings
  type: Class
  summary: "구성 섹션 및 일반적인 구성 설정 읽기 위한 런타임 버전 1.0 및 1.1 지원을 제공 합니다."
  remarks: "버전 1.0 및 1.1 응용 프로그램에 대 한 런타임 시 구성 정보를 읽기 위한 정적 메서드와 ConfigurationSettings 형식의 속성을 사용 하는 것이 좋습니다.      > [!NOTE] > The ConfigurationSettings 클래스는 이전 버전과 호환성을 위해서만 제공 합니다. 새 응용 프로그램에 대 한 사용할지는 <xref:System.Configuration.ConfigurationManager>클래스 또는 <xref:System.Web.Configuration.WebConfigurationManager>클래스를 대신 합니다.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager> 이 두 클래스를 사용 하려면 프로젝트 또는 응용 프로그램 System.Configuration 네임 스페이스에 대 한 참조를 추가 해야 합니다."
  syntax:
    content: public sealed class ConfigurationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.AppSettings
  id: AppSettings
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "읽기 전용 가져옵니다 <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> 구성 파일의 응용 프로그램 설정 섹션입니다."
  remarks: "`appSettings` 구성 파일의 섹션 요소를 일련의 목적을 위해 응용 프로그램이 사용할 수 있는 이름/값 쌍을 포함 합니다.       이 메서드는 사용 되지 않으며 이전 버전과 호환성을 위해 유지 됩니다. GetSection 메서드를 대신 사용 하십시오.      > [!NOTE] >는 <xref:System.Configuration.ConfigurationSettings>클래스는 이전 버전과 호환성을 위해서만 제공 합니다.</xref:System.Configuration.ConfigurationSettings> 사용 해야는 <xref:System.Configuration.ConfigurationManager>클래스 또는 <xref:System.Web.Configuration.WebConfigurationManager>클래스를 대신 합니다.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager>"
  syntax:
    content: public static System.Collections.Specialized.NameValueCollection AppSettings { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "읽기 전용 <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> 구성 파일에서 응용 프로그램 설정 섹션입니다."
  overload: System.Configuration.ConfigurationSettings.AppSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  id: GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "반환 된 <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> 전달 된 구성 섹션 이름 및 경로 대 한 개체입니다."
  remarks: "이 메서드는 사용 되지 않으며 이전 버전과 호환성을 위해 유지 됩니다. GetSection 메서드를 대신 사용 하십시오."
  syntax:
    content: public static object GetConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "구성 이름 및 경로 &quot;system.net/settings&quot; 예."
    return:
      type: System.Object
      description: "<xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> 전달 된 구성 섹션 이름 및 경로 대 한 개체입니다.       <div class=&quot;alert NOTE&quot;>    <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> 클래스는 이전 버전과 호환성을 위해서만 제공 합니다. 사용 해야는 <xref href=&quot;System.Configuration.ConfigurationManager&quot;> </xref> 클래스 또는 <xref href=&quot;System.Web.Configuration.WebConfigurationManager&quot;> </xref> 클래스를 대신 합니다.      </div>"
  overload: System.Configuration.ConfigurationSettings.GetConfig*
  exceptions:
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "요청된 된 섹션을 검색할 수 없습니다."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ConfigurationSettings.AppSettings
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSettings.AppSettings*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
- uid: System.Configuration.ConfigurationSettings.GetConfig*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig
  nameWithType: ConfigurationSettings.GetConfig
