### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement
  id: TcpTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  langs:
  - csharp
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement
  type: Class
  summary: "TcpTransport 바인딩의 보안 설정을 정의 하는 XML 요소입니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: 'public sealed class TcpTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: TcpTransportSecurityElement()
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.TcpTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.TcpTransportSecurityElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public TcpTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "가져오고 인증에 사용 되는 클라이언트 자격 증명 형식을 설정 합니다."
  syntax:
    content: public System.ServiceModel.TcpClientCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.TcpClientCredentialType
      description: "A <xref:System.ServiceModel.TcpClientCredentialType>인증에 사용 되는 클라이언트 자격 증명의 유형을 지정 하는.</xref:System.ServiceModel.TcpClientCredentialType>"
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "가져오기는 <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;> </xref> 에 사용할 구성 설정을 포함 하는 인스턴스는 세션에 대 한 보호를 확장 합니다."
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement ExtendedProtectionPolicy { get; }
    return:
      type: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
      description: "Returns <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></xref>."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "명명 된 파이프 수준에서 메시지 수준 보안을 정의 하는 값을 가져오거나 설정 합니다."
  remarks: "제&3; 자가 메시지와 함께 전송 되는 동안의 위험을 줄일 메시지에 서명 합니다. 암호화는 전송 중 데이터 수준의 개인 정보 보호를 제공합니다."
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "A <xref:System.ServiceModel.TcpTransportSecurity.ProtectionLevel*>명명 된 파이프 수준에서 메시지 수준 보안을 정의 하는 값입니다.</xref:System.ServiceModel.TcpTransportSecurity.ProtectionLevel*>"
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  id: SslProtocols
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: 'TcpClientCredentialType.Certificate의 클라이언트 자격 증명 형식을 사용 하는 경우 협상할 SSL/TLS 프로토콜 목록을 가져옵니다. 값은 다음 열거형 멤버 중 하나 이상의 조합이 될 수 있습니다: Ssl3, Tls, Tls11, t l s&12;입니다.'
  remarks: "기본값은 Ssl3 | Tls | Tls11 | T l s&12;입니다. Framework 4.6 이전 버전 Ssl3 및 Tls에만 지원합니다. 이 사용 하지 않는 이전 버전의 프레임 워크와의 통신 가능 되지 않습니다. Tls11 및/또는 t l s&12; 지정 경과 했는데도 문제가 있다면 포함 하는 경우에 Ssl3의 사용을 해제 됩니다."
  syntax:
    content: public System.Security.Authentication.SslProtocols SslProtocols { get; }
    return:
      type: System.Security.Authentication.SslProtocols
      description: "SSL/TLS 프로토콜 목록입니다."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: TcpTransportSecurityElement()
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.TcpTransportSecurityElement()
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.TcpClientCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: TcpClientCredentialType
  nameWithType: TcpClientCredentialType
  fullName: System.ServiceModel.TcpClientCredentialType
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  parent: System.Security.Authentication.ExtendedProtection.Configuration
  isExternal: false
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
- uid: System.Security.Authentication.SslProtocols
  parent: System.Security.Authentication
  isExternal: true
  name: SslProtocols
  nameWithType: SslProtocols
  fullName: System.Security.Authentication.SslProtocols
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
