### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  id: WindowsStreamSecurityElement
  children:
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
  langs:
  - csharp
  name: WindowsStreamSecurityElement
  nameWithType: WindowsStreamSecurityElement
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  type: Class
  summary: "바인딩에 대 한 보안을 스트림 하는 Windows에 대 한 설정을 지정 하는 데 사용 되는 구성 요소를 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: 'public sealed class WindowsStreamSecurityElement : System.ServiceModel.Configuration.BindingElementExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BindingElementExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: WindowsStreamSecurityElement()
  nameWithType: WindowsStreamSecurityElement.WindowsStreamSecurityElement()
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.WindowsStreamSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.WindowsStreamSecurityElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public WindowsStreamSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  id: ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: ApplyConfiguration(BindingElement)
  nameWithType: WindowsStreamSecurityElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정 된 바인딩 요소의 내용을이 바인딩 구성 요소에 적용 됩니다."
  syntax:
    content: public override void ApplyConfiguration (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "바인딩 요소입니다."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: WindowsStreamSecurityElement.BindingElementType
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "가져옵니다는 <xref:System.Type>바인딩 요소를 나타내는 개체입니다.</xref:System.Type>"
  syntax:
    content: public override Type BindingElementType { get; }
    return:
      type: System.Type
      description: "A <xref:System.Type>바인딩 형식을 나타내는 개체입니다.</xref:System.Type>"
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: WindowsStreamSecurityElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정 된 구성 요소의 내용을이 구성 요소에 복사합니다."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "복사할 구성 요소입니다."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement
  id: CreateBindingElement
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: CreateBindingElement()
  nameWithType: WindowsStreamSecurityElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.ServiceModel.Channels.BindingElement CreateBindingElement ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.BindingElement
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  id: InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: InitializeFrom(BindingElement)
  nameWithType: WindowsStreamSecurityElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void InitializeFrom (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WindowsStreamSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: WindowsStreamSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "사용 되는 메시지 수준 보안을 설정 하거나 가져옵니다."
  remarks: "이 속성 서명 및 암호화에 사용 되는 메시지 수준 보안을 지정 합니다. 서명 된 메시지 제&3; 자가 메시지와 함께 전송 되는 동안의 위험을 완화 합니다. 암호화는 전송 중 데이터 수준의 개인 정보 보호를 제공합니다."
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "A <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> 사용 되는 메시지 수준 보안을 지정 하는 합니다. 기본값은 <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> 합니다."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BindingElementExtensionElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: WindowsStreamSecurityElement()
  nameWithType: WindowsStreamSecurityElement.WindowsStreamSecurityElement()
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.WindowsStreamSecurityElement()
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: ApplyConfiguration(BindingElement)
  nameWithType: WindowsStreamSecurityElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(BindingElement)
- uid: System.ServiceModel.Channels.BindingElement
  parent: System.ServiceModel.Channels
  isExternal: true
  name: BindingElement
  nameWithType: BindingElement
  fullName: System.ServiceModel.Channels.BindingElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: BindingElementType
  nameWithType: WindowsStreamSecurityElement.BindingElementType
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: WindowsStreamSecurityElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: CreateBindingElement()
  nameWithType: WindowsStreamSecurityElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement()
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: InitializeFrom(BindingElement)
  nameWithType: WindowsStreamSecurityElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(BindingElement)
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WindowsStreamSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: WindowsStreamSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: WindowsStreamSecurityElement
  nameWithType: WindowsStreamSecurityElement.WindowsStreamSecurityElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: WindowsStreamSecurityElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: BindingElementType
  nameWithType: WindowsStreamSecurityElement.BindingElementType
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: CopyFrom
  nameWithType: WindowsStreamSecurityElement.CopyFrom
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: CreateBindingElement
  nameWithType: WindowsStreamSecurityElement.CreateBindingElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: InitializeFrom
  nameWithType: WindowsStreamSecurityElement.InitializeFrom
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WindowsStreamSecurityElement.Properties
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: WindowsStreamSecurityElement.ProtectionLevel
