### YamlMime:ManagedReference
items:
- uid: System.Diagnostics.DiagnosticsConfigurationHandler
  id: DiagnosticsConfigurationHandler
  children:
  - System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  - System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler
  type: Class
  summary: "구성 파일의 진단 섹션을 처리합니다."
  remarks: "DiagnosticsConfigurationHandler 메서드는의 구성 설정의 확인에 참여 하는 섹션 처리기는 [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) 구성 파일의 부분입니다."
  syntax:
    content: >-
      [System.Obsolete("This class has been deprecated.  http://go.microsoft.com/fwlink/?linkid=14202")]

      public class DiagnosticsConfigurationHandler : System.Configuration.IConfigurationSectionHandler
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Diagnostics.DiagnosticsConfigurationHandler&quot;> </xref> 클래스입니다."
  syntax:
    content: public DiagnosticsConfigurationHandler ();
    parameters: []
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "에 대 한 구성 설정을 구문 분석 하는 [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) 구성 파일의 섹션입니다."
  remarks: "만들기는이 메서드는 <xref:System.Collections.Hashtable>에서 얻은 값으로는 [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) 구성 파일의 해시 테이블을 반환 합니다.</xref:System.Collections.Hashtable>"
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "부모 경로에서 상속 되며, 개체"
    - id: configContext
      type: System.Object
      description: "예약되어 있습니다. 확인 중인 구성의 가상 경로 전달 하기 위해 ASP.NET에서 사용 합니다."
    - id: section
      type: System.Xml.XmlNode
      description: "처리할 섹션에서 루트 XML 노드."
    return:
      type: System.Object
      description: "새 구성 개체의 형태로 <xref href=&quot;System.Collections.Hashtable&quot;> </xref>합니다."
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "스위치를 찾을 수 없습니다.       -또는-Assert 찾을 수 없습니다.       -또는-추적을 찾을 수 없습니다.       -또는-성능 카운터를 찾을 수 없습니다."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DiagnosticsConfigurationHandler.Create
