### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  id: MsmqIntegrationSecurity
  children:
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  langs:
  - csharp
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  type: Class
  summary: "MsmqIntegrationSecurity 클래스에는 MSMQ (메시지 큐) 통합 채널용 전송 보안 설정을 캡슐화합니다."
  remarks: "메시지 큐 통합 채널을 통해 [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] 응용 프로그램이 기존 메시지 큐 응용 프로그램과 통신할 수 있습니다."
  syntax:
    content: public sealed class MsmqIntegrationSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "새 인스턴스를 초기화 <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity&quot;> </xref>합니다."
  syntax:
    content: public MsmqIntegrationSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  id: Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "가져오거나는 <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> MSMQ (메시지 큐) 통합 채널와 연결 된입니다."
  remarks: '<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>다음 값을 포함 하는 열거형: <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>및 <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> </xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode></xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> 기본값은 <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>'
  syntax:
    content: public System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
      description: "<xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> 와 메시지 큐 통합 채널과 연결 된입니다."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  id: Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "가져옵니다는 <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> MSMQ (메시지 큐) 통합 채널와 연결 된입니다."
  remarks: "<xref:System.ServiceModel.MsmqTransportSecurity>메시지 큐 통합 전송 위한 보안 설정을 캡슐화합니다.</xref:System.ServiceModel.MsmqTransportSecurity> 설정은 메시지 큐 통합 및 대기 중인된 전송에서 모두에 대해 동일 합니다. <xref:System.ServiceModel.MsmqTransportSecurity>인증 모드, 암호화 알고리즘, 보안 해시 알고리즘 및 보호 수준을 설정할 수 있습니다.</xref:System.ServiceModel.MsmqTransportSecurity>"
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> 와 메시지 큐 통합 채널과 연결 된입니다."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
  parent: System.ServiceModel.MsmqIntegration
  isExternal: false
  name: MsmqIntegrationSecurityMode
  nameWithType: MsmqIntegrationSecurityMode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
