### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  id: FactorySettingsElement
  children:
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  langs:
  - csharp
  name: FactorySettingsElement
  nameWithType: FactorySettingsElement
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  type: Class
  summary: "워크플로 서비스 응용 프로그램에서 채널 팩터리 구성 요소의 설정에 값을 할당할 수 있도록 합니다. 클래스는 봉인된 클래스입니다."
  syntax:
    content: 'public sealed class FactorySettingsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: FactorySettingsElement()
  nameWithType: FactorySettingsElement.FactorySettingsElement()
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.FactorySettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.ServiceModel.Activities.Configuration.FactorySettingsElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public FactorySettingsElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: FactorySettingsElement.IdleTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "최대 개체 상태로 있을 수 있는 유휴 워크플로 캐시에서 삭제 되기 전에 시간 간격을 가져오거나 설정 합니다."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Timespan 개체입니다."
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: FactorySettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "개체가 워크플로 캐시에서 제거 됩니다 하는 시간 간격을 가져오거나 설정 합니다."
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Timespan 개체입니다."
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  id: MaxItemsInCache
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: MaxItemsInCache
  nameWithType: FactorySettingsElement.MaxItemsInCache
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "워크플로 캐시에 저장할 수 있는 개체의 최대 수를 가져오거나 설정 합니다."
  syntax:
    content: public int MaxItemsInCache { get; set; }
    return:
      type: System.Int32
      description: "최대 수를 나타내는 정수입니다."
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: FactorySettingsElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: FactorySettingsElement()
  nameWithType: FactorySettingsElement.FactorySettingsElement()
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.FactorySettingsElement()
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: FactorySettingsElement.IdleTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: FactorySettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: MaxItemsInCache
  nameWithType: FactorySettingsElement.MaxItemsInCache
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: Properties
  nameWithType: FactorySettingsElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: FactorySettingsElement
  nameWithType: FactorySettingsElement.FactorySettingsElement
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: FactorySettingsElement.IdleTimeout
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: FactorySettingsElement.LeaseTimeout
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: MaxItemsInCache
  nameWithType: FactorySettingsElement.MaxItemsInCache
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: Properties
  nameWithType: FactorySettingsElement.Properties
