### YamlMime:ManagedReference
items:
- uid: System.Configuration.IntegerValidatorAttribute
  id: IntegerValidatorAttribute
  children:
  - System.Configuration.IntegerValidatorAttribute.#ctor
  - System.Configuration.IntegerValidatorAttribute.ExcludeRange
  - System.Configuration.IntegerValidatorAttribute.MaxValue
  - System.Configuration.IntegerValidatorAttribute.MinValue
  - System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: IntegerValidatorAttribute
  nameWithType: IntegerValidatorAttribute
  fullName: System.Configuration.IntegerValidatorAttribute
  type: Class
  summary: "구성 속성에 정수 유효성 검사를 수행 하려면.NET Framework를 선언적으로 지시 합니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "IntegerValidatorAttribute 특성을 사용 하 여 구성 속성을 사용 하 여 속성을 검사할.NET Framework 지시 하기를 데코레이팅하는 <xref:System.Configuration.IntegerValidator>개체를 데코레이팅 매개 변수의 값을 전달 합니다.</xref:System.Configuration.IntegerValidator>       속성 형식에만 IntegerValidatorAttribute 특성을 적용할 수 있습니다."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the IntegerValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/visualbasic/t-system.configuration.i_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/csharp/t-system.configuration.i_0_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class IntegerValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: IntegerValidatorAttribute()
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute()
  fullName: System.Configuration.IntegerValidatorAttribute.IntegerValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.Configuration.IntegerValidatorAttribute&quot;> </xref> 클래스입니다."
  remarks: "특성 사용 모델에서 관련된 속성에 할당 된 값은 정수가이 생성자를 사용 합니다."
  example:
  - "The following example shows how to use the IntegerValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#5](~/add/codesnippet/visualbasic/m-system.configuration.i_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#5](~/add/codesnippet/csharp/m-system.configuration.i_2_1.cs)]"
  syntax:
    content: public IntegerValidatorAttribute ();
    parameters: []
  overload: System.Configuration.IntegerValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
  fullName: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "포함할지으로 정의 된 범위에 있는 정수를 제외할지 여부를 나타내는 값을 가져오거나 설정 합니다.는 <> </> *> 및 <> </> *> 속성 값입니다."
  remarks: "범위는 포함 된 <xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A>및 <xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A>속성 값.</xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A> </xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A> 제외 범위 속성 값이 `true`, 허용 되는 값은 범위를 벗어납니다."
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/visualbasic/p-system.configuration.i_6_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/csharp/p-system.configuration.i_6_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>값을 제외 해야 하는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다. 기본값은 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Configuration.IntegerValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
  fullName: System.Configuration.IntegerValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "속성에 대해 허용 되는 최대값을 가져오거나 설정 합니다."
  remarks: "MaxValue 속성 값은 허용 되는 범위에 포함 됩니다."
  example:
  - "The following example shows how to use the MaxValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/visualbasic/p-system.configuration.i_3_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/csharp/p-system.configuration.i_3_1.cs)]"
  syntax:
    content: public int MaxValue { get; set; }
    return:
      type: System.Int32
      description: "허용 되는 최대값을 나타내는 정수입니다."
  overload: System.Configuration.IntegerValidatorAttribute.MaxValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "선택한 값이 <xref:System.Configuration.IntegerValidatorAttribute.MinValue*>.</xref:System.Configuration.IntegerValidatorAttribute.MinValue*> 보다 작은"
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
  fullName: System.Configuration.IntegerValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "속성에 대해 허용 되는 최소값을 가져오거나 설정 합니다."
  remarks: "MinValue 속성 값은 허용 되는 범위에 포함 됩니다."
  example:
  - "The following example shows how to use the MinValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/visualbasic/p-system.configuration.i_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/csharp/p-system.configuration.i_0_1.cs)]"
  syntax:
    content: public int MinValue { get; set; }
    return:
      type: System.Int32
      description: "허용 되는 최소값을 나타내는 정수입니다."
  overload: System.Configuration.IntegerValidatorAttribute.MinValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "선택한 값 <xref:System.Configuration.IntegerValidatorAttribute.MaxValue*>.</xref:System.Configuration.IntegerValidatorAttribute.MaxValue*> 보다 큽니다."
  platform:
  - net462
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "인스턴스를 가져옵니다는 <xref href=&quot;System.Configuration.IntegerValidator&quot;> </xref> 클래스입니다."
  remarks: "호출 하 여 문자열 유효성 검사를 수행 하려면 ValidatorInstance 속성을 사용 하면 해당 <xref:System.Configuration.IntegerValidator.Validate%2A>메서드.</xref:System.Configuration.IntegerValidator.Validate%2A>"
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#13](~/add/codesnippet/visualbasic/p-system.configuration.i_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#13](~/add/codesnippet/csharp/p-system.configuration.i_2_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "<xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> 유효성 검사기 인스턴스에 있습니다."
  overload: System.Configuration.IntegerValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.IntegerValidatorAttribute.#ctor
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: IntegerValidatorAttribute()
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute()
  fullName: System.Configuration.IntegerValidatorAttribute.IntegerValidatorAttribute()
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
  fullName: System.Configuration.IntegerValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
  fullName: System.Configuration.IntegerValidatorAttribute.MaxValue
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.IntegerValidatorAttribute.MinValue
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
  fullName: System.Configuration.IntegerValidatorAttribute.MinValue
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.IntegerValidatorAttribute.#ctor*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: IntegerValidatorAttribute
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
- uid: System.Configuration.IntegerValidatorAttribute.MinValue*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
