### YamlMime:ManagedReference
items:
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  id: ChartHttpHandlerSettings
  children:
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  langs:
  - csharp
  name: ChartHttpHandlerSettings
  nameWithType: ChartHttpHandlerSettings
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  type: Class
  summary: "임시 이미지 파일을 저장 하기 위한 사용자 지정 HTTP 처리기를 작성 하는 데 사용할 수 있는 특성을 제공 합니다."
  syntax:
    content: public class ChartHttpHandlerSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  id: CustomHandlerName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "사용자 지정 처리기의 이름을 가져오거나 설정 합니다."
  syntax:
    content: public string CustomHandlerName { get; set; }
    return:
      type: System.String
      description: "A <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> 사용자 지정 처리기의 이름을 나타내는 값입니다."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  id: Directory
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "임시 이미지 파일을 저장할 디렉터리의 사용자 지정 처리기를 가져오거나 설정 합니다."
  syntax:
    content: public string Directory { get; set; }
    return:
      type: System.String
      description: "A <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> 디렉터리를 나타내는 값입니다."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  id: FolderName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "지정된 된 디렉터리에서 이미지를 저장 하는 데 사용 되는 폴더를 가져오거나 설정 합니다."
  syntax:
    content: public string FolderName { get; set; }
    return:
      type: System.String
      description: "A <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> 폴더 이름을 나타내는입니다."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  id: HandlerType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "사용자 지정 처리기의 처리기 유형을 가져옵니다."
  syntax:
    content: public Type HandlerType { get; }
    return:
      type: System.Type
      description: "<xref:System.Type>사용자 지정 처리기의.</xref:System.Type>"
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  id: Item(System.String)
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Item(String)
  nameWithType: ChartHttpHandlerSettings.Item(String)
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(String)
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "아래에 있는 Web.config 파일에 등록 되어 설정 매개 변수에서 지정한 이름 가진 가져옵니다는 `ChartHttpHandler` 키입니다."
  remarks: "이 메서드를 사용 하 여 아래에 있는 Web.config 파일 매개 변수에 액세스 하는 `ChartHttpHandler` 키입니다."
  syntax:
    content: public string this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "매개 변수를의 이름입니다."
    return:
      type: System.String
      description: "매개 변수 값입니다."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  id: PrivateImages
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "처리기는 전용 이미지를 사용할지 여부를 나타내는 플래그를 가져옵니다."
  remarks: "PrivateImages 속성을 설정 하는 경우 처리기는 세션 범위를 벗어난 이미지 반환 하지 않습니다. 또한 클라이언트를 다른 사용자의 이미지를 다운로드할 수 없습니다. 이것이 기본 동작입니다."
  syntax:
    content: public bool PrivateImages { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>그렇지 않으면 처리기 개인 이미지를 이용 하 게 하는 경우 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  id: StorageType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "차트 이미지 저장소 형식을 설정 하거나 가져옵니다."
  remarks: "차트 이미지 파일 또는 메모리에 저장할 수 있습니다."
  syntax:
    content: public System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType StorageType { get; set; }
    return:
      type: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
      description: "A <xref href=&quot;System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType&quot;> </xref> 차트 이미지 저장소 형식을 나타내는 열거형 값입니다."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  id: Timeout
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "사용자 지정 처리기의 제한 시간을 가져오거나 설정 합니다."
  remarks: "제한 시간이 만료 되 면 저장 된 차트 이미지 새 차트 이미지에 의해 재정의 되었거나 삭제 됩니다."
  syntax:
    content: public TimeSpan Timeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>차트 이미지의 수명을 나타내는 열거형 값입니다.</xref:System.TimeSpan>"
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  id: Url
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "임시 이미지 파일이 저장 되어 있는 HTTP 경로에 해당 하는 URL을 설정 하거나 가져옵니다."
  syntax:
    content: public string Url { get; set; }
    return:
      type: System.String
      description: "A <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> URL을 나타내는 값입니다."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Item(String)
  nameWithType: ChartHttpHandlerSettings.Item(String)
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(String)
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
  parent: System.Web.UI.DataVisualization.Charting
  isExternal: false
  name: ChartHttpHandlerStorageType
  nameWithType: ChartHttpHandlerStorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Item
  nameWithType: ChartHttpHandlerSettings.Item
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
