### YamlMime:ManagedReference
items:
- uid: System.Printing.PrintJobSettings
  id: PrintJobSettings
  children:
  - System.Printing.PrintJobSettings.CurrentPrintTicket
  - System.Printing.PrintJobSettings.Description
  langs:
  - csharp
  name: PrintJobSettings
  nameWithType: PrintJobSettings
  fullName: System.Printing.PrintJobSettings
  type: Class
  summary: "인쇄 작업에 설명합니다."
  remarks: "<xref:System.Printing.PrintTicket>개체 값의 <xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A>속성, 인쇄 작업에 대 한 자세한 설정이 모두에 저장 합니다.</xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A> </xref:System.Printing.PrintTicket> PrintJobSettings, 부모 설명만 추가합니다.      > [!CAUTION] > 내에서 클래스는 <xref:System.Printing>Windows 서비스 또는 ASP.NET 응용 프로그램 또는 서비스 내에서 사용 하기 위해 네임 스페이스를 사용할 수 없습니다.</xref:System.Printing> 이러한 응용 프로그램 종류 중 하나에서 이러한 클래스를 사용 하는 동안 예기치 않은 문제가 발생할 수 있습니다, 그리고 감소와 같은 서비스 성능 및 런타임 예외입니다.       Windows Forms 응용 프로그램에서 인쇄 하는 경우 참조는 <xref:System.Drawing.Printing>네임 스페이스.</xref:System.Drawing.Printing>"
  syntax:
    content: public class PrintJobSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  id: CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "가져오거나는 <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> 인쇄 작업에 대 한 자세한 설정이 모두 포함 하는 개체입니다."
  remarks: "이 CurrentPrintTicket 속성을 설정의 유효성을 검사 않거나 지정한 <xref:System.Printing.PrintTicket>특정 <xref:System.Printing.PrintQueue>.</xref:System.Printing.PrintQueue> </xref:System.Printing.PrintTicket> 수정  필요한 경우 사용 하 여는 <xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>만드는 메서드를 한 <xref:System.Printing.PrintQueue>-특정 <xref:System.Printing.PrintTicket>지정된 된 프린터에 대 한 유효한.</xref:System.Printing.PrintTicket> </xref:System.Printing.PrintQueue> </xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>"
  syntax:
    content: public System.Printing.PrintTicket CurrentPrintTicket { get; set; }
    return:
      type: System.Printing.PrintTicket
      description: "A <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> 인쇄 매수 등 인쇄 작업에 대 한 모든 세부 정보를 포함 하는 개체 및 스테이플 또는 양면 인쇄 사용 여부."
  overload: System.Printing.PrintJobSettings.CurrentPrintTicket*
  exceptions: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.Description
  id: Description
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "인쇄 작업에 대 한 설명을 가져오거나 설정 합니다."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "<xref:System.String>예를 들어, 분기별 &quot;보고서&quot; 합니다. 인쇄 작업을 설명 하</xref:System.String> 는"
  overload: System.Printing.PrintJobSettings.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintTicket
  parent: System.Printing
  isExternal: false
  name: PrintTicket
  nameWithType: PrintTicket
  fullName: System.Printing.PrintTicket
- uid: System.Printing.PrintJobSettings.Description
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintJobSettings.Description*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
