### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DependentPlatformMissingException
  id: DependentPlatformMissingException
  children:
  - System.Deployment.Application.DependentPlatformMissingException.#ctor
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  - System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  langs:
  - csharp
  name: DependentPlatformMissingException
  nameWithType: DependentPlatformMissingException
  fullName: System.Deployment.Application.DependentPlatformMissingException
  type: Class
  summary: "ClickOnce 배포 및 배포의 정품 인증 하는 동안은 플랫폼 종속성을 찾을 수 없을 때 throw 되는 예외는 실행 되지 않습니다."
  remarks: "배포 매니페스트에 요청한 플랫폼 및 ClickOnce 응용 프로그램을 실행 하려고 하는 플랫폼 사이 불일치가 없는 경우이 예외가 throw 됩니다. 이 컨텍스트에서 &quot;플랫폼&quot;는 운영 체제, 설치 된 버전의 공용 언어 런타임 또는 이전에 설치 된 어셈블리를 참조할 수 있습니다. 예를 들어 ClickOnce 응용 프로그램을 어설션하는 Windows XP 있어야 하며 사용자가이 예외는 Windows 2000에서 응용 프로그램을 실행 하려고 합니다."
  syntax:
    content: 'public class DependentPlatformMissingException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException()
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException()
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> 클래스입니다."
  remarks: "이 생성자는 <xref:System.Exception.Message%2A>&quot;defaultmessagedisplayedbyparameterlessctorwritermustsupply&quot;와 같은 오류를 설명 하는 시스템 제공 메시지로 새 인스턴스의 속성.</xref:System.Exception.Message%2A> 이 메시지는 현재 시스템 문화권을 고려 합니다.       다음 표에서 <xref:System.InsufficientMemoryException>안내 하십시오.</xref:System.InsufficientMemoryException> 인스턴스에 대 한 초기 속성 값을 보여 줍니다.      | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| 지역화 된 오류 메시지 문자열입니다. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DependentPlatformMissingException ();
    parameters: []
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> 지정 된 메시지 오류를 설명 하는 클래스입니다."
  remarks: "다음 표에서 <xref:System.Deployment.Application.DependentPlatformMissingException>안내 하십시오.</xref:System.Deployment.Application.DependentPlatformMissingException> 인스턴스에 대 한 초기 속성 값을 보여 줍니다.      | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| 에 지정 된 오류 메시지 문자열 `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DependentPlatformMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "예외를 설명 하는 메시지입니다. 이 생성자의 호출자는이 문자열이 현재 시스템 문화권에 맞게 지역화 되었는지 확인 해야 합니다."
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> 클래스입니다."
  remarks: "이 생성자는 스트림을 통해 전송 된 예외 개체를 다시 구성 하기 위해 역직렬화 하는 동안 호출 됩니다."
  syntax:
    content: protected DependentPlatformMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "직렬화 된 개체 데이터를 보유 하는 개체입니다."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "소스 또는 대상에 대 한 컨텍스트 정보입니다."
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String,Exception)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> 지정된 된 오류 메시지와 해당 예외의 원인인 내부 예외에 대 한 참조를 사용 하 여 클래스입니다."
  remarks: "이전 예외의 직접적인 결과에 이전 예외에 대 한 참조가 들어 있어야 throw 되는 예외는 <xref:System.Exception.InnerException%2A>속성.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>속성은 생성자에 전달 되는 동일한 값을 반환 하거나 `null` 경우는 <xref:System.Exception.InnerException%2A>생성자에 내부 예외 값을 제공 하지 않는.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       다음 표에서 <xref:System.Deployment.Application.DependentPlatformMissingException>안내 하십시오.</xref:System.Deployment.Application.DependentPlatformMissingException> 인스턴스에 대 한 초기 속성 값을 보여 줍니다.      | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| 에 지정 된 오류 메시지 문자열 `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DependentPlatformMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "예외를 설명 하는 메시지입니다. 이 생성자의 호출자는이 문자열이 현재 시스템 문화권에 맞게 지역화 되었는지 확인 해야 합니다."
    - id: innerException
      type: System.Exception
      description: "현재 예외의 원인인 예외입니다. 경우는 `innerException` 매개 변수가 않습니다 <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>에서 현재 예외가 발생 한 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> 내부 예외를 처리 하는 블록입니다."
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  id: '#ctor(System.String,System.Uri)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: DependentPlatformMissingException(String,Uri)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Deployment.Application.DependentPlatformMissingException&quot;> </xref> 클래스입니다."
  syntax:
    content: public DependentPlatformMissingException (string message, Uri supportUrl);
    parameters:
    - id: message
      type: System.String
      description: "예외 메시지입니다."
    - id: supportUrl
      type: System.Uri
      description: "제품 지원 정보를 얻기 위해 방문할 URL입니다."
  overload: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "개체 데이터를 가져옵니다."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "직렬화 된 개체 데이터를 보유 하는 개체입니다."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "소스 또는 대상에 대 한 컨텍스트 정보입니다."
  overload: System.Deployment.Application.DependentPlatformMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  id: SupportUrl
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
  fullName: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "발생 한 문제에 대 한 지원을 찾을 수 있는 여부를 나타내는 URI를 가져옵니다."
  syntax:
    content: public Uri SupportUrl { get; }
    return:
      type: System.Uri
      description: "발생 한 문제에 대 한 지원을 찾을 수 있는 여부를 나타내는 URI입니다."
  overload: System.Deployment.Application.DependentPlatformMissingException.SupportUrl*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException()
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException()
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException()
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String,Exception)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException(String,Uri)
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
  fullName: System.Deployment.Application.DependentPlatformMissingException.DependentPlatformMissingException(String,Uri)
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
  fullName: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor*
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: DependentPlatformMissingException
  nameWithType: DependentPlatformMissingException.DependentPlatformMissingException
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData*
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: DependentPlatformMissingException.GetObjectData
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl*
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
