### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection
  id: CommonBehaviorsSection
  children:
  - System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  - System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  - System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  - System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  langs:
  - csharp
  name: CommonBehaviorsSection
  nameWithType: CommonBehaviorsSection
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection
  type: Class
  summary: "모두에 적용 되는 동작의 목록을 포함 하는 구성 섹션을 나타냅니다 [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] 의 동작이 하기 전에 컴퓨터의 서비스는 <xref uid=&quot;langword_csharp_behaviors&quot; name=&quot;behaviors&quot; href=&quot;&quot;> </xref> 섹션이 적용 됩니다."
  remarks: "이 구성 섹션은 Machine.config 파일에 정의 됩니다. 모두에 적용 되는 동작의 목록을 포함 [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] 에서 동작 하기 전에 컴퓨터의 서비스는 `behaviors` 섹션이 적용 됩니다. 동작을 둘 다에 정의 된 경우 섹션, 동작에는 `behaviors` 섹션 우선 합니다."
  syntax:
    content: 'public class CommonBehaviorsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: CommonBehaviorsSection()
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection()
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.CommonBehaviorsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.CommonBehaviorsSection&quot;> </xref> 클래스입니다."
  syntax:
    content: public CommonBehaviorsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  id: EndpointBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "모든 자식 항목을 가져옵니다 <xref uid=&quot;langword_csharp_EndpointBehavior&quot; name=&quot;EndpointBehavior&quot; href=&quot;&quot;> </xref> 고유한 이름으로 식별 되는 요소입니다."
  syntax:
    content: public System.ServiceModel.Configuration.CommonEndpointBehaviorElement EndpointBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
      description: "자식 항목을 <xref uid=&quot;langword_csharp_EndpointBehavior&quot; name=&quot;EndpointBehavior&quot; href=&quot;&quot;> </xref> 고유한 이름으로 식별 되는 요소입니다."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 의 컬렉션을 포함 하는 인스턴스 <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> 특성 일 수 있는 개체 또는 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 이 구성 요소 개체입니다."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 의 컬렉션을 포함 하는 인스턴스 <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> 특성 일 수 있는 개체 또는 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 이 구성 요소 개체입니다."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  id: ServiceBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "모든 자식 항목을 가져옵니다 <xref uid=&quot;langword_csharp_serviceBehavior&quot; name=&quot;serviceBehavior&quot; href=&quot;&quot;> </xref> 고유한 이름으로 식별 되는 요소입니다."
  syntax:
    content: public System.ServiceModel.Configuration.CommonServiceBehaviorElement ServiceBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.CommonServiceBehaviorElement
      description: "자식 항목을 <xref uid=&quot;langword_csharp_serviceBehavior&quot; name=&quot;serviceBehavior&quot; href=&quot;&quot;> </xref> 고유한 이름으로 식별 되는 요소입니다."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: CommonBehaviorsSection()
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection()
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.CommonBehaviorsSection()
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: CommonEndpointBehaviorElement
  nameWithType: CommonEndpointBehaviorElement
  fullName: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
- uid: System.ServiceModel.Configuration.CommonServiceBehaviorElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: CommonServiceBehaviorElement
  nameWithType: CommonServiceBehaviorElement
  fullName: System.ServiceModel.Configuration.CommonServiceBehaviorElement
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: CommonBehaviorsSection
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
