### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageabilityAttribute
  id: SettingsManageabilityAttribute
  children:
  - System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  - System.Configuration.SettingsManageabilityAttribute.Manageability
  langs:
  - csharp
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute
  fullName: System.Configuration.SettingsManageabilityAttribute
  type: Class
  summary: "응용 프로그램 설정 속성에 대 한 특별 한 서비스를 지정합니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "SettingsManageabilityAttribute 특수, 미리 정의 된 서비스를 개별 응용 프로그램 설정 속성 및 속성 그룹에 제공 해야 함을 나타냅니다. 대부분의 이러한 서비스는 Windows 운영 체제에 의해 제공 됩니다.       응용 프로그램 설정 속성 및 사용에 대 한 자세한 내용은 참조 [Windows Forms에 대 한 응용 프로그램 설정](~/add/includes/ajax-current-ext-md.md)합니다."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsManageabilityAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  id: '#ctor(System.Configuration.SettingsManageability)'
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: System.Configuration.SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.SettingsManageabilityAttribute&quot;> </xref> 클래스입니다."
  remarks: "으로 정의 된 값을 함께 결합 하 여 여러 서비스를 요청할 수 있습니다는 <xref:System.Configuration.SettingsManageability>논리적 열거형 `OR` 연산자.</xref:System.Configuration.SettingsManageability>"
  syntax:
    content: public SettingsManageabilityAttribute (System.Configuration.SettingsManageability manageability);
    parameters:
    - id: manageability
      type: System.Configuration.SettingsManageability
      description: "A <xref href=&quot;System.Configuration.SettingsManageability&quot;> </xref> 요청 되는 서비스를 열거 하는 값입니다."
  overload: System.Configuration.SettingsManageabilityAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  id: Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: System.Configuration.SettingsManageabilityAttribute.Manageability
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "요청 된 특별 한 서비스의 집합을 가져옵니다."
  remarks: "이 속성는 <xref:System.Configuration.SettingsManageabilityAttribute.%23ctor%2A>생성자.</xref:System.Configuration.SettingsManageabilityAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SettingsManageability Manageability { get; }
    return:
      type: System.Configuration.SettingsManageability
      description: "논리를 사용 하 여 결과인 값 <xref uid=&quot;langword_csharp_OR&quot; name=&quot;OR&quot; href=&quot;&quot;> </xref> 모든 결합할 연산자는 <xref href=&quot;System.Configuration.SettingsManageability&quot;> </xref> 요청 된 서비스에 해당 하는 열거형 값입니다."
  overload: System.Configuration.SettingsManageabilityAttribute.Manageability*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: System.Configuration.SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: System.Configuration.SettingsManageabilityAttribute.Manageability
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
