### YamlMime:ManagedReference
items:
- uid: System.Configuration.KeyValueConfigurationElement
  id: KeyValueConfigurationElement
  children:
  - System.Configuration.KeyValueConfigurationElement.#ctor(System.String,System.String)
  - System.Configuration.KeyValueConfigurationElement.Init
  - System.Configuration.KeyValueConfigurationElement.Key
  - System.Configuration.KeyValueConfigurationElement.Properties
  - System.Configuration.KeyValueConfigurationElement.Value
  langs:
  - csharp
  name: KeyValueConfigurationElement
  nameWithType: KeyValueConfigurationElement
  fullName: System.Configuration.KeyValueConfigurationElement
  type: Class
  summary: "키/값 쌍을 포함 하는 구성 요소를 나타냅니다."
  remarks: "<xref:System.Configuration.ConfigurationElement>. 기본 클래스</xref:System.Configuration.ConfigurationElement> 에서 상속 KeyValueConfigurationElement 개체 <xref:System.Configuration.ConfigurationElement>개체 구성 파일 내에서 요소를 나타냅니다.</xref:System.Configuration.ConfigurationElement> 에 속할 수 있는 KeyValueConfigurationElement 개체는 <xref:System.Configuration.KeyValueConfigurationCollection>컬렉션.</xref:System.Configuration.KeyValueConfigurationCollection>"
  example:
  - "The following code example demonstrates how to use members of the KeyValueConfigurationElement class.  \n  \n [!code-cs[System.Configuration.KeyValueConfigurationCollection#1](~/add/codesnippet/csharp/t-system.configuration.k_1_1.cs)]\n [!code-vb[System.Configuration.KeyValueConfigurationCollection#1](~/add/codesnippet/visualbasic/t-system.configuration.k_1_1.vb)]"
  syntax:
    content: 'public class KeyValueConfigurationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Configuration.KeyValueConfigurationElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: KeyValueConfigurationElement(String,String)
  nameWithType: KeyValueConfigurationElement.KeyValueConfigurationElement(String,String)
  fullName: System.Configuration.KeyValueConfigurationElement.KeyValueConfigurationElement(String,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.KeyValueConfigurationElement&quot;> </xref> 클래스 제공된 된 매개 변수 기반으로 합니다."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the KeyValueConfigurationElement constructor. This code example is part of a larger example provided for the <xref:System.Configuration.KeyValueConfigurationCollection> class overview.  \n  \n [!code-cs[System.Configuration.KeyValueConfigurationCollection#2](~/add/codesnippet/csharp/fdb89f7c-58dc-453b-9739-_1.cs)]\n [!code-vb[System.Configuration.KeyValueConfigurationCollection#2](~/add/codesnippet/visualbasic/fdb89f7c-58dc-453b-9739-_1.vb)]"
  syntax:
    content: public KeyValueConfigurationElement (string key, string value);
    parameters:
    - id: key
      type: System.String
      description: "키에서 <xref href=&quot;System.Configuration.KeyValueConfigurationElement&quot;> </xref>합니다."
    - id: value
      type: System.String
      description: "값은 <xref href=&quot;System.Configuration.KeyValueConfigurationElement&quot;> </xref>합니다."
  overload: System.Configuration.KeyValueConfigurationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.KeyValueConfigurationElement.Init
  id: Init
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: Init()
  nameWithType: KeyValueConfigurationElement.Init()
  fullName: System.Configuration.KeyValueConfigurationElement.Init()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "설정의 <xref href=&quot;System.Configuration.KeyValueConfigurationElement&quot;> </xref> 를 초기 상태로 개체입니다."
  syntax:
    content: protected override void Init ();
    parameters: []
  overload: System.Configuration.KeyValueConfigurationElement.Init*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.KeyValueConfigurationElement.Key
  id: Key
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: Key
  nameWithType: KeyValueConfigurationElement.Key
  fullName: System.Configuration.KeyValueConfigurationElement.Key
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "키를 가져옵니다는 <xref href=&quot;System.Configuration.KeyValueConfigurationElement&quot;> </xref> 개체입니다."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the Key property. This code example is part of a larger example provided for the <xref:System.Configuration.KeyValueConfigurationCollection> class overview.  \n  \n [!code-cs[System.Configuration.KeyValueConfigurationCollection#5](~/add/codesnippet/csharp/p-system.configuration.k_0_1.cs)]\n [!code-vb[System.Configuration.KeyValueConfigurationCollection#5](~/add/codesnippet/visualbasic/p-system.configuration.k_0_1.vb)]"
  syntax:
    content: public string Key { get; }
    return:
      type: System.String
      description: "키에서 <xref href=&quot;System.Configuration.KeyValueConfigurationElement&quot;> </xref>합니다."
  overload: System.Configuration.KeyValueConfigurationElement.Key*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.KeyValueConfigurationElement.Properties
  id: Properties
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: Properties
  nameWithType: KeyValueConfigurationElement.Properties
  fullName: System.Configuration.KeyValueConfigurationElement.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "속성의 컬렉션을 가져옵니다."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "<xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 요소에 대 한 속성입니다."
  overload: System.Configuration.KeyValueConfigurationElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.KeyValueConfigurationElement.Value
  id: Value
  parent: System.Configuration.KeyValueConfigurationElement
  langs:
  - csharp
  name: Value
  nameWithType: KeyValueConfigurationElement.Value
  fullName: System.Configuration.KeyValueConfigurationElement.Value
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "값을 가져오거나 설정 합니다.는 <xref href=&quot;System.Configuration.KeyValueConfigurationElement&quot;> </xref> 개체입니다."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the Value property. This code example is part of a larger example provided for the <xref:System.Configuration.KeyValueConfigurationCollection> class overview.  \n  \n [!code-cs[System.Configuration.KeyValueConfigurationCollection#5](~/add/codesnippet/csharp/p-system.configuration.k_1_1.cs)]\n [!code-vb[System.Configuration.KeyValueConfigurationCollection#5](~/add/codesnippet/visualbasic/p-system.configuration.k_1_1.vb)]"
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: "값은 <xref href=&quot;System.Configuration.KeyValueConfigurationElement&quot;> </xref>합니다."
  overload: System.Configuration.KeyValueConfigurationElement.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.KeyValueConfigurationElement.#ctor(System.String,System.String)
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: KeyValueConfigurationElement(String,String)
  nameWithType: KeyValueConfigurationElement.KeyValueConfigurationElement(String,String)
  fullName: System.Configuration.KeyValueConfigurationElement.KeyValueConfigurationElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.KeyValueConfigurationElement.Init
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Init()
  nameWithType: KeyValueConfigurationElement.Init()
  fullName: System.Configuration.KeyValueConfigurationElement.Init()
- uid: System.Configuration.KeyValueConfigurationElement.Key
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Key
  nameWithType: KeyValueConfigurationElement.Key
  fullName: System.Configuration.KeyValueConfigurationElement.Key
- uid: System.Configuration.KeyValueConfigurationElement.Properties
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Properties
  nameWithType: KeyValueConfigurationElement.Properties
  fullName: System.Configuration.KeyValueConfigurationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.KeyValueConfigurationElement.Value
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Value
  nameWithType: KeyValueConfigurationElement.Value
  fullName: System.Configuration.KeyValueConfigurationElement.Value
- uid: System.Configuration.KeyValueConfigurationElement.#ctor*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: KeyValueConfigurationElement
  nameWithType: KeyValueConfigurationElement.KeyValueConfigurationElement
- uid: System.Configuration.KeyValueConfigurationElement.Init*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Init
  nameWithType: KeyValueConfigurationElement.Init
- uid: System.Configuration.KeyValueConfigurationElement.Key*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Key
  nameWithType: KeyValueConfigurationElement.Key
- uid: System.Configuration.KeyValueConfigurationElement.Properties*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Properties
  nameWithType: KeyValueConfigurationElement.Properties
- uid: System.Configuration.KeyValueConfigurationElement.Value*
  parent: System.Configuration.KeyValueConfigurationElement
  isExternal: false
  name: Value
  nameWithType: KeyValueConfigurationElement.Value
