### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  id: NonDualMessageSecurityOverHttpElement
  children:
  - System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  - System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  - System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
  langs:
  - csharp
  name: NonDualMessageSecurityOverHttpElement
  nameWithType: NonDualMessageSecurityOverHttpElement
  fullName: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  type: Class
  summary: "비 이중 서비스 계약에 대 한 HTTP를 사용 하 여 보낸 메시지의 보안에 대 한 구성 설정을 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: 'public sealed class NonDualMessageSecurityOverHttpElement : System.ServiceModel.Configuration.MessageSecurityOverHttpElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  langs:
  - csharp
  name: NonDualMessageSecurityOverHttpElement()
  nameWithType: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
  fullName: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public NonDualMessageSecurityOverHttpElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  id: EstablishSecurityContext
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  langs:
  - csharp
  name: EstablishSecurityContext
  nameWithType: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  fullName: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "보안 컨텍스트가 설정 되는지 여부를 지정 하는 부울 값을 가져오거나 설정 합니다."
  syntax:
    content: public bool EstablishSecurityContext { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>보안 컨텍스트; 설정 하는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  langs:
  - csharp
  name: Properties
  nameWithType: NonDualMessageSecurityOverHttpElement.Properties
  fullName: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.MessageSecurityOverHttpElement
  isExternal: false
  name: System.ServiceModel.Configuration.MessageSecurityOverHttpElement
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: NonDualMessageSecurityOverHttpElement()
  nameWithType: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
  fullName: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: EstablishSecurityContext
  nameWithType: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  fullName: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: Properties
  nameWithType: NonDualMessageSecurityOverHttpElement.Properties
  fullName: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor*
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: NonDualMessageSecurityOverHttpElement
  nameWithType: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext*
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: EstablishSecurityContext
  nameWithType: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties*
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: Properties
  nameWithType: NonDualMessageSecurityOverHttpElement.Properties
