### YamlMime:ManagedReference
items:
- uid: System.ComponentModel.SettingsBindableAttribute
  id: SettingsBindableAttribute
  children:
  - System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  - System.ComponentModel.SettingsBindableAttribute.Bindable
  - System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  - System.ComponentModel.SettingsBindableAttribute.GetHashCode
  - System.ComponentModel.SettingsBindableAttribute.No
  - System.ComponentModel.SettingsBindableAttribute.Yes
  langs:
  - csharp
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute
  fullName: System.ComponentModel.SettingsBindableAttribute
  type: Class
  summary: "응용 프로그램 설정에 구성 요소 속성을 바인딩할 수 있습니다 시기를 지정 합니다."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsBindableAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: SettingsBindableAttribute(Boolean)
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  fullName: System.ComponentModel.SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ComponentModel.SettingsBindableAttribute&quot;> </xref> 클래스입니다."
  syntax:
    content: public SettingsBindableAttribute (bool bindable);
    parameters:
    - id: bindable
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>속성 설정을; 바인딩하에 적합 한 임을 지정 하려면 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ComponentModel.SettingsBindableAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable
  id: Bindable
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
  fullName: System.ComponentModel.SettingsBindableAttribute.Bindable
  type: Property
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "속성에 설정을 바인딩할 적합 한지 여부를 나타내는 값을 가져옵니다."
  syntax:
    content: public bool Bindable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>속성이;에 설정을 바인딩할 적절 한 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ComponentModel.SettingsBindableAttribute.Bindable*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: SettingsBindableAttribute.Equals(Object)
  fullName: System.ComponentModel.SettingsBindableAttribute.Equals(Object)
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "이 인스턴스가 지정한 개체와 같은지 여부를 나타내는 값을 반환 합니다."
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: "<xref:System.Object>이 인스턴스 또는 null 참조와 비교할 개체 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> Visual basic에서).</xref:System.Object>"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>경우 <code> obj </code> 유형과;이 인스턴스의 값과 같으면 그렇지 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ComponentModel.SettingsBindableAttribute.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode
  id: GetHashCode
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: SettingsBindableAttribute.GetHashCode()
  fullName: System.ComponentModel.SettingsBindableAttribute.GetHashCode()
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "이 인스턴스에 대 한 해시 코드를 반환합니다."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "부호 있는 32 비트 정수 해시 코드입니다."
  overload: System.ComponentModel.SettingsBindableAttribute.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.No
  id: No
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: No
  nameWithType: SettingsBindableAttribute.No
  fullName: System.ComponentModel.SettingsBindableAttribute.No
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "속성에 설정을 바인딩할 적합 하지 않음을 지정 합니다."
  syntax:
    content: public static readonly System.ComponentModel.SettingsBindableAttribute No;
    return:
      type: System.ComponentModel.SettingsBindableAttribute
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Yes
  id: Yes
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Yes
  nameWithType: SettingsBindableAttribute.Yes
  fullName: System.ComponentModel.SettingsBindableAttribute.Yes
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "속성에 설정을 바인딩할 적절 한 임을 지정 합니다."
  syntax:
    content: public static readonly System.ComponentModel.SettingsBindableAttribute Yes;
    return:
      type: System.ComponentModel.SettingsBindableAttribute
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: SettingsBindableAttribute(Boolean)
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  fullName: System.ComponentModel.SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
  fullName: System.ComponentModel.SettingsBindableAttribute.Bindable
- uid: System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Equals(Object)
  nameWithType: SettingsBindableAttribute.Equals(Object)
  fullName: System.ComponentModel.SettingsBindableAttribute.Equals(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: GetHashCode()
  nameWithType: SettingsBindableAttribute.GetHashCode()
  fullName: System.ComponentModel.SettingsBindableAttribute.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ComponentModel.SettingsBindableAttribute.No
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: No
  nameWithType: SettingsBindableAttribute.No
  fullName: System.ComponentModel.SettingsBindableAttribute.No
- uid: System.ComponentModel.SettingsBindableAttribute
  parent: System.ComponentModel
  isExternal: false
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute
  fullName: System.ComponentModel.SettingsBindableAttribute
- uid: System.ComponentModel.SettingsBindableAttribute.Yes
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Yes
  nameWithType: SettingsBindableAttribute.Yes
  fullName: System.ComponentModel.SettingsBindableAttribute.Yes
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
- uid: System.ComponentModel.SettingsBindableAttribute.Equals*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Equals
  nameWithType: SettingsBindableAttribute.Equals
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: GetHashCode
  nameWithType: SettingsBindableAttribute.GetHashCode
