### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlObjectReaderSettings
  id: XamlObjectReaderSettings
  children:
  - System.Xaml.XamlObjectReaderSettings.#ctor
  - System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  langs:
  - csharp
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings
  fullName: System.Xaml.XamlObjectReaderSettings
  type: Class
  summary: "처리 규칙 또는 대 한 옵션 설정을 지정는 <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref>합니다."
  syntax:
    content: 'public class XamlObjectReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Xaml.XamlObjectReaderSettings&quot;> </xref> 클래스입니다."
  syntax:
    content: public XamlObjectReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlObjectReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  id: RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "있는지 여부를 사용 하는 작성기를 결정 하는 값을 가져오거나 설정 합니다. 연결 된 <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref> 컨텍스트 설정 디자이너를 사용 하 여 명시적으로 콘텐츠를 쓰는 데 해야 합니다."
  remarks: "이 설정은 내부적으로 쿼리 됩니다. 컨텍스트에 대 한 다음 동작에 영향을 줍니다 하는 <xref:System.Xaml.XamlObjectReader>에 전달 <xref:System.Xaml.XamlWriter>:-The RequireExplicitContentVisibility 동작은 속성에만 적용 됩니다 위치 <xref:System.Xaml.XamlMember.IsWritePublic%2A>은 `false`, 및 시기는 `ShouldSerialize` 패턴은 속성 값에 사용할 수 없습니다.</xref:System.Xaml.XamlMember.IsWritePublic%2A> </xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlObjectReader>      -첫 번째 글머리 기호의 문을 true 고 RequireExplicitContentVisibility가 있으면 `true`, 디자이너 설정 속성 내용으로 출력을 작성 또는 속성은 암시적으로 간주 하는지 여부를 확인 합니다. .NET Framework XAML 서비스에서 내부 Api를 통해 이며 읽기 기반 디자이너 설정에 대 한 액세스 <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>백업 어셈블리의.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute> 이 경우 내부 코드 값을 확인 <xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName>속성에 해당 출력을 씁니다.</xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName> 이렇게 하지 않으면 콘텐츠 암시적 간주 됩니다.      -문이 첫 번째 글머리 기호의 경우 `true`, 및 RequireExplicitContentVisibility은 `false`, 속성은 항상 출력을 작성 하 고 <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>백업 어셈블리의은 관련이 없습니다.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>"
  syntax:
    content: public bool RequireExplicitContentVisibility { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>이 컨텍스트를 사용 하는 작성기가 쓰기를 위한 설정 디자이너를 사용 하도록 지정 하려면 <xref:System.Xaml.XamlMember.IsWritePublic*>를 보고 하는 경우에는 콘텐츠 출력 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> 디자이너 설정 무시 해야 하는 경우.</xref:System.Xaml.XamlMember.IsWritePublic*>"
  overload: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlObjectReaderSettings.#ctor*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
