### YamlMime:ManagedReference
items:
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  id: DateTimeSerializationSection
  children:
  - System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor
  - System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
  - System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
  langs:
  - csharp
  name: DateTimeSerializationSection
  nameWithType: DateTimeSerializationSection
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  type: Class
  summary: "XML serialization에 대 한 구성 설정을 처리 <xref:System.DateTime>인스턴스.</xref:System.DateTime>"
  remarks: "이 클래스는 구성 요소는 처리 [ \\&lt; dateTimeSerialization\\&gt; 요소](../Topic/%3CdateTimeSerialization%3E%20Element.md) 아래는 [ \\&lt;system.xml.serialization\\&gt; 요소](../Topic/%3Csystem.xml.serialization%3E%20Element.md)합니다. 구성 파일에 대 한 자세한 내용은 참조 [구성 파일 스키마](~/add/includes/ajax-current-ext-md.md)합니다."
  syntax:
    content: 'public sealed class DateTimeSerializationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor
  id: '#ctor'
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  langs:
  - csharp
  name: DateTimeSerializationSection()
  nameWithType: DateTimeSerializationSection.DateTimeSerializationSection()
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationSection()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Xml.Serialization.Configuration.DateTimeSerializationSection&quot;> </xref> 클래스입니다."
  syntax:
    content: public DateTimeSerializationSection ();
    parameters: []
  overload: System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
  id: Mode
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  langs:
  - csharp
  name: Mode
  nameWithType: DateTimeSerializationSection.Mode
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Serialization 형식을 결정 하는 값을 가져오거나 설정 합니다."
  remarks: "처리할 때이 속성은 사용 된 `mode` 특성에는 [ \\&lt; dateTimeSerialization\\&gt; 요소](../Topic/%3CdateTimeSerialization%3E%20Element.md)합니다."
  syntax:
    content: public System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode Mode { get; set; }
    return:
      type: System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode
      description: "중 하나는 <xref:System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode>값.</xref:System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode>"
  overload: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
  id: Properties
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  langs:
  - csharp
  name: Properties
  nameWithType: DateTimeSerializationSection.Properties
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: DateTimeSerializationSection()
  nameWithType: DateTimeSerializationSection.DateTimeSerializationSection()
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationSection()
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: Mode
  nameWithType: DateTimeSerializationSection.Mode
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode
  parent: System.Xml.Serialization.Configuration
  isExternal: false
  name: DateTimeSerializationSection+DateTimeSerializationMode
  nameWithType: DateTimeSerializationSection+DateTimeSerializationMode
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection+DateTimeSerializationMode
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: Properties
  nameWithType: DateTimeSerializationSection.Properties
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor*
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: DateTimeSerializationSection
  nameWithType: DateTimeSerializationSection.DateTimeSerializationSection
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode*
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: Mode
  nameWithType: DateTimeSerializationSection.Mode
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties*
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: Properties
  nameWithType: DateTimeSerializationSection.Properties
