### YamlMime:ManagedReference
items:
- uid: System.Configuration.LongValidator
  id: LongValidator
  children:
  - System.Configuration.LongValidator.#ctor(System.Int64,System.Int64)
  - System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean)
  - System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean,System.Int64)
  - System.Configuration.LongValidator.CanValidate(System.Type)
  - System.Configuration.LongValidator.Validate(System.Object)
  langs:
  - csharp
  name: LongValidator
  nameWithType: LongValidator
  fullName: System.Configuration.LongValidator
  type: Class
  summary: "유효성을 검사 한 <xref:System.Int64>값.</xref:System.Int64>"
  remarks: "LongValidator 하도록 만드는 데 사용 되는 `long` (64 비트 부호 있는 정수) 특정 기준을 충족 합니다. 유효성 검사에 대 한 조건은 LongValidator 클래스의 인스턴스를 만들 때 설정 됩니다. <xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%29>생성자를 사용 하면는 `long` 유효성을 검사할 값이 최소 및 최대 길이 모두에 따르는지.</xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%29> <xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%2CSystem.Boolean%29>생성자의 최소값 및 최대값을 확인 <xref:System.Int64>유효성 검사 범위는 배타적 여부 뿐만 아니라.</xref:System.Int64> </xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%2CSystem.Boolean%29> <xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%2CSystem.Boolean%2CSystem.Int64%29>생성자는 이전 세 가지 매개 변수를 확인 검사 여부는 <xref:System.Int64>값은 특정 해상도 값과 같습니다.</xref:System.Int64> </xref:System.Configuration.LongValidator.%23ctor%28System.Int64%2CSystem.Int64%2CSystem.Boolean%2CSystem.Int64%29>       <xref:System.Configuration.LongValidator.CanValidate%2A>메서드 유효성을 검사할 개체 유형이 예상된 유형과 일치 하는지 여부를 확인 합니다.</xref:System.Configuration.LongValidator.CanValidate%2A> 유효성 검사 중인 개체의 매개 변수로 전달 되는 <xref:System.Configuration.LongValidator.Validate%2A>메서드.</xref:System.Configuration.LongValidator.Validate%2A>"
  example:
  - "The following code example demonstrates how to use the LongValidator type.  \n  \n [!code-vb[System.Configuration.LongValidator#1](~/add/codesnippet/visualbasic/t-system.configuration.l_1_1.vb)]\n [!code-cs[System.Configuration.LongValidator#1](~/add/codesnippet/csharp/t-system.configuration.l_1_1.cs)]"
  syntax:
    content: 'public class LongValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64)
  id: '#ctor(System.Int64,System.Int64)'
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: LongValidator(Int64,Int64)
  nameWithType: LongValidator.LongValidator(Int64,Int64)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> 클래스입니다."
  remarks: "LongValidator 생성자 따르는지 확인은 long 값을 확인 하는 최소값과 최대 길이입니다."
  syntax:
    content: public LongValidator (long minValue, long maxValue);
    parameters:
    - id: minValue
      type: System.Int64
      description: "<xref:System.Int64>의 최소 길이 지정 하는 값은 <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> 값.</xref:System.Int64>"
    - id: maxValue
      type: System.Int64
      description: "<xref:System.Int64>의 최대 길이 지정 하는 값은 <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> 값.</xref:System.Int64>"
  overload: System.Configuration.LongValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean)
  id: '#ctor(System.Int64,System.Int64,System.Boolean)'
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: LongValidator(Int64,Int64,Boolean)
  nameWithType: LongValidator.LongValidator(Int64,Int64,Boolean)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64,Boolean)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> 클래스입니다."
  remarks: "최소값 및 최대값 확인 LongValidator 생성자를 사용 하는 경우 <xref:System.Int64>유효성 검사 범위는 배타적 여부 뿐만 아니라.</xref:System.Int64> 경우는 `rangeIsExclusive` 로 설정 된 `true`, <xref:System.Int64>값 사이의 아니어야 `minValue` 및 `maxValue`.</xref:System.Int64>"
  example:
  - "The following code example demonstrates how to use the LongValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.LongValidator> class.  \n  \n [!code-vb[System.Configuration.LongValidator#2](~/add/codesnippet/visualbasic/2847484f-ec91-486e-9c9a-_1.vb)]\n [!code-cs[System.Configuration.LongValidator#2](~/add/codesnippet/csharp/2847484f-ec91-486e-9c9a-_1.cs)]"
  syntax:
    content: public LongValidator (long minValue, long maxValue, bool rangeIsExclusive);
    parameters:
    - id: minValue
      type: System.Int64
      description: "<xref:System.Int64>의 최소 길이 지정 하는 값은 <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> 값.</xref:System.Int64>"
    - id: maxValue
      type: System.Int64
      description: "<xref:System.Int64>의 최대 길이 지정 하는 값은 <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> 값.</xref:System.Int64>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "A <xref:System.Boolean>유효성 검사 범위는 배타적 있는지 여부를 지정 하는 값입니다.</xref:System.Boolean>"
  overload: System.Configuration.LongValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean,System.Int64)
  id: '#ctor(System.Int64,System.Int64,System.Boolean,System.Int64)'
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: LongValidator(Int64,Int64,Boolean,Int64)
  nameWithType: LongValidator.LongValidator(Int64,Int64,Boolean,Int64)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64,Boolean,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> 클래스입니다."
  remarks: "지정 하는 경우는 `resolution`, <xref:System.Int64>유효성을 검사할 값 유효성 검사를 통과 하려면 해당 값과 같지 여야 합니다.</xref:System.Int64>"
  syntax:
    content: public LongValidator (long minValue, long maxValue, bool rangeIsExclusive, long resolution);
    parameters:
    - id: minValue
      type: System.Int64
      description: "<xref:System.Int64>의 최소 길이 지정 하는 값은 <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> 값.</xref:System.Int64>"
    - id: maxValue
      type: System.Int64
      description: "<xref:System.Int64>의 최대 길이 지정 하는 값은 <xref uid=&quot;langword_csharp_long&quot; name=&quot;long&quot; href=&quot;&quot;> </xref> 값.</xref:System.Int64>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "A <xref:System.Boolean>유효성 검사 범위는 배타적 있는지 여부를 지정 하는 값입니다.</xref:System.Boolean>"
    - id: resolution
      type: System.Int64
      description: "<xref:System.Int64>일치 해야 하는 특정 값을 지정 하는 값입니다.</xref:System.Int64>"
  overload: System.Configuration.LongValidator.#ctor*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "<code>resolution</code> is equal to or less than <xref uid=\"langword_csharp_0\" name=\"0\" href=\"\"></xref>.  \n  \n \\- or -  \n  \n <code>maxValue</code> is less than <code>minValue</code>."
  platform:
  - net462
- uid: System.Configuration.LongValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: LongValidator.CanValidate(Type)
  fullName: System.Configuration.LongValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "개체 형식의 유효성을 검사할 수 있는지 여부를 결정 합니다."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.LongValidator> class.  \n  \n [!code-vb[System.Configuration.LongValidator#3](~/add/codesnippet/visualbasic/m-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.LongValidator#3](~/add/codesnippet/csharp/m-system.configuration.l_0_1.cs)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "개체의 형식입니다."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>경우는 <code> type </code> 매개 변수와 일치는 <xref:System.Int64>값입니다; 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Int64>"
  overload: System.Configuration.LongValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.LongValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: LongValidator.Validate(Object)
  fullName: System.Configuration.LongValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "개체의 값이 유효한 지 확인 합니다."
  remarks: "<xref:System.Configuration.LongValidator>유효성을 검사 하는 데 필요한 규칙을 포함 하는 클래스는 <xref:System.Int64>개체입니다.</xref:System.Int64> </xref:System.Configuration.LongValidator> 규칙 설정의 인스턴스는 <xref:System.Configuration.LongValidator>클래스가 만들어집니다.</xref:System.Configuration.LongValidator> 유효성을 검사할 개체의 Validate 메서드 매개 변수로 전달 됩니다."
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.LongValidator> class.  \n  \n [!code-vb[System.Configuration.LongValidator#4](~/add/codesnippet/visualbasic/m-system.configuration.l_1_1.vb)]\n [!code-cs[System.Configuration.LongValidator#4](~/add/codesnippet/csharp/m-system.configuration.l_1_1.cs)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "개체의 값입니다."
  overload: System.Configuration.LongValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: LongValidator(Int64,Int64)
  nameWithType: LongValidator.LongValidator(Int64,Int64)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64)
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: LongValidator(Int64,Int64,Boolean)
  nameWithType: LongValidator.LongValidator(Int64,Int64,Boolean)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.LongValidator.#ctor(System.Int64,System.Int64,System.Boolean,System.Int64)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: LongValidator(Int64,Int64,Boolean,Int64)
  nameWithType: LongValidator.LongValidator(Int64,Int64,Boolean,Int64)
  fullName: System.Configuration.LongValidator.LongValidator(Int64,Int64,Boolean,Int64)
- uid: System.Configuration.LongValidator.CanValidate(System.Type)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: LongValidator.CanValidate(Type)
  fullName: System.Configuration.LongValidator.CanValidate(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.LongValidator.Validate(System.Object)
  parent: System.Configuration.LongValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: LongValidator.Validate(Object)
  fullName: System.Configuration.LongValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.LongValidator.#ctor*
  parent: System.Configuration.LongValidator
  isExternal: false
  name: LongValidator
  nameWithType: LongValidator.LongValidator
- uid: System.Configuration.LongValidator.CanValidate*
  parent: System.Configuration.LongValidator
  isExternal: false
  name: CanValidate
  nameWithType: LongValidator.CanValidate
- uid: System.Configuration.LongValidator.Validate*
  parent: System.Configuration.LongValidator
  isExternal: false
  name: Validate
  nameWithType: LongValidator.Validate
