### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup
  id: CachingSectionGroup
  children:
  - System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  - System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  langs:
  - csharp
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup
  type: Class
  summary: "구성 섹션 같은.net Framework 캐싱 정의합니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "캐싱 섹션을 정의 하는 CachingSectionGroup 클래스 (`system.runtime.caching`) 구성 파일에 대 한 합니다. 이 섹션에는 다양 한 형식의 캐시를 구성 하는 데 사용 되는 요소가 포함 되어 있습니다. ASP.NET 캐싱 섹션에서 제공 하는 유일한 요소는 요소입니다. 이 요소 <xref:System.Runtime.Caching.MemoryCache>클래스</xref:System.Runtime.Caching.MemoryCache> 를 기반으로 하는 캐시를 구성 합니다."
  syntax:
    content: 'public sealed class CachingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
  type: Constructor
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Caching.Configuration.CachingSectionGroup&quot;> </xref> 클래스입니다."
  syntax:
    content: public CachingSectionGroup ();
    parameters: []
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  id: MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "컬렉션을 가져옵니다 <xref href=&quot;System.Runtime.Caching.Configuration.MemoryCacheElement&quot;> </xref> 개체입니다."
  remarks: "MemoryCaches 속성의 컬렉션을 반환 <xref:System.Runtime.Caching.Configuration.MemoryCacheSection>캐싱 섹션 부모에서 개체입니다.</xref:System.Runtime.Caching.Configuration.MemoryCacheSection>"
  syntax:
    content: public System.Runtime.Caching.Configuration.MemoryCacheSection MemoryCaches { get; }
    return:
      type: System.Runtime.Caching.Configuration.MemoryCacheSection
      description: "캐시 영역 개체의 컬렉션입니다."
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection
  parent: System.Runtime.Caching.Configuration
  isExternal: false
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup.CachingSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
