### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationActivationAttribute
  id: ApplicationActivationAttribute
  children:
  - System.EnterpriseServices.ApplicationActivationAttribute.#ctor(System.EnterpriseServices.ActivationOption)
  - System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
  - System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
  - System.EnterpriseServices.ApplicationActivationAttribute.Value
  langs:
  - csharp
  name: ApplicationActivationAttribute
  nameWithType: ApplicationActivationAttribute
  fullName: System.EnterpriseServices.ApplicationActivationAttribute
  type: Class
  summary: "어셈블리의 구성 요소 작성자의 프로세스에서 또는 시스템 프로세스의 실행 여부를 지정 합니다."
  remarks: ''
  example:
  - "The following code example demonstrates the use of `ApplicationActivationAttribute` to mark a <xref:System.EnterpriseServices.ServicedComponent>.  \n  \n [!code-cpp[EnterpriseServices_Basic#1](~/add/codesnippet/cpp/t-system.enterpriseservi_13_1.cpp)]\n [!code-cs[EnterpriseServices_Basic#1](~/add/codesnippet/csharp/t-system.enterpriseservi_13_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationActivationAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationActivationAttribute.#ctor(System.EnterpriseServices.ActivationOption)
  id: '#ctor(System.EnterpriseServices.ActivationOption)'
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  langs:
  - csharp
  name: ApplicationActivationAttribute(ActivationOption)
  nameWithType: ApplicationActivationAttribute.ApplicationActivationAttribute(ActivationOption)
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.ApplicationActivationAttribute(ActivationOption)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.EnterpriseServices.ApplicationActivationAttribute&quot;> </xref> 클래스를 지정 된 설정 <xref href=&quot;System.EnterpriseServices.ActivationOption&quot;> </xref> 값입니다."
  syntax:
    content: public ApplicationActivationAttribute (System.EnterpriseServices.ActivationOption opt);
    parameters:
    - id: opt
      type: System.EnterpriseServices.ActivationOption
      description: "중 하나는 <xref href=&quot;System.EnterpriseServices.ActivationOption&quot;> </xref> 값입니다."
  overload: System.EnterpriseServices.ApplicationActivationAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
  id: SoapMailbox
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  langs:
  - csharp
  name: SoapMailbox
  nameWithType: ApplicationActivationAttribute.SoapMailbox
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "이 속성은 현재 버전에서 지원 되지 않습니다."
  syntax:
    content: public string SoapMailbox { get; set; }
    return:
      type: System.String
      description: "이 속성은 현재 버전에서 지원 되지 않습니다."
  overload: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
  id: SoapVRoot
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  langs:
  - csharp
  name: SoapVRoot
  nameWithType: ApplicationActivationAttribute.SoapVRoot
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "COM + 응용 프로그램에 대 한 웹에서 가상 루트를 나타내는 값을 가져오거나 설정 합니다."
  remarks: "을 사용 하는 경우를 설정 또는 응용 프로그램에 대 한 SOAP를 종료 하는 데 필요한 모든 작업에 발생 합니다. 컴퓨터에서 실행 되는 응용 프로그램에 대해이 속성을 설정 하는 경우는 [!INCLUDE[winsdklong](~/add/includes/winsdklong-md.md)] 설치 되지 않은 오류가 발생 합니다."
  syntax:
    content: public string SoapVRoot { get; set; }
    return:
      type: System.String
      description: "COM + 응용 프로그램에 대 한 웹에서 가상 루트입니다."
  overload: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationActivationAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationActivationAttribute.Value
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "지정 된 가져옵니다 <xref href=&quot;System.EnterpriseServices.ActivationOption&quot;> </xref> 값입니다."
  syntax:
    content: public System.EnterpriseServices.ActivationOption Value { get; }
    return:
      type: System.EnterpriseServices.ActivationOption
      description: "One of the <xref href=&quot;System.EnterpriseServices.ActivationOption&quot;></xref> values, either <xref uid=&quot;langword_csharp_Library&quot; name=&quot;Library&quot; href=&quot;&quot;></xref> or <xref uid=&quot;langword_csharp_Server&quot; name=&quot;Server&quot; href=&quot;&quot;></xref>."
  overload: System.EnterpriseServices.ApplicationActivationAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationActivationAttribute.#ctor(System.EnterpriseServices.ActivationOption)
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: ApplicationActivationAttribute(ActivationOption)
  nameWithType: ApplicationActivationAttribute.ApplicationActivationAttribute(ActivationOption)
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.ApplicationActivationAttribute(ActivationOption)
- uid: System.EnterpriseServices.ActivationOption
  parent: System.EnterpriseServices
  isExternal: false
  name: ActivationOption
  nameWithType: ActivationOption
  fullName: System.EnterpriseServices.ActivationOption
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: SoapMailbox
  nameWithType: ApplicationActivationAttribute.SoapMailbox
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: SoapVRoot
  nameWithType: ApplicationActivationAttribute.SoapVRoot
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot
- uid: System.EnterpriseServices.ApplicationActivationAttribute.Value
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationActivationAttribute.Value
  fullName: System.EnterpriseServices.ApplicationActivationAttribute.Value
- uid: System.EnterpriseServices.ApplicationActivationAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: ApplicationActivationAttribute
  nameWithType: ApplicationActivationAttribute.ApplicationActivationAttribute
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapMailbox*
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: SoapMailbox
  nameWithType: ApplicationActivationAttribute.SoapMailbox
- uid: System.EnterpriseServices.ApplicationActivationAttribute.SoapVRoot*
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: SoapVRoot
  nameWithType: ApplicationActivationAttribute.SoapVRoot
- uid: System.EnterpriseServices.ApplicationActivationAttribute.Value*
  parent: System.EnterpriseServices.ApplicationActivationAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationActivationAttribute.Value
