### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  children:
  - System.Net.Configuration.UnicodeDecodingConformance.Auto
  - System.Net.Configuration.UnicodeDecodingConformance.Compat
  - System.Net.Configuration.UnicodeDecodingConformance.Loose
  - System.Net.Configuration.UnicodeDecodingConformance.Strict
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
  type: Enum
  summary: "유니코드 문자에서 해석 하는 방법을 제어는 <xref:System.Net.WebUtility.HtmlDecode*>메서드.</xref:System.Net.WebUtility.HtmlDecode*>"
  remarks: "유니코드 문자는 되어야 하는 방법에 대 한 자세한 내용은 참조에 html에서 인코딩할 [태그와 CSS의 이스케이프 문자를 사용 하 여](http://go.microsoft.com/fwlink/?LinkId=256607)합니다."
  syntax:
    content: public enum UnicodeDecodingConformance
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  id: Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "자동 동작을 사용 합니다. 디코딩 동작은 현재 응용 프로그램의 대상 프레임 워크에 의해 결정 됩니다. 에 대 한 [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)] 이상에서 엄격한은 유니코드 인코딩 디코딩."
  syntax:
    content: Auto
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  id: Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "호환 되는 동작을 사용 합니다. 디코딩될 하기 전에 들어오는 데이터의 유효성 확인 하지는 지정 합니다. 예를 들어 입력된 문자열로 &quot;&amp;amp; #xD84C&quot; 쌍을 이루지 않는 서로게이트는 U + D84C로 디코딩할 것입니다. 또한 디코더 인식 하지 못하는 SMP의 코드 포인트를 하므로 HTML로 인코딩된 서로게이트로 표시 하는 이러한 경우가 아니면 inputstring &quot;&amp;#144308;&quot; 출력 문자열 초래 &quot;&amp;#144308;&quot;입니다."
  syntax:
    content: Compat
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  id: Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "느슨한 동작을 사용 합니다. 유효성 검사는 디코더 코드 포인트 이해 한다는 점에서 Compat 유사 합니다. 입력된 문자열 &quot;&amp;#144308;&quot; 올바르게 문자 U +&233;B4 대로 복원 합니다. 이 스위치는 디코더 인코딩된 문자열을 생성 하는 공급자가 사용 하는 형식을 알지 못할 때 최대 상호 운용성을 제공 하기 위한 것입니다."
  syntax:
    content: Loose
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  id: Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "엄격한 동작을 사용 합니다. 디코딩될 하기 전에 들어오는 인코딩된 데이터 유효성에 대 한 선택 되어 있는지를 지정 합니다. 예를 들어 입력된 문자열로 &quot;&amp;#144308;&quot;가 U +&233;B4, 하지만 입력된 문자열의 디코딩 &quot;&amp;#xD84C;&amp; #xDFB4; &quot;올바로 디코드 하지 못합니다. 문자열에서 디코딩된 이미 데이터 유효성 검사 하지 않습니다. 예를 들어 입력된 문자열로 &quot;\\ud800&quot;를 쌍으로 연결 된 이더라도 이미 디코딩된 서로게이트 디코딩, 중 무시 하도록 &quot;\\ud800&quot;의 출력 문자열 발생 합니다."
  syntax:
    content: Strict
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
