### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WsdlImporterElement
  id: WsdlImporterElement
  children:
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  - System.ServiceModel.Configuration.WsdlImporterElement.Properties
  - System.ServiceModel.Configuration.WsdlImporterElement.Type
  langs:
  - csharp
  name: WsdlImporterElement
  nameWithType: WsdlImporterElement
  fullName: System.ServiceModel.Configuration.WsdlImporterElement
  type: Class
  summary: "Ws-policy 첨부 파일과 함께 WSDL 웹 서비스 설명 언어 () 1.1 메타 데이터의 가져오기를 지정 하는 구성 요소를 나타냅니다."
  remarks: "A <xref:System.ServiceModel.Description.WsdlImporter>메타 데이터를 가져올 수 있을 뿐만 아니라 해당 정보를 계약 및 끝점 정보를 나타내는 다양 한 클래스로 변환 하는 데 사용 됩니다.</xref:System.ServiceModel.Description.WsdlImporter>       가져오기 오류를 표시 하며, 가져오기 및 변환 프로세스와 관련 된 형식 정보를 수락 하는 속성 및 계약과 끝점 정보에 선택적으로 가져올 수 있습니다. 또한 바인딩 정보와 정책 문서, WSDL 문서, WSDL 확장명 및 XML 스키마 문서에 대 한 액세스를 제공 하는 속성의 가져오기도 지원 합니다."
  syntax:
    content: 'public sealed class WsdlImporterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement()
  nameWithType: WsdlImporterElement.WsdlImporterElement()
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public WsdlImporterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement(String)
  nameWithType: WsdlImporterElement.WsdlImporterElement(String)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> 지정 된 형식의 클래스입니다."
  syntax:
    content: public WsdlImporterElement (string type);
    parameters:
    - id: type
      type: System.String
      description: "지정 된 형식입니다."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement(Type)
  nameWithType: WsdlImporterElement.WsdlImporterElement(Type)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(Type)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> 지정 된 형식의 클래스입니다."
  syntax:
    content: public WsdlImporterElement (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "지정 된 형식입니다."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "이 구성 요소의 형식을 가져오거나 설정 합니다."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "이 구성 요소의 형식입니다."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement()
  nameWithType: WsdlImporterElement.WsdlImporterElement()
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement()
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement(String)
  nameWithType: WsdlImporterElement.WsdlImporterElement(String)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement(Type)
  nameWithType: WsdlImporterElement.WsdlImporterElement(Type)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Type
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement
  nameWithType: WsdlImporterElement.WsdlImporterElement
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Properties
  nameWithType: WsdlImporterElement.Properties
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Type
  nameWithType: WsdlImporterElement.Type
