### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  id: ActivityWithResultValueSerializer
  children:
  - System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor
  - System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: ActivityWithResultValueSerializer
  nameWithType: ActivityWithResultValueSerializer
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  type: Class
  summary: "활동의 결과 직렬 전송을 위해 사용할 수 있는 문자열로 올바르게 변환 되어 있는지 확인 합니다."
  syntax:
    content: 'public sealed class ActivityWithResultValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor
  id: '#ctor'
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  langs:
  - csharp
  name: ActivityWithResultValueSerializer()
  nameWithType: ActivityWithResultValueSerializer.ActivityWithResultValueSerializer()
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ActivityWithResultValueSerializer()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.Activities.XamlIntegration.ActivityWithResultValueSerializer&quot;> </xref> 클래스입니다."
  syntax:
    content: public ActivityWithResultValueSerializer ();
    parameters: []
  overload: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ActivityWithResultValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "입력 개체가 있는지 여부를 나타내는 값을 반환 합니다.는 <xref href=&quot;System.Activities.XamlIntegration.IValueSerializableExpression&quot;> </xref> 문자열로 serialize 할 수 있습니다."
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "<xref href=&quot;System.Activities.XamlIntegration.IValueSerializableExpression&quot;> </xref> 직렬 전송을 위해 문자열로 변환 하는 기능에 대 한 확인 된 개체입니다."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "serialization에 대 한 컨텍스트를 정의 <xref href=&quot;System.Activities.XamlIntegration.IValueSerializableExpression&quot;> </xref>합니다."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>경우 식은 serialize 할 수 있습니다. 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ActivityWithResultValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "문자열에 지정된 된 개체를 serialize합니다."
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "직렬 전송을 위해 문자열로 변환 되는 개체입니다."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "문자열로 변환 되는 개체의 serialization에 대 한 컨텍스트를 정의 합니다."
    return:
      type: System.String
      description: "직렬화 된 식의 문자열 버전입니다."
  overload: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: ActivityWithResultValueSerializer()
  nameWithType: ActivityWithResultValueSerializer.ActivityWithResultValueSerializer()
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ActivityWithResultValueSerializer()
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ActivityWithResultValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ActivityWithResultValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.#ctor*
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: ActivityWithResultValueSerializer
  nameWithType: ActivityWithResultValueSerializer.ActivityWithResultValueSerializer
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.CanConvertToString*
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: ActivityWithResultValueSerializer.CanConvertToString
- uid: System.Activities.XamlIntegration.ActivityWithResultValueSerializer.ConvertToString*
  parent: System.Activities.XamlIntegration.ActivityWithResultValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: ActivityWithResultValueSerializer.ConvertToString
