### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  id: CancelRequestedQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ChildActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.Properties
  langs:
  - csharp
  name: CancelRequestedQueryElement
  nameWithType: CancelRequestedQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  type: Class
  summary: "나타내는 구성 요소는 <xref href=&quot;System.Activities.Tracking.CancelRequestedQuery&quot;> </xref>합니다."
  syntax:
    content: 'public class CancelRequestedQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  langs:
  - csharp
  name: CancelRequestedQueryElement()
  nameWithType: CancelRequestedQueryElement.CancelRequestedQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.CancelRequestedQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement&quot;> </xref>합니다."
  syntax:
    content: public CancelRequestedQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ActivityName
  id: ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  langs:
  - csharp
  name: ActivityName
  nameWithType: CancelRequestedQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "구독할 활동의 이름을 가져오거나 설정 합니다.는 <xref href=&quot;System.Activities.Tracking.CancelRequestedRecord&quot;> </xref> 에서 지정된 된 활동 취소 요청을 발급 합니다."
  remarks: "기본값은 &quot;*&quot; (모두)입니다."
  syntax:
    content: public string ActivityName { get; set; }
    return:
      type: System.String
      description: "활동의 이름에 대 한 구독 <xref href=&quot;System.Activities.Tracking.CancelRequestedRecord&quot;> </xref> 에 있습니다."
  overload: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ActivityName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ChildActivityName
  id: ChildActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  langs:
  - csharp
  name: ChildActivityName
  nameWithType: CancelRequestedQueryElement.ChildActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ChildActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "구독에 대 한 자식 활동의 이름을 가져오거나 설정 합니다.는 <xref href=&quot;System.Activities.Tracking.CancelRequestedRecord&quot;> </xref> 취소할 활동의 이름입니다."
  remarks: "기본값은 &quot;*&quot; (모두)입니다."
  syntax:
    content: public string ChildActivityName { get; set; }
    return:
      type: System.String
      description: "구독할 자식 활동의 이름 <xref href=&quot;System.Activities.Tracking.CancelRequestedRecord&quot;> </xref>합니다."
  overload: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ChildActivityName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: CancelRequestedQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "새 <xref href=&quot;System.Activities.Tracking.CancelRequestedQuery&quot;> </xref>합니다."
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: "A <xref href=&quot;System.Activities.Tracking.CancelRequestedQuery&quot;> </xref> 인스턴스."
  overload: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.NewTrackingQuery*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: CancelRequestedQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 이 요소와 연결 된 속성이 들어 있는입니다."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "속성의 컬렉션입니다."
  overload: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: CancelRequestedQueryElement()
  nameWithType: CancelRequestedQueryElement.CancelRequestedQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.CancelRequestedQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: CancelRequestedQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ActivityName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ChildActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: ChildActivityName
  nameWithType: CancelRequestedQueryElement.ChildActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ChildActivityName
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: CancelRequestedQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: Properties
  nameWithType: CancelRequestedQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: CancelRequestedQueryElement
  nameWithType: CancelRequestedQueryElement.CancelRequestedQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ActivityName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: CancelRequestedQueryElement.ActivityName
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.ChildActivityName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: ChildActivityName
  nameWithType: CancelRequestedQueryElement.ChildActivityName
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: CancelRequestedQueryElement.NewTrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  isExternal: false
  name: Properties
  nameWithType: CancelRequestedQueryElement.Properties
