### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ModuleElement
  id: ModuleElement
  children:
  - System.Net.Configuration.ModuleElement.#ctor
  - System.Net.Configuration.ModuleElement.Properties
  - System.Net.Configuration.ModuleElement.Type
  langs:
  - csharp
  name: ModuleElement
  nameWithType: ModuleElement
  fullName: System.Net.Configuration.ModuleElement
  type: Class
  summary: "사용자 지정에 대 한 형식 정보를 나타냅니다 <xref:System.Net.IWebProxy>모듈.</xref:System.Net.IWebProxy> 이 클래스는 상속 될 수 없습니다."
  remarks: "This class corresponds to the `type` attribute of the [\\&lt;module\\&gt; Element (Network Settings)](../Topic/%3Cmodule%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify a Web proxy that handles requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.ModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: ModuleElement()
  nameWithType: ModuleElement.ModuleElement()
  fullName: System.Net.Configuration.ModuleElement.ModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Net.Configuration.ModuleElement&quot;> </xref> 클래스입니다."
  remarks: "추가 하는이 생성자는 <xref:System.Configuration.ConfigurationProperty>개체에 대 한는 <xref:System.Net.Configuration.ModuleElement.Type%2A>속성을는 <xref:System.Configuration.ConfigurationElement.Properties%2A>컬렉션.</xref:System.Configuration.ConfigurationElement.Properties%2A> </xref:System.Net.Configuration.ModuleElement.Type%2A> </xref:System.Configuration.ConfigurationProperty>"
  syntax:
    content: public ModuleElement ();
    parameters: []
  overload: System.Net.Configuration.ModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: ModuleElement.Properties
  fullName: System.Net.Configuration.ModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.ModuleElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ModuleElement.Type
  id: Type
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: ModuleElement.Type
  fullName: System.Net.Configuration.ModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "현재 인스턴스에 대 한 형식 및 어셈블리 정보를 가져오거나 설정 합니다."
  remarks: "이 속성에는 다음 쉼표 (,)와 어셈블리 정보 정규화 된 형식 이름을 포함 합니다. 어셈블리 정보의 요소는 쉼표로 구분 하 여, 예를 들어 `Corp.Net.CustomWebProxy, CorpLibrary, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=&quot;00000000000000000&quot;`합니다."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "구현 하는 형식을 식별 하는 문자열은 <xref:System.Net.IWebProxy>인터페이스 또는 <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> 값이 지정 하는 경우.</xref:System.Net.IWebProxy>"
  overload: System.Net.Configuration.ModuleElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ModuleElement.#ctor
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: ModuleElement()
  nameWithType: ModuleElement.ModuleElement()
  fullName: System.Net.Configuration.ModuleElement.ModuleElement()
- uid: System.Net.Configuration.ModuleElement.Properties
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Properties
  nameWithType: ModuleElement.Properties
  fullName: System.Net.Configuration.ModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ModuleElement.Type
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Type
  nameWithType: ModuleElement.Type
  fullName: System.Net.Configuration.ModuleElement.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.ModuleElement.#ctor*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: ModuleElement
  nameWithType: ModuleElement.ModuleElement
- uid: System.Net.Configuration.ModuleElement.Properties*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Properties
  nameWithType: ModuleElement.Properties
- uid: System.Net.Configuration.ModuleElement.Type*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Type
  nameWithType: ModuleElement.Type
