### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  id: WorkflowRuntimeSection
  children:
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.#ctor
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.CommonParameters
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.EnablePerformanceCounters
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Name
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Services
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.ValidateOnCreate
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity
  langs:
  - csharp
  name: WorkflowRuntimeSection
  nameWithType: WorkflowRuntimeSection
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  type: Class
  summary: "워크플로 런타임 엔진에 대 한 설정을 정의 하는 구성 파일 내에서 섹션을 나타냅니다."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]WorkflowRuntimeSection 하 여 지정 된 설정을 포함 한 `section`> WorkflowRuntimeSection 구성 파일에서 형식의 합니다. 워크플로 런타임 엔진을 초기화 하는 WorkflowRuntimeSection에 지정한 설정이 사용 됩니다. 응용 프로그램에서 호출할 수는 <xref:System.Workflow.Runtime.WorkflowRuntime.%23ctor%28System.String%29?displayProperty=fullName>구성 파일의 적절 한 이름의 섹션에서 워크플로 런타임 엔진을 초기화 하는 생성자입니다.</xref:System.Workflow.Runtime.WorkflowRuntime.%23ctor%28System.String%29?displayProperty=fullName>       응용 프로그램 구성 파일을 사용 하지 않지만 WorkflowRuntimeSection에서 워크플로 런타임 엔진을 초기화 하려면 하는 경우 응용 프로그램 및 호출에는 WorkflowRuntimeSection를 구성할 수 있습니다는 <xref:System.Workflow.Runtime.WorkflowRuntime.%23ctor%28System.Workflow.Runtime.Configuration.WorkflowRuntimeSection%29?displayProperty=fullName>생성자.</xref:System.Workflow.Runtime.WorkflowRuntime.%23ctor%28System.Workflow.Runtime.Configuration.WorkflowRuntimeSection%29?displayProperty=fullName> 예를 들어 응용 프로그램 데이터베이스에 구성 매개 변수를 저장할 수 있습니다. 또는 구성 파일 사용 되지 않는 신뢰할 수 있는 환경에서 작동할 수 있습니다."
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class WorkflowRuntimeSection : System.Configuration.ConfigurationSection
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.#ctor
  id: '#ctor'
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  langs:
  - csharp
  name: WorkflowRuntimeSection()
  nameWithType: WorkflowRuntimeSection.WorkflowRuntimeSection()
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowRuntimeSection()
  type: Constructor
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Workflow.Runtime.Configuration.WorkflowRuntimeSection&quot;> </xref> 클래스입니다."
  syntax:
    content: public WorkflowRuntimeSection ();
    parameters: []
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.CommonParameters
  id: CommonParameters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  langs:
  - csharp
  name: CommonParameters
  nameWithType: WorkflowRuntimeSection.CommonParameters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.CommonParameters
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "서비스에서 사용 하는 일반 매개 변수 컬렉션을 가져옵니다."
  remarks: "CommonParameters 포함 될 수 있습니다, 예를 들어 영 속 서비스에서 공유할 수 있는 데이터베이스 연결 문자열입니다."
  syntax:
    content: public System.Configuration.NameValueConfigurationCollection CommonParameters { get; }
    return:
      type: System.Configuration.NameValueConfigurationCollection
      description: "서비스에서 사용 하는 일반 매개 변수입니다. 기본값은 null 참조 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> Visual basic에서)."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.CommonParameters*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.EnablePerformanceCounters
  id: EnablePerformanceCounters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  langs:
  - csharp
  name: EnablePerformanceCounters
  nameWithType: WorkflowRuntimeSection.EnablePerformanceCounters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.EnablePerformanceCounters
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "성능 카운터를 사용할 수 있는지 여부를 나타내는 값을 가져오거나 설정 합니다."
  remarks: "성능 카운터는 다양 한 워크플로 관련 통계에 정보를 제공 하지만 워크플로 런타임 엔진이 시작 될 때 및 워크플로 인스턴스가 실행 되는 경우 성능 저하는 합니다. 기본값은 `true`입니다."
  syntax:
    content: public bool EnablePerformanceCounters { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>성능 카운터를 사용 하면 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.EnablePerformanceCounters*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Name
  id: Name
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  langs:
  - csharp
  name: Name
  nameWithType: WorkflowRuntimeSection.Name
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Name
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "워크플로 런타임 엔진의 이름을 가져오거나 설정 합니다."
  remarks: "이 속성은 <xref:System.Workflow.Runtime.WorkflowRuntime.Name%2A?displayProperty=fullName>.</xref:System.Workflow.Runtime.WorkflowRuntime.Name%2A?displayProperty=fullName> 설정 사용 기본값은 빈 문자열입니다."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "워크플로 런타임 엔진의 이름입니다."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Services
  id: Services
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  langs:
  - csharp
  name: Services
  nameWithType: WorkflowRuntimeSection.Services
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Services
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "초기화 될 때 워크플로 런타임 엔진에 추가 되는 서비스의 컬렉션을 가져옵니다."
  remarks: "에 지정 된 서비스는 <xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElementCollection>워크플로 런타임 엔진에 의해 초기화 되 고 서비스에 추가 하면 적절 한 <xref:System.Workflow.Runtime.WorkflowRuntime>생성자를 호출 합니다.</xref:System.Workflow.Runtime.WorkflowRuntime> </xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElementCollection> 따라서에 지정 된 서비스는 <xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElementCollection>는 생성자의 서명에 대 한 특정 규칙을 따라야 합니다.</xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElementCollection> [!INCLUDE[crdefault](~/add/includes/ajax-current-ext-md.md)]<xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement>.</xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement>"
  syntax:
    content: public System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElementCollection Services { get; }
    return:
      type: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElementCollection
      description: "서비스는 워크플로 런타임 엔진에 추가할 수입니다."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Services*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.ValidateOnCreate
  id: ValidateOnCreate
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  langs:
  - csharp
  name: ValidateOnCreate
  nameWithType: WorkflowRuntimeSection.ValidateOnCreate
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.ValidateOnCreate
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "워크플로 인스턴스를 만드는 과정에서 유효성 검사가 수행 여부를 나타내는 값을 가져오거나 설정 합니다."
  remarks: "이 속성이로 설정 된 경우 `true`, 워크플로 유효성 검사 될 때마다 실행 되 <xref:System.Workflow.Runtime.WorkflowRuntime.CreateWorkflow%2A>호출 됩니다.</xref:System.Workflow.Runtime.WorkflowRuntime.CreateWorkflow%2A> 유효성 검사 오류가 발견 되 면 한 <xref:System.Workflow.ComponentModel.Compiler.WorkflowValidationFailedException>throw 됩니다.</xref:System.Workflow.ComponentModel.Compiler.WorkflowValidationFailedException>       이 속성이로 설정 된 경우 `false`, <xref:System.Workflow.Runtime.WorkflowRuntime.CreateWorkflow%2A>워크플로 인스턴스를 만들고 유효성 검사를 건너뜁니다.</xref:System.Workflow.Runtime.WorkflowRuntime.CreateWorkflow%2A> 이 경우 호스트 응용 프로그램에서 워크플로의 구성이 올바른지 또는 런타임 오류가 발생 했지만 보장 해야 합니다.       이 속성에 대 한 기본값은 `true`합니다."
  syntax:
    content: public bool ValidateOnCreate { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>유효성 검사 생성에서 발생 한 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.ValidateOnCreate*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity
  id: WorkflowDefinitionCacheCapacity
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  langs:
  - csharp
  name: WorkflowDefinitionCacheCapacity
  nameWithType: WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "런타임에서 캐시할 수 있는 워크플로 정의의 수를 가져옵니다."
  syntax:
    content: public int WorkflowDefinitionCacheCapacity { get; set; }
    return:
      type: System.Int32
      description: "워크플로의 수입니다."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.#ctor
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: WorkflowRuntimeSection()
  nameWithType: WorkflowRuntimeSection.WorkflowRuntimeSection()
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowRuntimeSection()
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.CommonParameters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: CommonParameters
  nameWithType: WorkflowRuntimeSection.CommonParameters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.CommonParameters
- uid: System.Configuration.NameValueConfigurationCollection
  parent: System.Configuration
  isExternal: false
  name: NameValueConfigurationCollection
  nameWithType: NameValueConfigurationCollection
  fullName: System.Configuration.NameValueConfigurationCollection
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.EnablePerformanceCounters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: EnablePerformanceCounters
  nameWithType: WorkflowRuntimeSection.EnablePerformanceCounters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.EnablePerformanceCounters
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Name
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: Name
  nameWithType: WorkflowRuntimeSection.Name
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Services
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: Services
  nameWithType: WorkflowRuntimeSection.Services
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Services
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElementCollection
  parent: System.Workflow.Runtime.Configuration
  isExternal: false
  name: WorkflowRuntimeServiceElementCollection
  nameWithType: WorkflowRuntimeServiceElementCollection
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElementCollection
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.ValidateOnCreate
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: ValidateOnCreate
  nameWithType: WorkflowRuntimeSection.ValidateOnCreate
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.ValidateOnCreate
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: WorkflowDefinitionCacheCapacity
  nameWithType: WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.#ctor*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: WorkflowRuntimeSection
  nameWithType: WorkflowRuntimeSection.WorkflowRuntimeSection
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.CommonParameters*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: CommonParameters
  nameWithType: WorkflowRuntimeSection.CommonParameters
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.EnablePerformanceCounters*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: EnablePerformanceCounters
  nameWithType: WorkflowRuntimeSection.EnablePerformanceCounters
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Name*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: Name
  nameWithType: WorkflowRuntimeSection.Name
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.Services*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: Services
  nameWithType: WorkflowRuntimeSection.Services
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.ValidateOnCreate*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: ValidateOnCreate
  nameWithType: WorkflowRuntimeSection.ValidateOnCreate
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeSection
  isExternal: false
  name: WorkflowDefinitionCacheCapacity
  nameWithType: WorkflowRuntimeSection.WorkflowDefinitionCacheCapacity
