### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BehaviorsSection
  id: BehaviorsSection
  children:
  - System.ServiceModel.Configuration.BehaviorsSection.#ctor
  - System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
  - System.ServiceModel.Configuration.BehaviorsSection.Properties
  - System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
  langs:
  - csharp
  name: BehaviorsSection
  nameWithType: BehaviorsSection
  fullName: System.ServiceModel.Configuration.BehaviorsSection
  type: Class
  summary: "자식 항목을 포함 하는 구성 섹션을 나타냅니다 <xref uid=&quot;langword_csharp_behavior&quot; name=&quot;behavior&quot; href=&quot;&quot;> </xref> 고유한으로 식별 되는 요소 <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>합니다."
  remarks: "A `behavior` 요소는 서비스의 동작에 대 한 설정 컬렉션을 포함 합니다. 각 동작은 기준으로 인덱싱되어 있으면 해당 `name`합니다. 서비스에이 이름을 지정 하 여 연결 하 여 동작을 사용 합니다."
  syntax:
    content: 'public class BehaviorsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BehaviorsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BehaviorsSection
  langs:
  - csharp
  name: BehaviorsSection()
  nameWithType: BehaviorsSection.BehaviorsSection()
  fullName: System.ServiceModel.Configuration.BehaviorsSection.BehaviorsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.BehaviorsSection&quot;> </xref> 클래스입니다."
  syntax:
    content: public BehaviorsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.BehaviorsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
  id: EndpointBehaviors
  parent: System.ServiceModel.Configuration.BehaviorsSection
  langs:
  - csharp
  name: EndpointBehaviors
  nameWithType: BehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "모든 자식 항목은 고유한 것으로 식별 하는 끝점 동작 요소를 가져옵니다 <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>합니다."
  syntax:
    content: public System.ServiceModel.Configuration.EndpointBehaviorElementCollection EndpointBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.EndpointBehaviorElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Configuration.EndpointBehaviorElementCollection&quot;> </xref> 고유한으로 식별 되는 끝점 동작 요소를 포함 하는 <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BehaviorsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BehaviorsSection
  langs:
  - csharp
  name: Properties
  nameWithType: BehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.BehaviorsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 의 컬렉션을 포함 하는 인스턴스 <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> 특성 일 수 있는 개체 또는 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 이 구성 요소 개체입니다."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 의 컬렉션을 포함 하는 인스턴스 <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> 특성 일 수 있는 개체 또는 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 이 구성 요소 개체입니다."
  overload: System.ServiceModel.Configuration.BehaviorsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
  id: ServiceBehaviors
  parent: System.ServiceModel.Configuration.BehaviorsSection
  langs:
  - csharp
  name: ServiceBehaviors
  nameWithType: BehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "모든 자식 항목은 고유한으로 식별 되는 서비스 동작 요소를 가져옵니다 <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>합니다."
  syntax:
    content: public System.ServiceModel.Configuration.ServiceBehaviorElementCollection ServiceBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.ServiceBehaviorElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Configuration.ServiceBehaviorElementCollection&quot;> </xref> 고유한로 식별 되는 서비스 동작 요소를 포함 하는 <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.BehaviorsSection.#ctor
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: BehaviorsSection()
  nameWithType: BehaviorsSection.BehaviorsSection()
  fullName: System.ServiceModel.Configuration.BehaviorsSection.BehaviorsSection()
- uid: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: BehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.EndpointBehaviorElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: EndpointBehaviorElementCollection
  nameWithType: EndpointBehaviorElementCollection
  fullName: System.ServiceModel.Configuration.EndpointBehaviorElementCollection
- uid: System.ServiceModel.Configuration.BehaviorsSection.Properties
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: BehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.BehaviorsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: BehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
- uid: System.ServiceModel.Configuration.ServiceBehaviorElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceBehaviorElementCollection
  nameWithType: ServiceBehaviorElementCollection
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElementCollection
- uid: System.ServiceModel.Configuration.BehaviorsSection.#ctor*
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: BehaviorsSection
  nameWithType: BehaviorsSection.BehaviorsSection
- uid: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors*
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: BehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.BehaviorsSection.Properties*
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: BehaviorsSection.Properties
- uid: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors*
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: BehaviorsSection.ServiceBehaviors
