### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  id: X509RecipientCertificateClientElement
  children:
  - System.ServiceModel.Configuration.X509RecipientCertificateClientElement.#ctor
  - System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Authentication
  - System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Copy(System.ServiceModel.Configuration.X509RecipientCertificateClientElement)
  - System.ServiceModel.Configuration.X509RecipientCertificateClientElement.DefaultCertificate
  - System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Properties
  - System.ServiceModel.Configuration.X509RecipientCertificateClientElement.ScopedCertificates
  - System.ServiceModel.Configuration.X509RecipientCertificateClientElement.SslCertificateAuthentication
  langs:
  - csharp
  name: X509RecipientCertificateClientElement
  nameWithType: X509RecipientCertificateClientElement
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  type: Class
  summary: "보낸 사람에 의해 사용할 X.509 인증서에 대 한 받는 사람의 요구 사항을 지정 하는 구성 요소를 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: 'public sealed class X509RecipientCertificateClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  langs:
  - csharp
  name: X509RecipientCertificateClientElement()
  nameWithType: X509RecipientCertificateClientElement.X509RecipientCertificateClientElement()
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.X509RecipientCertificateClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.X509RecipientCertificateClientElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public X509RecipientCertificateClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Authentication
  id: Authentication
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  langs:
  - csharp
  name: Authentication
  nameWithType: X509RecipientCertificateClientElement.Authentication
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Authentication
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "인증에 사용 된 인증서를 가져옵니다."
  syntax:
    content: public System.ServiceModel.Configuration.X509ServiceCertificateAuthenticationElement Authentication { get; }
    return:
      type: System.ServiceModel.Configuration.X509ServiceCertificateAuthenticationElement
      description: "인증에 사용 된 인증서입니다."
  overload: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Authentication*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Copy(System.ServiceModel.Configuration.X509RecipientCertificateClientElement)
  id: Copy(System.ServiceModel.Configuration.X509RecipientCertificateClientElement)
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  langs:
  - csharp
  name: Copy(X509RecipientCertificateClientElement)
  nameWithType: X509RecipientCertificateClientElement.Copy(X509RecipientCertificateClientElement)
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Copy(X509RecipientCertificateClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정 된 구성 요소의 내용을이 구성 요소에 복사합니다."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509RecipientCertificateClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
      description: "복사할 구성 요소입니다."
  overload: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "구성 파일에는 읽기 전용입니다."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.DefaultCertificate
  id: DefaultCertificate
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  langs:
  - csharp
  name: DefaultCertificate
  nameWithType: X509RecipientCertificateClientElement.DefaultCertificate
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.DefaultCertificate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "클라이언트에 응답할 때 서비스를 나타내는 데 사용할 기본 인증서를 가져옵니다."
  syntax:
    content: public System.ServiceModel.Configuration.X509DefaultServiceCertificateElement DefaultCertificate { get; }
    return:
      type: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.X509Certificate2&quot;> </xref> 클라이언트에 응답할 때 서비스를 나타내기 위해 사용할 수 있습니다."
  overload: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.DefaultCertificate*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509RecipientCertificateClientElement.Properties
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.ScopedCertificates
  id: ScopedCertificates
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  langs:
  - csharp
  name: ScopedCertificates
  nameWithType: X509RecipientCertificateClientElement.ScopedCertificates
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.ScopedCertificates
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "클라이언트에 응답할 때 서비스를 나타내는 데 사용할 범위 지정 된 인증서를 가져옵니다."
  syntax:
    content: public System.ServiceModel.Configuration.X509ScopedServiceCertificateElementCollection ScopedCertificates { get; }
    return:
      type: System.ServiceModel.Configuration.X509ScopedServiceCertificateElementCollection
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.X509Certificate2&quot;> </xref> 클라이언트에 응답할 때 서비스를 나타내는 데 사용할 수 있습니다."
  overload: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.ScopedCertificates*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.SslCertificateAuthentication
  id: SslCertificateAuthentication
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  langs:
  - csharp
  name: SslCertificateAuthentication
  nameWithType: X509RecipientCertificateClientElement.SslCertificateAuthentication
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.SslCertificateAuthentication
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "(SECURE Sockets Layer) 인증서에 대 한 인증 설정을 가져옵니다."
  syntax:
    content: public System.ServiceModel.Configuration.X509ServiceCertificateAuthenticationElement SslCertificateAuthentication { get; }
    return:
      type: System.ServiceModel.Configuration.X509ServiceCertificateAuthenticationElement
      description: "SSL 인증서에 대 한 인증 설정입니다."
  overload: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.SslCertificateAuthentication*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.#ctor
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: X509RecipientCertificateClientElement()
  nameWithType: X509RecipientCertificateClientElement.X509RecipientCertificateClientElement()
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.X509RecipientCertificateClientElement()
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Authentication
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: Authentication
  nameWithType: X509RecipientCertificateClientElement.Authentication
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Authentication
- uid: System.ServiceModel.Configuration.X509ServiceCertificateAuthenticationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509ServiceCertificateAuthenticationElement
  nameWithType: X509ServiceCertificateAuthenticationElement
  fullName: System.ServiceModel.Configuration.X509ServiceCertificateAuthenticationElement
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Copy(System.ServiceModel.Configuration.X509RecipientCertificateClientElement)
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: Copy(X509RecipientCertificateClientElement)
  nameWithType: X509RecipientCertificateClientElement.Copy(X509RecipientCertificateClientElement)
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Copy(X509RecipientCertificateClientElement)
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509RecipientCertificateClientElement
  nameWithType: X509RecipientCertificateClientElement
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.DefaultCertificate
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: DefaultCertificate
  nameWithType: X509RecipientCertificateClientElement.DefaultCertificate
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.DefaultCertificate
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509DefaultServiceCertificateElement
  nameWithType: X509DefaultServiceCertificateElement
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Properties
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: Properties
  nameWithType: X509RecipientCertificateClientElement.Properties
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.ScopedCertificates
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: ScopedCertificates
  nameWithType: X509RecipientCertificateClientElement.ScopedCertificates
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.ScopedCertificates
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509ScopedServiceCertificateElementCollection
  nameWithType: X509ScopedServiceCertificateElementCollection
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElementCollection
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.SslCertificateAuthentication
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: SslCertificateAuthentication
  nameWithType: X509RecipientCertificateClientElement.SslCertificateAuthentication
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.SslCertificateAuthentication
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.#ctor*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: X509RecipientCertificateClientElement
  nameWithType: X509RecipientCertificateClientElement.X509RecipientCertificateClientElement
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Authentication*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: Authentication
  nameWithType: X509RecipientCertificateClientElement.Authentication
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Copy*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: Copy
  nameWithType: X509RecipientCertificateClientElement.Copy
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.DefaultCertificate*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: DefaultCertificate
  nameWithType: X509RecipientCertificateClientElement.DefaultCertificate
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.Properties*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: Properties
  nameWithType: X509RecipientCertificateClientElement.Properties
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.ScopedCertificates*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: ScopedCertificates
  nameWithType: X509RecipientCertificateClientElement.ScopedCertificates
- uid: System.ServiceModel.Configuration.X509RecipientCertificateClientElement.SslCertificateAuthentication*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateClientElement
  isExternal: false
  name: SslCertificateAuthentication
  nameWithType: X509RecipientCertificateClientElement.SslCertificateAuthentication
