### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.WmiConfigurationAttribute
  id: WmiConfigurationAttribute
  children:
  - System.Management.Instrumentation.WmiConfigurationAttribute.#ctor(System.String)
  - System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
  - System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
  - System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
  - System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
  - System.Management.Instrumentation.WmiConfigurationAttribute.Scope
  - System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
  langs:
  - csharp
  name: WmiConfigurationAttribute
  nameWithType: WmiConfigurationAttribute
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute
  type: Class
  summary: "WmiConfiguration 특성 WMI.NET 공급자 확장 모델을 사용 하 여 WMI 공급자를 구현 하는 코드 어셈블리에 포함 되어 있음을 나타냅니다. 특성에 구현 된 WMI 공급자의 상위 수준 구성을 설정 하는 매개 변수입니다.       참고: WMI.NET 라이브러리 이제 간주 최종 상태 및 이후 개발, 향상 된 기능, 또는 업데이트 이러한 라이브러리에 영향을 주는 비보안 관련된 문제에 대해 사용할 수 있습니다. [MI Api](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) 새로운 개발에 사용 해야 합니다."
  remarks: "다음 표에서 공급자 구성의 어떤 부분 사용할 수 있습니다 제어와 함께이 특성에서 허용 하는 매개 변수를 나열 합니다.      | 매개 변수 | 구성 |   |---------------|----------------|   | [Scope](~/add/includes/ajax-current-ext-md.md)| 공급자 클래스를 노출 하는 네임 스페이스입니다. |   | [NamespaceSecurity](~/add/includes/ajax-current-ext-md.md)|-사용 된 네임 스페이스에 보안 (dacl 임의). |   | [HostingModel](~/add/includes/ajax-current-ext-md.md)|-공급자가 사용 될 호스팅 모델입니다. |   | [IdentifyLevel](~/add/includes/ajax-current-ext-md.md)|-공급자의 가장 모드입니다. |   | [HostingGroup](~/add/includes/ajax-current-ext-md.md)| 공급자에 속한 호스팅 그룹입니다. 이 매개 변수 프로세스 공급자에만 적용 됩니다. |   | [SecurityRestriction](~/add/includes/ajax-current-ext-md.md)| WMI 공급자에 보안 (dacl 임의). |"
  example:
  - "```  \n// Specify that this assembly contains code that implements a WMI  \n// Provider. Use the assembly:WmiConfiguration attribute to define  \n// the WMI namespace, the hosting model, and the impersonation mode  \n// of the WMI provider.  \n// The attribute below specifies that the class this provider  \n// exposes to WMI will be in the root/MortgageCalc namespace, will  \n// use the decoupled hosting model and will not allow the provider  \n// to impersonate its callers.  \n  \n[assembly: WmiConfiguration(\"root/MortgageCalc\",HostingModel = ManagementHostingModel.Decoupled, IdentifyLevel = false)]  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly)]

      public sealed class WmiConfigurationAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: WmiConfigurationAttribute(String)
  nameWithType: WmiConfigurationAttribute.WmiConfigurationAttribute(String)
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.WmiConfigurationAttribute(String)
  type: Constructor
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "새 인스턴스를 초기화는 <xref:System.Management.WmiConfigurationAttribute>WMI 공급자는 클래스를 제공 하는 WMI 네임 스페이스를 지정 하는 클래스입니다.</xref:System.Management.WmiConfigurationAttribute>"
  remarks: "WMI 공급자 네임 스페이스의 클래스를 노출 해야 합니다. 이 생성자를 사용 하려면 범위를 매개 변수로 때문입니다."
  syntax:
    content: public WmiConfigurationAttribute (string scope);
    parameters:
    - id: scope
      type: System.String
      description: "공급자는 클래스를 제공 하는 WMI 네임 스페이스입니다. 예를 들어 &quot;root\\MyProviderNamespace&quot;가 있습니다."
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
  id: HostingGroup
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: HostingGroup
  nameWithType: WmiConfigurationAttribute.HostingGroup
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "WMI 공급자에 대 한 호스팅 그룹을 가져오거나 설정 합니다."
  remarks: "호스트 그룹에만 적용 되어 있는 공급자 호스트 프로세스에 있습니다. 분리 된 공급자에는 값은 무시 됩니다.       호스팅 그룹은 동일한 호스팅 그룹 이름이 할당 된 in-process 공급자입니다. 호스팅 그룹 이름은 공급자를 논리적으로 그룹화를 정의 하는 문자열입니다. 동일한 보안 컨텍스트 내에서 실행 되는 동일한 호스팅 그룹에에서 in-process 공급자를 모두 Wmiprvse.exe 프로세스의 단일 인스턴스 내에서 호스팅됩니다. 따라서 동일한 호스팅 그룹 및 보안 컨텍스트를 공유 하는 공급자는 서비스 호스트 프로세스를 공유 합니다."
  example:
  - "In the following example, the <xref:System.Management.Instrumentation.WmiConfigurationAttribute> is used to indicate that the assembly it is contained in implements an in-process provider that runs under the NetworkService security context and is hosted in a instance of the Wmiprvse.exe process that also hosts any other in-process providers in the same hosting group that also run within the NetworkService security context.  \n  \n```  \n[assembly: WmiConfiguration(\"root\\\\NVPair\", HostingModel = ManagementHostingModel.NetworkService), HostingGroup = \"MyProviders\"]  \n```"
  syntax:
    content: public string HostingGroup { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>WMI 공급자에 대 한 호스팅 그룹을 나타내는 값입니다.</xref:System.String>"
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
  id: HostingModel
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: HostingModel
  nameWithType: WmiConfigurationAttribute.HostingModel
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "WMI 공급자에 대 한 호스팅 모델을 가져오거나 설정 합니다."
  remarks: "WMI 서비스 또는 응용 프로그램에서 WMI 공급자를 호스팅할 수 있습니다. WMI 공급자 응용 프로그램에 의해 호스팅되는 분리 된 공급자 라고 합니다. WMI 서비스에서 호스팅하는 것에 in-process 공급자 라고 합니다. 호스팅 모델 값은 호스팅 모델 및 in-process 공급자를 공급자 실행 되는 계정 (보안 컨텍스트)의 경우를 결정 합니다. 참조 <xref:System.Management.Instrumentation.ManagementHostingModel>.</xref:System.Management.Instrumentation.ManagementHostingModel> HostingModel의 가능한 값에 대 한 자세한 내용을 보려면       호스팅 모델에 대 한 자세한 내용은 참조는 [공급자 호스팅 및 보안](http://go.microsoft.com/fwlink/?LinkId=100075) msdn WMI SDK에는 항목입니다."
  example:
  - "In the following example, the <xref:System.Management.Instrumentation.WmiConfigurationAttribute> is used to indicate that the assembly it is contained in implements a provider that is exposed through the root\\NVPair namespace. Because the hosting model is not <xref:System.Management.Instrumentation.ManagementHostingModel>, it is an in-process provider. The value <xref:System.Management.Instrumentation.ManagementHostingModel> indicates that the in-process provider runs under the NetworkService security context.  \n  \n```  \n[assembly: WmiConfiguration(\"root\\\\NVPair\", HostingModel = ManagementHostingModel.NetworkService)]  \n```  \n  \n In the next example, the <xref:System.Management.Instrumentation.WmiConfigurationAttribute> is used to indicate that the assembly it is contained in implements a provider that is exposed through the root\\NVPair namespace. The value <xref:System.Management.Instrumentation.ManagementHostingModel> indicates that it is a decoupled provider.  \n  \n```  \n[assembly: WmiConfiguration(\"root\\\\NVPair\", HostingModel = ManagementHostingModel.Decoupled)]  \n```"
  syntax:
    content: public System.Management.Instrumentation.ManagementHostingModel HostingModel { get; set; }
    return:
      type: System.Management.Instrumentation.ManagementHostingModel
      description: "A <xref href=&quot;System.Management.Instrumentation.ManagementHostingModel&quot;> </xref> 호스팅 모델의 WMI 공급자를 나타내는 값입니다."
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
  id: IdentifyLevel
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: IdentifyLevel
  nameWithType: WmiConfigurationAttribute.IdentifyLevel
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "WMI 공급자가 호출자를 가장할 수 있는지 여부를 지정 하는 값을 가져오거나 설정 합니다. 값이 false 이면 공급자 가장할 수 없고 하 고 값이 true 이면 공급자를 가장할 수 있습니다."
  remarks: "자세한 내용은 온라인에서 MSDN library에서 &quot;공급자 호스팅 및 보안&quot; 항목을 참조 [http://www.msdn.com](http://www.msdn.com/)합니다."
  example:
  - "The following example demonstrates how to use the IdentifyLevel parameter to indicate that the provider can impersonate its callers.  \n  \n```  \n[assembly: WmiConfiguration(\"root/MyProv\", HostingModel = ManagementHostingModel.Decoupled, IdentifyLevel = true]  \n```"
  syntax:
    content: public bool IdentifyLevel { get; set; }
    return:
      type: System.Boolean
      description: "공급자 수 또는 호출자를 가장할 수 있는지를 나타내는 부울 값입니다. 값이 false 이면 공급자 가장할 수 없고 하 고 값이 true 이면 공급자를 가장할 수 있습니다."
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
  id: NamespaceSecurity
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: NamespaceSecurity
  nameWithType: WmiConfigurationAttribute.NamespaceSecurity
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "공급자 관리 개체를 노출 하는 네임 스페이스에서 보안 설명자를 지정 하는 보안 설명자 정의 언어 (SDDL) 문자열을 가져오거나 설정 합니다."
  remarks: "SDDL 형식에 대 한 보안 설명자를 나타내는 방법에 대 한 자세한 내용은 참조는 [보안 설명자 문자열 형식](http://go.microsoft.com/fwlink/?LinkId=100763) 온라인 MSDN library의 항목입니다."
  example:
  - "The following example demonstrates how to use the NamespaceSecurity parameter to set the security descriptor on the root/SDTest namespace in which the provider implemented in this assembly exposes WMI classes.  \n  \n```  \n[assembly: WmiConfiguration(\"root/SDTest\", HostingModel = ManagementHostingModel.Decoupled, IdentifyLevel = false, NamespaceSecurity = \"O:BAG:BAD:(A;CI;0x60003;;;WD)\")]  \n```"
  syntax:
    content: public string NamespaceSecurity { get; set; }
    return:
      type: System.String
      description: "공급자 관리 개체를 제공 하는 네임 스페이스에서 보안 설명자를 나타내는 SDDL 문자열입니다."
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.Scope
  id: Scope
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: Scope
  nameWithType: WmiConfigurationAttribute.Scope
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.Scope
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "WMI 공급자 클래스를 노출 하는 WMI 네임 스페이스를 가져오거나 설정 합니다."
  remarks: "WMI 네임 스페이스는 WMI 리포지토리 내에서 범주입니다. 일반적으로 사용 되는 root/cimv2 네임 스페이스 Common Information Model, 버전 2 컨소시엄 데스크톱 Management Task Force DMTF ()에 의해 정의 설명 하는 클래스를 보관 합니다. 경우에 해당 네임 스페이스의 공급자를 노출 해야 표준 CIM 모델을 확장 합니다. 그렇지 않으면 정확 하 게 사용자가 네임 스페이스에서 찾을 수 기대할 수 있는 WMI 클래스의 형식을 하는 적절 한 네임 스페이스를 만들어야 합니다."
  syntax:
    content: public string Scope { get; }
    return:
      type: System.String
      description: "A <xref:System.String>WMI 공급자 클래스를 노출 하는 네임 스페이스를 나타내는 값입니다.</xref:System.String>"
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.Scope*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
  id: SecurityRestriction
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: SecurityRestriction
  nameWithType: WmiConfigurationAttribute.SecurityRestriction
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "WMI 공급자에 대 한 보안 설명자를 가져오거나 설정 합니다. 자세한 내용은 MSDN online library에서 &quot;__Win32Provider&quot; 항목에 있는 SecurityDescriptor 속성 정보를 참조 하십시오. [http://www.msdn.com](http://www.msdn.com/)합니다."
  syntax:
    content: public string SecurityRestriction { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>WMI 공급자에 대 한 보안 설명자를 포함 하는 값입니다.</xref:System.String>"
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.#ctor(System.String)
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: WmiConfigurationAttribute(String)
  nameWithType: WmiConfigurationAttribute.WmiConfigurationAttribute(String)
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.WmiConfigurationAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: HostingGroup
  nameWithType: WmiConfigurationAttribute.HostingGroup
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: HostingModel
  nameWithType: WmiConfigurationAttribute.HostingModel
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
- uid: System.Management.Instrumentation.ManagementHostingModel
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementHostingModel
  nameWithType: ManagementHostingModel
  fullName: System.Management.Instrumentation.ManagementHostingModel
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: IdentifyLevel
  nameWithType: WmiConfigurationAttribute.IdentifyLevel
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: NamespaceSecurity
  nameWithType: WmiConfigurationAttribute.NamespaceSecurity
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.Scope
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: Scope
  nameWithType: WmiConfigurationAttribute.Scope
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.Scope
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: SecurityRestriction
  nameWithType: WmiConfigurationAttribute.SecurityRestriction
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.#ctor*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: WmiConfigurationAttribute
  nameWithType: WmiConfigurationAttribute.WmiConfigurationAttribute
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: HostingGroup
  nameWithType: WmiConfigurationAttribute.HostingGroup
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: HostingModel
  nameWithType: WmiConfigurationAttribute.HostingModel
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: IdentifyLevel
  nameWithType: WmiConfigurationAttribute.IdentifyLevel
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: NamespaceSecurity
  nameWithType: WmiConfigurationAttribute.NamespaceSecurity
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.Scope*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: Scope
  nameWithType: WmiConfigurationAttribute.Scope
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: SecurityRestriction
  nameWithType: WmiConfigurationAttribute.SecurityRestriction
