### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  id: CustomTrackingQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.ActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Properties
  langs:
  - csharp
  name: CustomTrackingQueryElement
  nameWithType: CustomTrackingQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  type: Class
  summary: "나타내는 구성 요소는 <xref href=&quot;System.Activities.Tracking.CustomTrackingQuery&quot;> </xref>합니다."
  syntax:
    content: 'public class CustomTrackingQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  langs:
  - csharp
  name: CustomTrackingQueryElement()
  nameWithType: CustomTrackingQueryElement.CustomTrackingQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.CustomTrackingQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public CustomTrackingQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.ActivityName
  id: ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  langs:
  - csharp
  name: ActivityName
  nameWithType: CustomTrackingQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.ActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "필터링 할 활동의 이름을 가져오거나 설정 합니다. <xref href=&quot;System.Activities.Tracking.CustomTrackingRecord&quot;> </xref> 인스턴스를 합니다. 기본값은 &quot;*&quot; (모두)입니다."
  syntax:
    content: public string ActivityName { get; set; }
    return:
      type: System.String
      description: "필터링 할 활동의 이름입니다."
  overload: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.ActivityName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  langs:
  - csharp
  name: Name
  nameWithType: CustomTrackingQueryElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "추적 레코드에 대 한 쿼리 하려는 활동의 이름을 가져오거나 설정 합니다."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "활동 이름입니다."
  overload: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: CustomTrackingQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "새 <xref href=&quot;System.Activities.Tracking.CustomTrackingQuery&quot;> </xref>합니다."
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: "새 <xref href=&quot;System.Activities.Tracking.CustomTrackingQuery&quot;> </xref> 인스턴스."
  overload: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.NewTrackingQuery*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: CustomTrackingQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 이 요소와 연결 된 속성이 들어 있는입니다."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "속성 컬렉션입니다."
  overload: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: CustomTrackingQueryElement()
  nameWithType: CustomTrackingQueryElement.CustomTrackingQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.CustomTrackingQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: CustomTrackingQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.ActivityName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: Name
  nameWithType: CustomTrackingQueryElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: CustomTrackingQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: Properties
  nameWithType: CustomTrackingQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: CustomTrackingQueryElement
  nameWithType: CustomTrackingQueryElement.CustomTrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.ActivityName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: CustomTrackingQueryElement.ActivityName
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: Name
  nameWithType: CustomTrackingQueryElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: CustomTrackingQueryElement.NewTrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElement
  isExternal: false
  name: Properties
  nameWithType: CustomTrackingQueryElement.Properties
