### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.VirtualDirectoryMapping
  id: VirtualDirectoryMapping
  children:
  - System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  - System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  - System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  - System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  - System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  - System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  langs:
  - csharp
  name: VirtualDirectoryMapping
  nameWithType: VirtualDirectoryMapping
  fullName: System.Web.Configuration.VirtualDirectoryMapping
  type: Class
  summary: "웹 응용 프로그램에 대 한 사용자 지정 가상 디렉터리 계층 구조를 지정합니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: public sealed class VirtualDirectoryMapping
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  id: '#ctor(System.String,System.Boolean)'
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectoryMapping(String,Boolean)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> 클래스에 따라 매개 변수를 제공 합니다."
  syntax:
    content: public VirtualDirectoryMapping (string physicalDirectory, bool isAppRoot);
    parameters:
    - id: physicalDirectory
      type: System.String
      description: "실제 디렉터리를 절대 경로 지정 하는 문자열 값입니다."
    - id: isAppRoot
      type: System.Boolean
      description: "가상 디렉터리는 웹 응용 프로그램의 응용 프로그램 루트 인지 여부를 나타내는 부울 값입니다."
  overload: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  id: '#ctor(System.String,System.Boolean,System.String)'
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectoryMapping(String,Boolean,String)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> 클래스에 따라 매개 변수를 제공 합니다."
  syntax:
    content: public VirtualDirectoryMapping (string physicalDirectory, bool isAppRoot, string configFileBaseName);
    parameters:
    - id: physicalDirectory
      type: System.String
      description: "실제 디렉터리를 절대 경로 지정 하는 문자열 값입니다."
    - id: isAppRoot
      type: System.Boolean
      description: "가상 디렉터리는 웹 응용 프로그램의 응용 프로그램 루트 인지 여부를 나타내는 부울 값입니다."
    - id: configFileBaseName
      type: System.String
      description: "구성 파일의 이름입니다."
  overload: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  id: ConfigFileBaseName
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
  fullName: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "구성 파일의 이름을 가져오거나 설정 합니다."
  remarks: "구성 파일의 이름을 지정 하지 않으면 Web.config 사용 됩니다."
  syntax:
    content: public string ConfigFileBaseName { get; set; }
    return:
      type: System.String
      description: "구성 파일의 이름을 지정 하는 값입니다."
  overload: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "선택한 값이 null 또는 빈 문자열 (&quot;&quot;)."
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  id: IsAppRoot
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
  fullName: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "가상 디렉터리를 응용 프로그램 루트로 처리할지 여부를 나타내는 값을 가져오거나 설정 합니다."
  syntax:
    content: public bool IsAppRoot { get; set; }
    return:
      type: System.Boolean
      description: "가상 디렉터리를 응용 프로그램 루트로 처리할지 여부를 나타내는 값입니다."
  overload: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  id: PhysicalDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "웹 응용 프로그램의 전체 서버 경로 지정 하는 값을 가져오거나 설정 합니다."
  syntax:
    content: public string PhysicalDirectory { get; set; }
    return:
      type: System.String
      description: "웹 응용 프로그램의 전체 서버 경로 나타내는 값입니다."
  overload: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "선택한 값에 유효 하지 않거나 내부 보안 유효성 검사에 실패 합니다."
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  id: VirtualDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "웹 서버 루트에 상대적인 가상 디렉터리를 지정 하는 값을 가져옵니다."
  syntax:
    content: public string VirtualDirectory { get; }
    return:
      type: System.String
      description: "상대 웹 응용 프로그램 디렉터리를 나타내는 값입니다."
  overload: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping(String,Boolean)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping(String,Boolean,String)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
  fullName: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
  fullName: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
