### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  id: MessageSecurityOverTcpElement
  children:
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
  langs:
  - csharp
  name: MessageSecurityOverTcpElement
  nameWithType: MessageSecurityOverTcpElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  type: Class
  summary: "TCP를 사용 하 여 보낸 메시지의 보안에 대 한 구성 설정을 정의 합니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: 'public sealed class MessageSecurityOverTcpElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  langs:
  - csharp
  name: MessageSecurityOverTcpElement()
  nameWithType: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.MessageSecurityOverTcpElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.MessageSecurityOverTcpElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public MessageSecurityOverTcpElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverTcpElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "메시지 암호화 및 키 래핑 알고리즘 TCP 메시지 보안에 사용 되는 값을 가져오거나 설정 합니다."
  syntax:
    content: public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: "유효한 <xref href=&quot;System.ServiceModel.Security.SecurityAlgorithmSuite&quot;> </xref> TCP 메시지 보안에 사용 되는 메시지 암호화 및 키 래핑 알고리즘을 지정 하는 값입니다. 기본값은 <xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256*>.</xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256*>"
  overload: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: MessageSecurityOverTcpElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "메시지 기반 보안을 사용 하 여 클라이언트 인증을 수행할 때 사용할 자격 증명의 형식을 지정 하거나 <xref uid=&quot;langword_csharp_TransportWithMessageCredential&quot; name=&quot;TransportWithMessageCredential&quot; href=&quot;&quot;> </xref>합니다."
  syntax:
    content: public System.ServiceModel.MessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.MessageCredentialType
      description: "유효한 <xref:System.ServiceModel.MessageCredentialType>메시지 기반 보안을 사용 하 여 클라이언트 인증을 수행할 때 사용 되는 자격 증명의 형식을 지정 하는 값 또는 <xref uid=&quot;langword_csharp_TransportWithMessageCredential&quot; name=&quot;TransportWithMessageCredential&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.MessageCredentialType> 기본값은 <xref:System.ServiceModel.MessageCredentialType>.</xref:System.ServiceModel.MessageCredentialType>"
  overload: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  langs:
  - csharp
  name: Properties
  nameWithType: MessageSecurityOverTcpElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: MessageSecurityOverTcpElement()
  nameWithType: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.MessageSecurityOverTcpElement()
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverTcpElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverTcpElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
- uid: System.ServiceModel.MessageCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: MessageCredentialType
  nameWithType: MessageCredentialType
  fullName: System.ServiceModel.MessageCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverTcpElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor*
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: MessageSecurityOverTcpElement
  nameWithType: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverTcpElement.AlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverTcpElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties*
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverTcpElement.Properties
