### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.WebUtilityElement
  id: WebUtilityElement
  children:
  - System.Net.Configuration.WebUtilityElement.#ctor
  - System.Net.Configuration.WebUtilityElement.Properties
  - System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
  - System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
  langs:
  - csharp
  name: WebUtilityElement
  nameWithType: WebUtilityElement
  fullName: System.Net.Configuration.WebUtilityElement
  type: Class
  summary: "구성 파일에서 WebUtility 요소를 나타냅니다."
  remarks: "이 클래스에 해당 하는 \\<webUtility > 요소 (네트워크 설정) 구성 요소입니다. 이 클래스는 구성 파일에 저장할 수 있는 정보에 대 한 프로그래밍 방식의 액세스를 제공 합니다."
  syntax:
    content: 'public sealed class WebUtilityElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.WebUtilityElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.WebUtilityElement
  langs:
  - csharp
  name: WebUtilityElement()
  nameWithType: WebUtilityElement.WebUtilityElement()
  fullName: System.Net.Configuration.WebUtilityElement.WebUtilityElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Net.Configuration.WebUtilityElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public WebUtilityElement ();
    parameters: []
  overload: System.Net.Configuration.WebUtilityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebUtilityElement.Properties
  id: Properties
  parent: System.Net.Configuration.WebUtilityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebUtilityElement.Properties
  fullName: System.Net.Configuration.WebUtilityElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.WebUtilityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  parent: System.Net.Configuration.WebUtilityElement
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: WebUtilityElement.UnicodeDecodingConformance
  fullName: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "기본 유니코드 디코딩 규칙에 따라 사용 되는 동작에 대 한 가져옵니다는 <xref:System.Net.WebUtility>개체입니다.</xref:System.Net.WebUtility>"
  syntax:
    content: public System.Net.Configuration.UnicodeDecodingConformance UnicodeDecodingConformance { get; set; }
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Returns <xref href=&quot;System.Net.Configuration.UnicodeDecodingConformance&quot;></xref>.       기본 유니코드 디코딩 동작입니다."
  overload: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
  id: UnicodeEncodingConformance
  parent: System.Net.Configuration.WebUtilityElement
  langs:
  - csharp
  name: UnicodeEncodingConformance
  nameWithType: WebUtilityElement.UnicodeEncodingConformance
  fullName: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "기본 유니코드 인코딩 규칙에 따라 사용 되는 동작에 대 한 가져옵니다는 <xref:System.Net.WebUtility>개체입니다.</xref:System.Net.WebUtility>"
  syntax:
    content: public System.Net.Configuration.UnicodeEncodingConformance UnicodeEncodingConformance { get; set; }
    return:
      type: System.Net.Configuration.UnicodeEncodingConformance
      description: "Returns <xref href=&quot;System.Net.Configuration.UnicodeEncodingConformance&quot;></xref>.       유니코드 인코딩 기본 동작입니다."
  overload: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.WebUtilityElement.#ctor
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: WebUtilityElement()
  nameWithType: WebUtilityElement.WebUtilityElement()
  fullName: System.Net.Configuration.WebUtilityElement.WebUtilityElement()
- uid: System.Net.Configuration.WebUtilityElement.Properties
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: Properties
  nameWithType: WebUtilityElement.Properties
  fullName: System.Net.Configuration.WebUtilityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: WebUtilityElement.UnicodeDecodingConformance
  fullName: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: UnicodeEncodingConformance
  nameWithType: WebUtilityElement.UnicodeEncodingConformance
  fullName: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
- uid: System.Net.Configuration.UnicodeEncodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeEncodingConformance
  nameWithType: UnicodeEncodingConformance
  fullName: System.Net.Configuration.UnicodeEncodingConformance
- uid: System.Net.Configuration.WebUtilityElement.#ctor*
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: WebUtilityElement
  nameWithType: WebUtilityElement.WebUtilityElement
- uid: System.Net.Configuration.WebUtilityElement.Properties*
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: Properties
  nameWithType: WebUtilityElement.Properties
- uid: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance*
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: WebUtilityElement.UnicodeDecodingConformance
- uid: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance*
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: UnicodeEncodingConformance
  nameWithType: WebUtilityElement.UnicodeEncodingConformance
