### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement
  id: BasicHttpBindingElement
  children:
  - System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor
  - System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor(System.String)
  - System.ServiceModel.Configuration.BasicHttpBindingElement.BindingElementType
  - System.ServiceModel.Configuration.BasicHttpBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.BasicHttpBindingElement.MessageEncoding
  - System.ServiceModel.Configuration.BasicHttpBindingElement.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.BasicHttpBindingElement.Properties
  - System.ServiceModel.Configuration.BasicHttpBindingElement.Security
  langs:
  - csharp
  name: BasicHttpBindingElement
  nameWithType: BasicHttpBindingElement
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement
  type: Class
  summary: "WS와 통신 하는 데 사용 되는 바인딩을 지정 하는 XML 요소를 나타냅니다.-ASMX 기반 서비스와 같은 하거나 ASMX 기반 클라이언트로부터 메시지를 받을 Basic Profile 1.1 사양의 웹 서비스입니다."
  syntax:
    content: 'public class BasicHttpBindingElement : System.ServiceModel.Configuration.HttpBindingBaseElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.StandardBindingElement
  - System.ServiceModel.Configuration.HttpBindingBaseElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.HttpBindingBaseElement.AllowCookies
  - System.ServiceModel.Configuration.HttpBindingBaseElement.BypassProxyOnLocal
  - System.ServiceModel.Configuration.HttpBindingBaseElement.HostNameComparisonMode
  - System.ServiceModel.Configuration.HttpBindingBaseElement.MaxBufferPoolSize
  - System.ServiceModel.Configuration.HttpBindingBaseElement.MaxBufferSize
  - System.ServiceModel.Configuration.HttpBindingBaseElement.MaxReceivedMessageSize
  - System.ServiceModel.Configuration.HttpBindingBaseElement.ProxyAddress
  - System.ServiceModel.Configuration.HttpBindingBaseElement.ReaderQuotas
  - System.ServiceModel.Configuration.HttpBindingBaseElement.TextEncoding
  - System.ServiceModel.Configuration.HttpBindingBaseElement.TransferMode
  - System.ServiceModel.Configuration.HttpBindingBaseElement.UseDefaultWebProxy
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.StandardBindingElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.CloseTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Name
  - System.ServiceModel.Configuration.StandardBindingElement.OpenTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.ReceiveTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.StandardBindingElement.SendTimeout
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  langs:
  - csharp
  name: BasicHttpBindingElement()
  nameWithType: BasicHttpBindingElement.BasicHttpBindingElement()
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.BasicHttpBindingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.BasicHttpBindingElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public BasicHttpBindingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  langs:
  - csharp
  name: BasicHttpBindingElement(String)
  nameWithType: BasicHttpBindingElement.BasicHttpBindingElement(String)
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.BasicHttpBindingElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.BasicHttpBindingElement&quot;> </xref> 클래스 이름으로 합니다."
  syntax:
    content: public BasicHttpBindingElement (string name);
    parameters:
    - id: name
      type: System.String
      description: "바인딩 요소의 이름입니다."
  overload: System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: BasicHttpBindingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "바인딩 요소의 형식을 가져옵니다."
  syntax:
    content: protected override Type BindingElementType { get; }
    return:
      type: System.Type
      description: "바인딩 요소를 지정 하는 형식입니다."
  overload: System.ServiceModel.Configuration.BasicHttpBindingElement.BindingElementType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  id: InitializeFrom(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  langs:
  - csharp
  name: InitializeFrom(Binding)
  nameWithType: BasicHttpBindingElement.InitializeFrom(Binding)
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.InitializeFrom(Binding)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정된 된 바인딩 컬렉션의 내용 사용 하 여이 바인딩 구성 요소를 초기화합니다."
  syntax:
    content: protected override void InitializeFrom (System.ServiceModel.Channels.Binding binding);
    parameters:
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "바인딩 요소의 컬렉션입니다."
  overload: System.ServiceModel.Configuration.BasicHttpBindingElement.InitializeFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.MessageEncoding
  id: MessageEncoding
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  langs:
  - csharp
  name: MessageEncoding
  nameWithType: BasicHttpBindingElement.MessageEncoding
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.MessageEncoding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "SOAP 메시지 인코딩에 MTOM 이나 텍스트/x m L 사용 여부를 나타내는 값을 가져오거나 설정 합니다."
  syntax:
    content: public System.ServiceModel.WSMessageEncoding MessageEncoding { get; set; }
    return:
      type: System.ServiceModel.WSMessageEncoding
      description: "값 <xref href=&quot;System.ServiceModel.WSMessageEncoding&quot;> </xref> 나타내는 SOAP 메시지 인코딩에 MTOM 이나 텍스트/x m L 사용 됩니다. 기본값은 <xref href=&quot;System.ServiceModel.WSMessageEncoding&quot;> </xref>합니다."
  overload: System.ServiceModel.Configuration.BasicHttpBindingElement.MessageEncoding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  id: OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  langs:
  - csharp
  name: OnApplyConfiguration(Binding)
  nameWithType: BasicHttpBindingElement.OnApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.OnApplyConfiguration(Binding)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정된 된 바인딩 컬렉션의 내용을이 바인딩 구성 요소에 적용 될 때 호출 됩니다."
  syntax:
    content: protected override void OnApplyConfiguration (System.ServiceModel.Channels.Binding binding);
    parameters:
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "바인딩 요소의 컬렉션입니다."
  overload: System.ServiceModel.Configuration.BasicHttpBindingElement.OnApplyConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  langs:
  - csharp
  name: Properties
  nameWithType: BasicHttpBindingElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 의 컬렉션을 포함 하는 인스턴스 <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> 특성 일 수 있는 개체 또는 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 이 바인딩 구성 요소 개체입니다."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> 의 컬렉션을 포함 하는 인스턴스 <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> 특성 일 수 있는 개체 또는 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> 이 바인딩 구성 요소 개체입니다."
  overload: System.ServiceModel.Configuration.BasicHttpBindingElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.Security
  id: Security
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  langs:
  - csharp
  name: Security
  nameWithType: BasicHttpBindingElement.Security
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.Security
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "이 바인딩과 함께 사용 되는 보안 형식을 가져오거나 설정 합니다."
  syntax:
    content: public System.ServiceModel.Configuration.BasicHttpSecurityElement Security { get; }
    return:
      type: System.ServiceModel.Configuration.BasicHttpSecurityElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.BasicHttpSecurityElement&quot;> </xref> 이 바인딩과 함께 사용 되는 보안 형식을 지정 하 합니다."
  overload: System.ServiceModel.Configuration.BasicHttpBindingElement.Security*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.HttpBindingBaseElement
  isExternal: false
  name: System.ServiceModel.Configuration.HttpBindingBaseElement
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: BasicHttpBindingElement()
  nameWithType: BasicHttpBindingElement.BasicHttpBindingElement()
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.BasicHttpBindingElement()
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: BasicHttpBindingElement(String)
  nameWithType: BasicHttpBindingElement.BasicHttpBindingElement(String)
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.BasicHttpBindingElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.BindingElementType
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: BindingElementType
  nameWithType: BasicHttpBindingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: InitializeFrom(Binding)
  nameWithType: BasicHttpBindingElement.InitializeFrom(Binding)
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.InitializeFrom(Binding)
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.MessageEncoding
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: MessageEncoding
  nameWithType: BasicHttpBindingElement.MessageEncoding
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.MessageEncoding
- uid: System.ServiceModel.WSMessageEncoding
  parent: System.ServiceModel
  isExternal: false
  name: WSMessageEncoding
  nameWithType: WSMessageEncoding
  fullName: System.ServiceModel.WSMessageEncoding
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: OnApplyConfiguration(Binding)
  nameWithType: BasicHttpBindingElement.OnApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.OnApplyConfiguration(Binding)
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.Properties
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpBindingElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.Security
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: Security
  nameWithType: BasicHttpBindingElement.Security
  fullName: System.ServiceModel.Configuration.BasicHttpBindingElement.Security
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BasicHttpSecurityElement
  nameWithType: BasicHttpSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.#ctor*
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: BasicHttpBindingElement
  nameWithType: BasicHttpBindingElement.BasicHttpBindingElement
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.BindingElementType*
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: BindingElementType
  nameWithType: BasicHttpBindingElement.BindingElementType
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: InitializeFrom
  nameWithType: BasicHttpBindingElement.InitializeFrom
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.MessageEncoding*
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: MessageEncoding
  nameWithType: BasicHttpBindingElement.MessageEncoding
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.OnApplyConfiguration*
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: OnApplyConfiguration
  nameWithType: BasicHttpBindingElement.OnApplyConfiguration
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.Properties*
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpBindingElement.Properties
- uid: System.ServiceModel.Configuration.BasicHttpBindingElement.Security*
  parent: System.ServiceModel.Configuration.BasicHttpBindingElement
  isExternal: false
  name: Security
  nameWithType: BasicHttpBindingElement.Security
