### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  id: ActivityXamlServicesSettings
  children:
  - System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor
  - System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
  - System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
  langs:
  - csharp
  name: ActivityXamlServicesSettings
  nameWithType: ActivityXamlServicesSettings
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  type: Class
  summary: "XAML 서비스 설정을 지정합니다."
  syntax:
    content: public class ActivityXamlServicesSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor
  id: '#ctor'
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  langs:
  - csharp
  name: ActivityXamlServicesSettings()
  nameWithType: ActivityXamlServicesSettings.ActivityXamlServicesSettings()
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.ActivityXamlServicesSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Activities.XamlIntegration.ActivityXamlServicesSettings&quot;> </xref> 클래스입니다."
  syntax:
    content: public ActivityXamlServicesSettings ();
    parameters: []
  overload: System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
  id: CompileExpressions
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  langs:
  - csharp
  name: CompileExpressions
  nameWithType: ActivityXamlServicesSettings.CompileExpressions
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "식은 컴파일되는지 여부를 나타내는 값을 가져오거나 설정 합니다."
  syntax:
    content: public bool CompileExpressions { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>식은; 컴파일할 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
  id: LocationReferenceEnvironment
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  langs:
  - csharp
  name: LocationReferenceEnvironment
  nameWithType: ActivityXamlServicesSettings.LocationReferenceEnvironment
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "작업의 위치 참조 환경 설정 하거나 가져옵니다."
  syntax:
    content: public System.Activities.LocationReferenceEnvironment LocationReferenceEnvironment { get; set; }
    return:
      type: System.Activities.LocationReferenceEnvironment
      description: "작업의 위치 참조 환경입니다."
  overload: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: ActivityXamlServicesSettings()
  nameWithType: ActivityXamlServicesSettings.ActivityXamlServicesSettings()
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.ActivityXamlServicesSettings()
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: CompileExpressions
  nameWithType: ActivityXamlServicesSettings.CompileExpressions
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: ActivityXamlServicesSettings.LocationReferenceEnvironment
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
- uid: System.Activities.LocationReferenceEnvironment
  parent: System.Activities
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor*
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: ActivityXamlServicesSettings
  nameWithType: ActivityXamlServicesSettings.ActivityXamlServicesSettings
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions*
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: CompileExpressions
  nameWithType: ActivityXamlServicesSettings.CompileExpressions
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment*
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: ActivityXamlServicesSettings.LocationReferenceEnvironment
