### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  id: DiscoveryClientSettingsElement
  children:
  - System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.#ctor
  - System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryEndpoint
  - System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.FindCriteria
  - System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.Properties
  langs:
  - csharp
  name: DiscoveryClientSettingsElement
  nameWithType: DiscoveryClientSettingsElement
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  type: Class
  summary: "해당 설정을 사용 하는 클라이언트 응용 프로그램을 검색 가능 워크플로 서비스에 대 한 자동으로 검색 하 고 런타임 시 해당 주소를 찾을 구성 요소를 제공 합니다."
  syntax:
    content: 'public sealed class DiscoveryClientSettingsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  langs:
  - csharp
  name: DiscoveryClientSettingsElement()
  nameWithType: DiscoveryClientSettingsElement.DiscoveryClientSettingsElement()
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryClientSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public DiscoveryClientSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryEndpoint
  id: DiscoveryEndpoint
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  langs:
  - csharp
  name: DiscoveryEndpoint
  nameWithType: DiscoveryClientSettingsElement.DiscoveryEndpoint
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryEndpoint
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.ServiceModel.Configuration.ChannelEndpointElement&quot;> </xref> 클라이언트 응용 프로그램에서 자동으로 검색 가능 워크플로 서비스를 검색 하 고 런타임 시 해당 주소를 찾을 수 있도록 합니다."
  syntax:
    content: public System.ServiceModel.Configuration.ChannelEndpointElement DiscoveryEndpoint { get; }
    return:
      type: System.ServiceModel.Configuration.ChannelEndpointElement
      description: "채널 끝점입니다."
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.FindCriteria
  id: FindCriteria
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  langs:
  - csharp
  name: FindCriteria
  nameWithType: DiscoveryClientSettingsElement.FindCriteria
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.FindCriteria
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "가져옵니다는 <xref href=&quot;System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;> </xref> 검색 워크플로 서비스를 검색 하려면 클라이언트 응용 프로그램에서 사용 되는 조건 집합을 제공 하 합니다."
  syntax:
    content: public System.ServiceModel.Discovery.Configuration.FindCriteriaElement FindCriteria { get; }
    return:
      type: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
      description: "찾기 조건 요소입니다."
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.FindCriteria*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: DiscoveryClientSettingsElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  isExternal: false
  name: DiscoveryClientSettingsElement()
  nameWithType: DiscoveryClientSettingsElement.DiscoveryClientSettingsElement()
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryClientSettingsElement()
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryEndpoint
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  isExternal: false
  name: DiscoveryEndpoint
  nameWithType: DiscoveryClientSettingsElement.DiscoveryEndpoint
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryEndpoint
- uid: System.ServiceModel.Configuration.ChannelEndpointElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ChannelEndpointElement
  nameWithType: ChannelEndpointElement
  fullName: System.ServiceModel.Configuration.ChannelEndpointElement
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.FindCriteria
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  isExternal: false
  name: FindCriteria
  nameWithType: DiscoveryClientSettingsElement.FindCriteria
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.FindCriteria
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  parent: System.ServiceModel.Discovery.Configuration
  isExternal: false
  name: FindCriteriaElement
  nameWithType: FindCriteriaElement
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.Properties
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  isExternal: false
  name: Properties
  nameWithType: DiscoveryClientSettingsElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  isExternal: false
  name: DiscoveryClientSettingsElement
  nameWithType: DiscoveryClientSettingsElement.DiscoveryClientSettingsElement
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.DiscoveryEndpoint*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  isExternal: false
  name: DiscoveryEndpoint
  nameWithType: DiscoveryClientSettingsElement.DiscoveryEndpoint
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.FindCriteria*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  isExternal: false
  name: FindCriteria
  nameWithType: DiscoveryClientSettingsElement.FindCriteria
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement.Properties*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryClientSettingsElement
  isExternal: false
  name: Properties
  nameWithType: DiscoveryClientSettingsElement.Properties
