### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.NamedPipeSettings
  id: NamedPipeSettings
  children:
  - System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
  langs:
  - csharp
  name: NamedPipeSettings
  nameWithType: NamedPipeSettings
  fullName: System.ServiceModel.Channels.NamedPipeSettings
  type: Class
  summary: "명명 된 파이프 설정을 지정합니다."
  syntax:
    content: public sealed class NamedPipeSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
  id: ApplicationContainerSettings
  parent: System.ServiceModel.Channels.NamedPipeSettings
  langs:
  - csharp
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettings.ApplicationContainerSettings
  fullName: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "명명 된 파이프 설정에 대 한 응용 프로그램 컨테이너 설정을 가져오거나 설정 합니다."
  syntax:
    content: public System.ServiceModel.Channels.ApplicationContainerSettings ApplicationContainerSettings { get; }
    return:
      type: System.ServiceModel.Channels.ApplicationContainerSettings
      description: "명명 된 파이프 설정에 대 한 응용 프로그램 컨테이너 설정 합니다."
  overload: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
  parent: System.ServiceModel.Channels.NamedPipeSettings
  isExternal: false
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettings.ApplicationContainerSettings
  fullName: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
- uid: System.ServiceModel.Channels.ApplicationContainerSettings
  parent: System.ServiceModel.Channels
  isExternal: false
  name: ApplicationContainerSettings
  nameWithType: ApplicationContainerSettings
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings
- uid: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings*
  parent: System.ServiceModel.Channels.NamedPipeSettings
  isExternal: false
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettings.ApplicationContainerSettings
