### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  id: BufferedReceiveElement
  children:
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
  langs:
  - csharp
  name: BufferedReceiveElement
  nameWithType: BufferedReceiveElement
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  type: Class
  summary: "워크플로 서비스 작업에 의해 클라이언트에서 받은 데이터의 버퍼링을 제어 하는 구성 요소를 정의 합니다. 클래스는 봉인된 클래스입니다."
  syntax:
    content: 'public sealed class BufferedReceiveElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: BufferedReceiveElement()
  nameWithType: BufferedReceiveElement.BufferedReceiveElement()
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BufferedReceiveElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.ServiceModel.Activities.Configuration.BufferedReceiveElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public BufferedReceiveElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: BufferedReceiveElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "워크플로의 클라이언트 인스턴스로부터 받는 메시지의 워크플로 런타임 버퍼링을 제어 하는 서비스 요소의 동작 형식을 가져옵니다."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "형식 개체입니다."
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: BufferedReceiveElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
  id: MaxPendingMessagesPerChannel
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: MaxPendingMessagesPerChannel
  nameWithType: BufferedReceiveElement.MaxPendingMessagesPerChannel
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "워크플로 서비스 작업 중 통신 채널에 버퍼링 할 수 있는 메시지의 최대 수를 가져오거나 설정 합니다."
  syntax:
    content: public int MaxPendingMessagesPerChannel { get; set; }
    return:
      type: System.Int32
      description: "정수입니다."
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: Properties
  nameWithType: BufferedReceiveElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: BufferedReceiveElement()
  nameWithType: BufferedReceiveElement.BufferedReceiveElement()
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BufferedReceiveElement()
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: BehaviorType
  nameWithType: BufferedReceiveElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: BufferedReceiveElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: MaxPendingMessagesPerChannel
  nameWithType: BufferedReceiveElement.MaxPendingMessagesPerChannel
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: Properties
  nameWithType: BufferedReceiveElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: BufferedReceiveElement
  nameWithType: BufferedReceiveElement.BufferedReceiveElement
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: BehaviorType
  nameWithType: BufferedReceiveElement.BehaviorType
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: CreateBehavior
  nameWithType: BufferedReceiveElement.CreateBehavior
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: MaxPendingMessagesPerChannel
  nameWithType: BufferedReceiveElement.MaxPendingMessagesPerChannel
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: Properties
  nameWithType: BufferedReceiveElement.Properties
