### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.HttpDigestClientElement
  id: HttpDigestClientElement
  children:
  - System.ServiceModel.Configuration.HttpDigestClientElement.#ctor
  - System.ServiceModel.Configuration.HttpDigestClientElement.Copy(System.ServiceModel.Configuration.HttpDigestClientElement)
  - System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
  - System.ServiceModel.Configuration.HttpDigestClientElement.Properties
  langs:
  - csharp
  name: HttpDigestClientElement
  nameWithType: HttpDigestClientElement
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement
  type: Class
  summary: "현재 HTTP 다이제스트 자격 증명을 나타냅니다는 <xref uid=&quot;langword_csharp_clientCredential&quot; name=&quot;clientCredential&quot; href=&quot;&quot;> </xref> 요소입니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: 'public sealed class HttpDigestClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  langs:
  - csharp
  name: HttpDigestClientElement()
  nameWithType: HttpDigestClientElement.HttpDigestClientElement()
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.HttpDigestClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.HttpDigestClientElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public HttpDigestClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.HttpDigestClientElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Copy(System.ServiceModel.Configuration.HttpDigestClientElement)
  id: Copy(System.ServiceModel.Configuration.HttpDigestClientElement)
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  langs:
  - csharp
  name: Copy(HttpDigestClientElement)
  nameWithType: HttpDigestClientElement.Copy(HttpDigestClientElement)
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.Copy(HttpDigestClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "지정 된 구성 요소의 내용을이 구성 요소에 복사합니다."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.HttpDigestClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.HttpDigestClientElement
      description: "복사할 구성 요소입니다."
  overload: System.ServiceModel.Configuration.HttpDigestClientElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code><xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> 이거나 비어 있습니다."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "구성 파일에는 읽기 전용입니다."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
  id: ImpersonationLevel
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  langs:
  - csharp
  name: ImpersonationLevel
  nameWithType: HttpDigestClientElement.ImpersonationLevel
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "서버와 통신 하도록 클라이언트가 사용 하는 가장 기본 설정을 가져오거나 설정 합니다."
  remarks: "클라이언트에서 선택 하는 가장 모드 서버에 적용 되지 않습니다."
  syntax:
    content: public System.Security.Principal.TokenImpersonationLevel ImpersonationLevel { get; set; }
    return:
      type: System.Security.Principal.TokenImpersonationLevel
      description: "유효한 <xref:System.Security.Principal.TokenImpersonationLevel>값.</xref:System.Security.Principal.TokenImpersonationLevel> 기본값은 <xref:System.Security.Principal.TokenImpersonationLevel>.</xref:System.Security.Principal.TokenImpersonationLevel>"
  overload: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpDigestClientElement.Properties
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.HttpDigestClientElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.#ctor
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: HttpDigestClientElement()
  nameWithType: HttpDigestClientElement.HttpDigestClientElement()
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.HttpDigestClientElement()
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Copy(System.ServiceModel.Configuration.HttpDigestClientElement)
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: Copy(HttpDigestClientElement)
  nameWithType: HttpDigestClientElement.Copy(HttpDigestClientElement)
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.Copy(HttpDigestClientElement)
- uid: System.ServiceModel.Configuration.HttpDigestClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HttpDigestClientElement
  nameWithType: HttpDigestClientElement
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: ImpersonationLevel
  nameWithType: HttpDigestClientElement.ImpersonationLevel
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel
- uid: System.Security.Principal.TokenImpersonationLevel
  parent: System.Security.Principal
  isExternal: true
  name: TokenImpersonationLevel
  nameWithType: TokenImpersonationLevel
  fullName: System.Security.Principal.TokenImpersonationLevel
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Properties
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: Properties
  nameWithType: HttpDigestClientElement.Properties
  fullName: System.ServiceModel.Configuration.HttpDigestClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.#ctor*
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: HttpDigestClientElement
  nameWithType: HttpDigestClientElement.HttpDigestClientElement
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Copy*
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: Copy
  nameWithType: HttpDigestClientElement.Copy
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.ImpersonationLevel*
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: ImpersonationLevel
  nameWithType: HttpDigestClientElement.ImpersonationLevel
- uid: System.ServiceModel.Configuration.HttpDigestClientElement.Properties*
  parent: System.ServiceModel.Configuration.HttpDigestClientElement
  isExternal: false
  name: Properties
  nameWithType: HttpDigestClientElement.Properties
