### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigRecord
  id: IInternalConfigRecord
  children:
  - System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  - System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  - System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  - System.Configuration.Internal.IInternalConfigRecord.Remove
  - System.Configuration.Internal.IInternalConfigRecord.StreamName
  - System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  langs:
  - csharp
  name: IInternalConfigRecord
  nameWithType: IInternalConfigRecord
  fullName: System.Configuration.Internal.IInternalConfigRecord
  type: Interface
  summary: "새 구성 레코드 생성을 지원 하려면.NET 구조체 내부에서 사용 되는 인터페이스를 정의 합니다."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigRecord
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  id: ConfigPath
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
  fullName: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "구성 파일 경로 나타내는 문자열을 가져옵니다."
  syntax:
    content: public string ConfigPath { get; }
    return:
      type: System.String
      description: "구성 파일 경로 나타내는 문자열입니다."
  overload: System.Configuration.Internal.IInternalConfigRecord.ConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  id: GetLkgSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: GetLkgSection(String)
  nameWithType: IInternalConfigRecord.GetLkgSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "마지막으로 성공한 (LKG) 구성에서 구성 섹션을 나타내는 개체를 반환 합니다."
  syntax:
    content: public object GetLkgSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: "구성 섹션에는 키를 나타내는 문자열입니다."
    return:
      type: System.Object
      description: "<xref:System.Object>마지막으로 성공한 구성으로 지정 된 섹션을 나타내는 인스턴스 <code> configKey </code>.</xref:System.Object>"
  overload: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: IInternalConfigRecord.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "반환 된 <xref:System.Object>인스턴스는 구성 파일의 섹션을 나타냅니다.</xref:System.Object>"
  syntax:
    content: public object GetSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: "구성 섹션에는 키를 나타내는 문자열입니다."
    return:
      type: System.Object
      description: "<xref:System.Object>인스턴스는 구성 파일의 섹션을 나타냅니다.</xref:System.Object>"
  overload: System.Configuration.Internal.IInternalConfigRecord.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  id: HasInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
  fullName: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "구성 개체를 초기화 하는 동안 오류가 발생 했는지 여부를 나타내는 값을 반환 합니다."
  syntax:
    content: public bool HasInitErrors { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>구성 개체;의 초기화 동안 오류가 발생 하는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  id: RefreshSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: RefreshSection(String)
  nameWithType: IInternalConfigRecord.RefreshSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "다시 초기화 해야 할 구성 개체의 지정 된 섹션이 합니다."
  syntax:
    content: public void RefreshSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: "새로 고칠 수 있는 구성 섹션에는 키를 나타내는 문자열입니다."
  overload: System.Configuration.Internal.IInternalConfigRecord.RefreshSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove
  id: Remove
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: Remove()
  nameWithType: IInternalConfigRecord.Remove()
  fullName: System.Configuration.Internal.IInternalConfigRecord.Remove()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "구성 레코드를 제거합니다."
  syntax:
    content: public void Remove ();
    parameters: []
  overload: System.Configuration.Internal.IInternalConfigRecord.Remove*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName
  id: StreamName
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
  fullName: System.Configuration.Internal.IInternalConfigRecord.StreamName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "이름을 반환 하는 <xref:System.IO.Stream>구성 파일에서 I/O를 수행 하는 개체 작업.</xref:System.IO.Stream>"
  syntax:
    content: public string StreamName { get; }
    return:
      type: System.String
      description: "이름을 나타내는 문자열을 <xref:System.IO.Stream>구성 파일에서 I/O를 수행 하는 개체 작업.</xref:System.IO.Stream>"
  overload: System.Configuration.Internal.IInternalConfigRecord.StreamName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  id: ThrowIfInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  langs:
  - csharp
  name: ThrowIfInitErrors()
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors()
  fullName: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "구성 개체를 초기화 하는 동안 오류가 발생 하면 예외를 throw 하는 권한을 부여 합니다."
  syntax:
    content: public void ThrowIfInitErrors ();
    parameters: []
  overload: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
  fullName: System.Configuration.Internal.IInternalConfigRecord.ConfigPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetLkgSection(String)
  nameWithType: IInternalConfigRecord.GetLkgSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetSection(String)
  nameWithType: IInternalConfigRecord.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.GetSection(String)
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
  fullName: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: RefreshSection(String)
  nameWithType: IInternalConfigRecord.RefreshSection(String)
  fullName: System.Configuration.Internal.IInternalConfigRecord.RefreshSection(String)
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: Remove()
  nameWithType: IInternalConfigRecord.Remove()
  fullName: System.Configuration.Internal.IInternalConfigRecord.Remove()
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
  fullName: System.Configuration.Internal.IInternalConfigRecord.StreamName
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ThrowIfInitErrors()
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors()
  fullName: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors()
- uid: System.Configuration.Internal.IInternalConfigRecord.ConfigPath*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ConfigPath
  nameWithType: IInternalConfigRecord.ConfigPath
- uid: System.Configuration.Internal.IInternalConfigRecord.GetLkgSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetLkgSection
  nameWithType: IInternalConfigRecord.GetLkgSection
- uid: System.Configuration.Internal.IInternalConfigRecord.GetSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: GetSection
  nameWithType: IInternalConfigRecord.GetSection
- uid: System.Configuration.Internal.IInternalConfigRecord.HasInitErrors*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: HasInitErrors
  nameWithType: IInternalConfigRecord.HasInitErrors
- uid: System.Configuration.Internal.IInternalConfigRecord.RefreshSection*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: RefreshSection
  nameWithType: IInternalConfigRecord.RefreshSection
- uid: System.Configuration.Internal.IInternalConfigRecord.Remove*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: Remove
  nameWithType: IInternalConfigRecord.Remove
- uid: System.Configuration.Internal.IInternalConfigRecord.StreamName*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: StreamName
  nameWithType: IInternalConfigRecord.StreamName
- uid: System.Configuration.Internal.IInternalConfigRecord.ThrowIfInitErrors*
  parent: System.Configuration.Internal.IInternalConfigRecord
  isExternal: false
  name: ThrowIfInitErrors
  nameWithType: IInternalConfigRecord.ThrowIfInitErrors
