### YamlMime:ManagedReference
items:
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  id: PropertyValueSource
  children:
  - System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  langs:
  - csharp
  name: PropertyValueSource
  nameWithType: PropertyValueSource
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  type: Class
  summary: "속성 값의 원본을 나타냅니다."
  remarks: "속성 값 원본의 예에는 상속 된 값, 부모 템플릿 값, 기본값, 암시적 스타일 참조, 트리거 기반 값 등을 포함할 수 있습니다."
  example:
  - '[!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]'
  syntax:
    content: public abstract class PropertyValueSource
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  id: '#ctor'
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  langs:
  - csharp
  name: PropertyValueSource()
  nameWithType: PropertyValueSource.PropertyValueSource()
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource.PropertyValueSource()
  type: Constructor
  assemblies:
  - System.Activities.Presentation
  namespace: System.Activities.Presentation.PropertyEditing
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.Activities.Presentation.PropertyEditing.PropertyValueSource&quot;> </xref> 클래스입니다."
  syntax:
    content: protected PropertyValueSource ();
    parameters: []
  overload: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  isExternal: false
  name: PropertyValueSource()
  nameWithType: PropertyValueSource.PropertyValueSource()
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource.PropertyValueSource()
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor*
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  isExternal: false
  name: PropertyValueSource
  nameWithType: PropertyValueSource.PropertyValueSource
