### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationValidatorAttribute
  id: ConfigurationValidatorAttribute
  children:
  - System.Configuration.ConfigurationValidatorAttribute.#ctor
  - System.Configuration.ConfigurationValidatorAttribute.#ctor(System.Type)
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  langs:
  - csharp
  name: ConfigurationValidatorAttribute
  nameWithType: ConfigurationValidatorAttribute
  fullName: System.Configuration.ConfigurationValidatorAttribute
  type: Class
  summary: "에 대 한 기본 클래스 역할을 <xref href=&quot;System.Configuration&quot;> </xref> 유효성 검사기 특성 유형입니다."
  remarks: "모든 ASP.NET 구성 유효성 검사기 표준 특성 유형 ConfigurationValidatorAttribute에서 파생 됩니다. 사용자 고유의 사용자 지정 유효성 검사기 특성을 만들려면이 형식을 사용할 수 있습니다."
  example:
  - "The following code examples demonstrate how to create two custom validators using the ConfigurationValidatorAttribute type. The first example performs validation using hard-coded parameters; the second example performs validation using the parameters assigned to it at the time it is applied to the related section property. This code example also contains three supporting files. The first file contains the custom section that uses the validators described above, the second file contains a custom converter type, and the third file contains the console application that builds and uses the custom validators and the section that contains them.  \n  \n The following code example shows how to create a fixed validator with hard-coded parameters.  \n  \n [!code-cs[System.Configuration.ConfigValidatorAttribute#21](~/add/codesnippet/csharp/t-system.configuration.c_11_1.cs)]\n [!code-vb[System.Configuration.ConfigValidatorAttribute#21](~/add/codesnippet/visualbasic/t-system.configuration.c_11_1.vb)]  \n  \n The following code example shows how to create a programmable validator.  \n  \n [!code-cs[System.Configuration.ConfigValidatorAttribute#31](~/add/codesnippet/csharp/t-system.configuration.c_11_2.cs)]\n [!code-vb[System.Configuration.ConfigValidatorAttribute#31](~/add/codesnippet/visualbasic/t-system.configuration.c_11_2.vb)]  \n  \n The following code example shows how to create a custom section using the previous validators.  \n  \n [!code-cs[System.Configuration.ConfigValidatorAttribute#11](~/add/codesnippet/csharp/t-system.configuration.c_11_3.cs)]\n [!code-vb[System.Configuration.ConfigValidatorAttribute#11](~/add/codesnippet/visualbasic/t-system.configuration.c_11_3.vb)]  \n  \n The following code example shows how to create a custom converter.  \n  \n [!code-cs[System.Configuration.ConfigValidatorAttribute#1](~/add/codesnippet/csharp/t-system.configuration.c_11_4.cs)]\n [!code-vb[System.Configuration.ConfigValidatorAttribute#1](~/add/codesnippet/visualbasic/t-system.configuration.c_11_4.vb)]  \n  \n The following code example shows how to create the console application that builds and uses the custom validators and their containing section.  \n  \n [!code-cs[System.Configuration.ConfigValidatorAttribute#41](~/add/codesnippet/csharp/t-system.configuration.c_11_5.cs)]\n [!code-vb[System.Configuration.ConfigValidatorAttribute#41](~/add/codesnippet/visualbasic/t-system.configuration.c_11_5.vb)]  \n  \n The following code example is a configuration excerpt used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n    <configSections>  \n        <section name=\"Cars\" type=\"Samples.AspNet.SelectCar, ConfigValidatorAttribute, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\" allowLocation=\"false\" allowDefinition=\"Everywhere\" allowExeDefinition=\"MachineToApplication\" restartOnExternalChanges=\"true\" requirePermission=\"true\" />  \n    </configSections>  \n    <Cars commute=\"Make:AlfaRomeo Color:Blue Miles:10000 Year:2002\"  \n        dream=\"Make:Ferrari Color:Red Miles:10 Year:2005\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public class ConfigurationValidatorAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationValidatorAttribute
  langs:
  - csharp
  name: ConfigurationValidatorAttribute()
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute()
  fullName: System.Configuration.ConfigurationValidatorAttribute.ConfigurationValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.ConfigurationValidatorAttribute&quot;> </xref> 클래스입니다."
  remarks: "특성 사용 모델에서 관련된 속성에 할당 된 값이 정수 인지 확인 하려면이 생성자를 사용 합니다."
  syntax:
    content: protected ConfigurationValidatorAttribute ();
    parameters: []
  overload: System.Configuration.ConfigurationValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.ConfigurationValidatorAttribute
  langs:
  - csharp
  name: ConfigurationValidatorAttribute(Type)
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute(Type)
  fullName: System.Configuration.ConfigurationValidatorAttribute.ConfigurationValidatorAttribute(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.ConfigurationValidatorAttribute&quot;> </xref> 클래스 지정 된 유효성 검사기 형식을 사용 합니다."
  remarks: "이 생성자는 지정 된 인스턴스로부터 유효성 검사기 인스턴스를 만들 수 있는지 여부를 결정 `validator` 유형입니다."
  syntax:
    content: public ConfigurationValidatorAttribute (Type validator);
    parameters:
    - id: validator
      type: System.Type
      description: "인스턴스를 만들 때 사용할 유효성 검사기 형식 <xref href=&quot;System.Configuration.ConfigurationValidatorAttribute&quot;> </xref>합니다."
  overload: System.Configuration.ConfigurationValidatorAttribute.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>validator</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>validator</code>파생 되지 않은 <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref>합니다."
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.ConfigurationValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: ConfigurationValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "유효성 검사기 특성 인스턴스를 가져옵니다."
  syntax:
    content: public virtual System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "현재 <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref>합니다."
  overload: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  id: ValidatorType
  parent: System.Configuration.ConfigurationValidatorAttribute
  langs:
  - csharp
  name: ValidatorType
  nameWithType: ConfigurationValidatorAttribute.ValidatorType
  fullName: System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "유효성 검사기 특성의 유형을 가져옵니다."
  syntax:
    content: public Type ValidatorType { get; }
    return:
      type: System.Type
      description: "<xref:System.Type>현재 유효성 검사기 특성 인스턴스의.</xref:System.Type>"
  overload: System.Configuration.ConfigurationValidatorAttribute.ValidatorType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ConfigurationValidatorAttribute()
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute()
  fullName: System.Configuration.ConfigurationValidatorAttribute.ConfigurationValidatorAttribute()
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor(System.Type)
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ConfigurationValidatorAttribute(Type)
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute(Type)
  fullName: System.Configuration.ConfigurationValidatorAttribute.ConfigurationValidatorAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: ConfigurationValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ValidatorType
  nameWithType: ConfigurationValidatorAttribute.ValidatorType
  fullName: System.Configuration.ConfigurationValidatorAttribute.ValidatorType
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor*
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ConfigurationValidatorAttribute
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: ConfigurationValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorType*
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ValidatorType
  nameWithType: ConfigurationValidatorAttribute.ValidatorType
