### YamlMime:ManagedReference
items:
- uid: System.Configuration.InfiniteIntConverter
  id: InfiniteIntConverter
  children:
  - System.Configuration.InfiniteIntConverter.#ctor
  - System.Configuration.InfiniteIntConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.InfiniteIntConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: InfiniteIntConverter
  nameWithType: InfiniteIntConverter
  fullName: System.Configuration.InfiniteIntConverter
  type: Class
  summary: "문자열 및 표준 무한 값 또는 정수 값 간에 변환합니다."
  remarks: "이 형식에는 다른 모든 구성 변환기 종류와 같은 강력한 형식의 관련된 속성에서 구성 파일에 문자열을 변환 합니다.       특히, InfiniteIntConverter 클래스에는 정수 값으로 또는 그 반대로 구성 속성에 할당 된 문자열 값을 변환 합니다. 이 값을 변환 구성 속성이 &quot;무제한&quot;의 문자열 값이 있으면 <xref:System.Int32>그 반대의.</xref:System.Int32>       이 변환기는 정수 형식과 함께 사용 됩니다. 무한 값 <xref:System.Int32>.</xref:System.Int32> 으로 유지 됩니다."
  example:
  - "The following code example shows how to use the InfiniteIntConverter when applied to a custom section property.  \n  \n [!code-cs[System.Configuration.ConfigurationConvertersCustomSection#5](~/add/codesnippet/csharp/t-system.configuration.i_7_1.cs)]\n [!code-vb[System.Configuration.ConfigurationConvertersCustomSection#5](~/add/codesnippet/visualbasic/t-system.configuration.i_7_1.vb)]"
  syntax:
    content: 'public sealed class InfiniteIntConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.InfiniteIntConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.InfiniteIntConverter
  langs:
  - csharp
  name: InfiniteIntConverter()
  nameWithType: InfiniteIntConverter.InfiniteIntConverter()
  fullName: System.Configuration.InfiniteIntConverter.InfiniteIntConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.InfiniteIntConverter&quot;> </xref> 클래스입니다."
  remarks: "일반적으로 시스템에서 제공 하는 변환기 종류를 사용 합니다. 사용자 지정 변환 형식을 만들 때는 InfiniteIntConverter 생성자를 사용 해야 합니다."
  syntax:
    content: public InfiniteIntConverter ();
    parameters: []
  overload: System.Configuration.InfiniteIntConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteIntConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteIntConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteIntConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteIntConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "<xref:System.String> <xref:System.Int32>.</xref:System.Int32> </xref:System.String> 변환"
  remarks: "시스템은 ConvertFrom 메서드는 구성 파일에서 읽을 때 사용 하 여 변환 <xref:System.String> <xref:System.Int32>.</xref:System.Int32> 값</xref:System.String>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> 형식 변환에 사용 되는 개체입니다."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>변환 하는 동안 사용 되는 개체입니다.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "<xref:System.String>변환할 개체입니다.</xref:System.String>"
    return:
      type: System.Object
      description: "<xref:System.Int32.MaxValue>경우는 <code> data </code> 매개 변수는는 <xref:System.String>고, 그러지 않으면 &quot;무한&quot;는 <xref:System.Int32>나타내는 <code> data </code> 매개 변수에 정수 값입니다.</xref:System.Int32> </xref:System.String> </xref:System.Int32.MaxValue>"
  overload: System.Configuration.InfiniteIntConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteIntConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteIntConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteIntConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteIntConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "으로 변환 <xref:System.Int32>하려면 <xref:System.String>.</xref:System.String> </xref:System.Int32>"
  remarks: "시스템에서는 ConvertTo 구성 파일에 쓸 때 <xref:System.Int32> <xref:System.String>.</xref:System.String> </xref:System.Int32> 변환합니다"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> 형식 변환에 사용 되는 개체입니다."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>변환 하는 동안 사용 되는 개체입니다.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "변환할 값입니다."
    - id: type
      type: System.Type
      description: "변환할 대상 형식입니다."
    return:
      type: System.Object
      description: "<xref:System.String>&quot;무한&quot; 경우에는 <code> value </code> 은 <xref:System.Int32.MaxValue>, 그렇지 않으면는 <xref:System.String>나타내는 <code> value </code> 매개 변수.</xref:System.String> </xref:System.Int32.MaxValue> </xref:System.String>"
  overload: System.Configuration.InfiniteIntConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.InfiniteIntConverter.#ctor
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: InfiniteIntConverter()
  nameWithType: InfiniteIntConverter.InfiniteIntConverter()
  fullName: System.Configuration.InfiniteIntConverter.InfiniteIntConverter()
- uid: System.Configuration.InfiniteIntConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteIntConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteIntConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.InfiniteIntConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteIntConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteIntConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.InfiniteIntConverter.#ctor*
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: InfiniteIntConverter
  nameWithType: InfiniteIntConverter.InfiniteIntConverter
- uid: System.Configuration.InfiniteIntConverter.ConvertFrom*
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: InfiniteIntConverter.ConvertFrom
- uid: System.Configuration.InfiniteIntConverter.ConvertTo*
  parent: System.Configuration.InfiniteIntConverter
  isExternal: false
  name: ConvertTo
  nameWithType: InfiniteIntConverter.ConvertTo
