### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression
  id: IValueSerializableExpression
  children:
  - System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: IValueSerializableExpression
  nameWithType: IValueSerializableExpression
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression
  type: Interface
  summary: "식을 문자열로 변환 하는 방법을 제공 합니다."
  remarks: "활동 식의 약식 텍스트를 제공 하려는 식 작업의 작성자는이 인터페이스를 구현 해야 합니다."
  syntax:
    content: public interface IValueSerializableExpression
  implements: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "식을 문자열로 변환할 수 있는지 여부를 결정 합니다."
  syntax:
    content: public bool CanConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>식을 문자열로; 변환할 수 있는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "식을 문자열로 변환합니다."
  syntax:
    content: public string ConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    return:
      type: System.String
      description: "식의 문자열 표현입니다."
  overload: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString*
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString
  nameWithType: IValueSerializableExpression.CanConvertToString
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString*
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString
  nameWithType: IValueSerializableExpression.ConvertToString
