### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComContractsSection
  id: ComContractsSection
  children:
  - System.ServiceModel.Configuration.ComContractsSection.#ctor
  - System.ServiceModel.Configuration.ComContractsSection.ComContracts
  - System.ServiceModel.Configuration.ComContractsSection.Properties
  langs:
  - csharp
  name: ComContractsSection
  nameWithType: ComContractsSection
  fullName: System.ServiceModel.Configuration.ComContractsSection
  type: Class
  summary: "COM + 통합 계약에 대 한 네임 스페이스 및 계약 이름을 지정 하는 요소를 포함 하는 구성 섹션을 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "COM + 통합 서비스 계약은 현재 &quot;http://tempuri.org&quot; 네임 스페이스로 제한 되며와 계약 이름은 지원 COM 인터페이스에서 파생 됩니다. 그러나 사용 하 여 대안을 지정할 수 있습니다는 `comContracts` 구성 파일의 섹션입니다. 서비스 계약에 대 한 네임 스페이스 및 계약 이름을 지정 하려면 다음 구성을 사용할 수는 예를 들어 [!code-cs [XpsCreate #XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent) ] 서비스가 초기화 될 지정 된 네임 스페이스 및 계약 이름은 생성된 된 서비스 설명에 적용 됩니다.       이 섹션이 비어 있으면 서비스 초기화 지원 COM 인터페이스 ID에서 가져온 기본 네임 스페이스와 계약 이름을 적용합니다"
  syntax:
    content: 'public sealed class ComContractsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: ComContractsSection()
  nameWithType: ComContractsSection.ComContractsSection()
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContractsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.ComContractsSection&quot;> </xref> 클래스입니다."
  syntax:
    content: public ComContractsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComContractsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  id: ComContracts
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "모든 COM + 통합 서비스 계약을에 지정 된을 가져옵니다."
  syntax:
    content: public System.ServiceModel.Configuration.ComContractElementCollection ComContracts { get; }
    return:
      type: System.ServiceModel.Configuration.ComContractElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Configuration.ComContractElementCollection&quot;> </xref> 모든 COM + 통합 서비스 계약에에서 지정 된 들어 있는입니다."
  overload: System.ServiceModel.Configuration.ComContractsSection.ComContracts*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ComContractsSection.Properties
  fullName: System.ServiceModel.Configuration.ComContractsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.ComContractsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContractsSection()
  nameWithType: ComContractsSection.ComContractsSection()
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContractsSection()
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContracts
- uid: System.ServiceModel.Configuration.ComContractElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ComContractElementCollection
  nameWithType: ComContractElementCollection
  fullName: System.ServiceModel.Configuration.ComContractElementCollection
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: Properties
  nameWithType: ComContractsSection.Properties
  fullName: System.ServiceModel.Configuration.ComContractsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContractsSection
  nameWithType: ComContractsSection.ComContractsSection
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: Properties
  nameWithType: ComContractsSection.Properties
