### YamlMime:ManagedReference
items:
- uid: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity
  id: MemoryMappedFileSecurity
  children:
  - System.IO.MemoryMappedFiles.MemoryMappedFileSecurity.#ctor
  langs:
  - csharp
  name: MemoryMappedFileSecurity
  nameWithType: MemoryMappedFileSecurity
  fullName: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity
  type: Class
  summary: "파일 액세스 및 메모리 매핑된 파일에 대 한 작업에 부여할 수 있는 사용 권한을 나타냅니다."
  remarks: "MemoryMappedFileSecurity 클래스에는 메모리 매핑된 파일 및 액세스 시도 감사 하는 방법에 대 한 액세스 권한을 지정 합니다.  이 클래스는 규칙의 집합으로 액세스 및 감사 권한을 나타냅니다.       MemoryMappedFileSecurity 클래스는 기본 Microsoft Windows 파일 보안 시스템 추상화 합니다. 이 시스템에서는 대부분의 Dacl과 Sacl의 세부 정보를 숨깁니다.       검색, 추가 또는 DACL 및 파이프의 SACL을 나타내는 액세스 규칙을 변경 하려면 MemoryMappedFileSecurity 클래스를 사용 합니다.       를 새로 추가 되거나 변경에 대 한 액세스를 적용 하거나 감사 규칙 메모리 매핑된 파일의 <xref:System.IO.MemoryMappedFiles.MemoryMappedFile.SetAccessControl%2A>메서드.</xref:System.IO.MemoryMappedFiles.MemoryMappedFile.SetAccessControl%2A> 액세스 또는 검색 하려면 감사 기존 파일에서 규칙을 사용 하 여는 <xref:System.IO.MemoryMappedFiles.MemoryMappedFile.GetAccessControl%2A>메서드.</xref:System.IO.MemoryMappedFiles.MemoryMappedFile.GetAccessControl%2A>       다음 <xref:System.IO.MemoryMappedFiles.MemoryMappedFile>메서드 MemoryMappedFileSecurity 개체를 매개 변수로 사용:- <xref:System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew%28System.String%2CSystem.Int64%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileAccess%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileOptions%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileSecurity%2CSystem.IO.HandleInheritability%29>- <xref:System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile%28System.IO.FileStream%2CSystem.String%2CSystem.Int64%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileAccess%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileSecurity%2CSystem.IO.HandleInheritability%2CSystem.Boolean%29>- <xref:System.IO.MemoryMappedFiles.MemoryMappedFile.SetAccessControl%28System.IO.MemoryMappedFiles.MemoryMappedFileSecurity%29>- <xref:System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen%28System.String%2CSystem.Int64%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileAccess%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileOptions%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileSecurity%2CSystem.IO.HandleInheritability%29></xref:System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpen%28System.String%2CSystem.Int64%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileAccess%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileOptions%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileSecurity%2CSystem.IO.HandleInheritability%29> </xref:System.IO.MemoryMappedFiles.MemoryMappedFile.SetAccessControl%28System.IO.MemoryMappedFiles.MemoryMappedFileSecurity%29> </xref:System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile%28System.IO.FileStream%2CSystem.String%2CSystem.Int64%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileAccess%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileSecurity%2CSystem.IO.HandleInheritability%2CSystem.Boolean%29> </xref:System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew%28System.String%2CSystem.Int64%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileAccess%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileOptions%2CSystem.IO.MemoryMappedFiles.MemoryMappedFileSecurity%2CSystem.IO.HandleInheritability%29> </xref:System.IO.MemoryMappedFiles.MemoryMappedFile>"
  syntax:
    content: 'public class MemoryMappedFileSecurity : System.Security.AccessControl.ObjectSecurity<System.IO.MemoryMappedFiles.MemoryMappedFileRights>'
  inheritance:
  - System.Object
  - System.Security.AccessControl.ObjectSecurity
  - System.Security.AccessControl.CommonObjectSecurity
  - System.Security.AccessControl.NativeObjectSecurity
  - System.Security.AccessControl.ObjectSecurity`1
  implements: []
  inheritedMembers:
  - System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(System.Security.AccessControl.AccessRule)
  - System.Security.AccessControl.CommonObjectSecurity.AddAuditRule(System.Security.AccessControl.AuditRule)
  - System.Security.AccessControl.CommonObjectSecurity.GetAccessRules(System.Boolean,System.Boolean,System.Type)
  - System.Security.AccessControl.CommonObjectSecurity.GetAuditRules(System.Boolean,System.Boolean,System.Type)
  - System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(System.Security.AccessControl.AccessControlModification,System.Security.AccessControl.AccessRule,System.Boolean@)
  - System.Security.AccessControl.CommonObjectSecurity.ModifyAudit(System.Security.AccessControl.AccessControlModification,System.Security.AccessControl.AuditRule,System.Boolean@)
  - System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRule(System.Security.AccessControl.AccessRule)
  - System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRuleAll(System.Security.AccessControl.AccessRule)
  - System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRuleSpecific(System.Security.AccessControl.AccessRule)
  - System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRule(System.Security.AccessControl.AuditRule)
  - System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRuleAll(System.Security.AccessControl.AuditRule)
  - System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRuleSpecific(System.Security.AccessControl.AuditRule)
  - System.Security.AccessControl.CommonObjectSecurity.ResetAccessRule(System.Security.AccessControl.AccessRule)
  - System.Security.AccessControl.CommonObjectSecurity.SetAccessRule(System.Security.AccessControl.AccessRule)
  - System.Security.AccessControl.CommonObjectSecurity.SetAuditRule(System.Security.AccessControl.AuditRule)
  - System.Security.AccessControl.NativeObjectSecurity.Persist(System.Runtime.InteropServices.SafeHandle,System.Security.AccessControl.AccessControlSections)
  - System.Security.AccessControl.NativeObjectSecurity.Persist(System.Runtime.InteropServices.SafeHandle,System.Security.AccessControl.AccessControlSections,System.Object)
  - System.Security.AccessControl.NativeObjectSecurity.Persist(System.String,System.Security.AccessControl.AccessControlSections)
  - System.Security.AccessControl.NativeObjectSecurity.Persist(System.String,System.Security.AccessControl.AccessControlSections,System.Object)
  - System.Security.AccessControl.ObjectSecurity.AccessRuleFactory(System.Security.Principal.IdentityReference,System.Int32,System.Boolean,System.Security.AccessControl.InheritanceFlags,System.Security.AccessControl.PropagationFlags,System.Security.AccessControl.AccessControlType)
  - System.Security.AccessControl.ObjectSecurity.AccessRulesModified
  - System.Security.AccessControl.ObjectSecurity.AreAccessRulesCanonical
  - System.Security.AccessControl.ObjectSecurity.AreAccessRulesProtected
  - System.Security.AccessControl.ObjectSecurity.AreAuditRulesCanonical
  - System.Security.AccessControl.ObjectSecurity.AreAuditRulesProtected
  - System.Security.AccessControl.ObjectSecurity.AuditRulesModified
  - System.Security.AccessControl.ObjectSecurity.GetGroup(System.Type)
  - System.Security.AccessControl.ObjectSecurity.GetOwner(System.Type)
  - System.Security.AccessControl.ObjectSecurity.GetSecurityDescriptorBinaryForm
  - System.Security.AccessControl.ObjectSecurity.GetSecurityDescriptorSddlForm(System.Security.AccessControl.AccessControlSections)
  - System.Security.AccessControl.ObjectSecurity.GroupModified
  - System.Security.AccessControl.ObjectSecurity.IsContainer
  - System.Security.AccessControl.ObjectSecurity.IsDS
  - System.Security.AccessControl.ObjectSecurity.IsSddlConversionSupported
  - System.Security.AccessControl.ObjectSecurity.ModifyAccessRule(System.Security.AccessControl.AccessControlModification,System.Security.AccessControl.AccessRule,System.Boolean@)
  - System.Security.AccessControl.ObjectSecurity.ModifyAuditRule(System.Security.AccessControl.AccessControlModification,System.Security.AccessControl.AuditRule,System.Boolean@)
  - System.Security.AccessControl.ObjectSecurity.OwnerModified
  - System.Security.AccessControl.ObjectSecurity.Persist(System.Boolean,System.String,System.Security.AccessControl.AccessControlSections)
  - System.Security.AccessControl.ObjectSecurity.PurgeAccessRules(System.Security.Principal.IdentityReference)
  - System.Security.AccessControl.ObjectSecurity.PurgeAuditRules(System.Security.Principal.IdentityReference)
  - System.Security.AccessControl.ObjectSecurity.ReadLock
  - System.Security.AccessControl.ObjectSecurity.ReadUnlock
  - System.Security.AccessControl.ObjectSecurity.SetAccessRuleProtection(System.Boolean,System.Boolean)
  - System.Security.AccessControl.ObjectSecurity.SetAuditRuleProtection(System.Boolean,System.Boolean)
  - System.Security.AccessControl.ObjectSecurity.SetGroup(System.Security.Principal.IdentityReference)
  - System.Security.AccessControl.ObjectSecurity.SetOwner(System.Security.Principal.IdentityReference)
  - System.Security.AccessControl.ObjectSecurity.SetSecurityDescriptorBinaryForm(System.Byte[])
  - System.Security.AccessControl.ObjectSecurity.SetSecurityDescriptorBinaryForm(System.Byte[],System.Security.AccessControl.AccessControlSections)
  - System.Security.AccessControl.ObjectSecurity.SetSecurityDescriptorSddlForm(System.String)
  - System.Security.AccessControl.ObjectSecurity.SetSecurityDescriptorSddlForm(System.String,System.Security.AccessControl.AccessControlSections)
  - System.Security.AccessControl.ObjectSecurity.WriteLock
  - System.Security.AccessControl.ObjectSecurity.WriteUnlock
  - System.Security.AccessControl.ObjectSecurity`1.AccessRightType
  - System.Security.AccessControl.ObjectSecurity`1.AccessRuleFactory(System.Security.Principal.IdentityReference,System.Int32,System.Boolean,System.Security.AccessControl.InheritanceFlags,System.Security.AccessControl.PropagationFlags,System.Security.AccessControl.AccessControl`0ype)
  - System.Security.AccessControl.ObjectSecurity`1.AccessRuleType
  - System.Security.AccessControl.ObjectSecurity`1.AddAccessRule(System.Security.AccessControl.AccessRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.AddAuditRule(System.Security.AccessControl.AuditRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.AuditRuleFactory(System.Security.Principal.IdentityReference,System.Int32,System.Boolean,System.Security.AccessControl.InheritanceFlags,System.Security.AccessControl.PropagationFlags,System.Security.AccessControl.AuditFlags)
  - System.Security.AccessControl.ObjectSecurity`1.AuditRuleType
  - System.Security.AccessControl.ObjectSecurity`1.Persist(System.Runtime.InteropServices.SafeHandle)
  - System.Security.AccessControl.ObjectSecurity`1.Persist(System.String)
  - System.Security.AccessControl.ObjectSecurity`1.RemoveAccessRule(System.Security.AccessControl.AccessRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.RemoveAccessRuleAll(System.Security.AccessControl.AccessRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.RemoveAccessRuleSpecific(System.Security.AccessControl.AccessRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.RemoveAuditRule(System.Security.AccessControl.AuditRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.RemoveAuditRuleAll(System.Security.AccessControl.AuditRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.RemoveAuditRuleSpecific(System.Security.AccessControl.AuditRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.ResetAccessRule(System.Security.AccessControl.AccessRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.SetAccessRule(System.Security.AccessControl.AccessRule`1)
  - System.Security.AccessControl.ObjectSecurity`1.SetAuditRule(System.Security.AccessControl.AuditRule`1)
  platform:
  - net462
- uid: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity.#ctor
  id: '#ctor'
  parent: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity
  langs:
  - csharp
  name: MemoryMappedFileSecurity()
  nameWithType: MemoryMappedFileSecurity.MemoryMappedFileSecurity()
  fullName: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity.MemoryMappedFileSecurity()
  type: Constructor
  assemblies:
  - System.Core
  namespace: System.IO.MemoryMappedFiles
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.IO.MemoryMappedFiles.MemoryMappedFileSecurity&quot;> </xref> 클래스입니다."
  syntax:
    content: public MemoryMappedFileSecurity ();
    parameters: []
  overload: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Security.AccessControl.ObjectSecurity`1
  isExternal: false
  name: System.Security.AccessControl.ObjectSecurity<System.IO.MemoryMappedFiles.MemoryMappedFileRights>
- uid: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity.#ctor
  parent: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity
  isExternal: false
  name: MemoryMappedFileSecurity()
  nameWithType: MemoryMappedFileSecurity.MemoryMappedFileSecurity()
  fullName: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity.MemoryMappedFileSecurity()
- uid: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity.#ctor*
  parent: System.IO.MemoryMappedFiles.MemoryMappedFileSecurity
  isExternal: false
  name: MemoryMappedFileSecurity
  nameWithType: MemoryMappedFileSecurity.MemoryMappedFileSecurity
