### YamlMime:ManagedReference
items:
- uid: System.Xml.Schema.XmlSchemaCompilationSettings
  id: XmlSchemaCompilationSettings
  children:
  - System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  - System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  langs:
  - csharp
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings
  type: Class
  summary: "에 대 한 스키마 컴파일 옵션을 제공 된 <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> 클래스가이 클래스는 상속 될 수 없습니다."
  remarks: "<xref:System.Xml.Schema.XmlSchemaSet>클래스</xref:System.Xml.Schema.XmlSchemaSet> 에 대 한 스키마 컴파일 옵션을 제공 하는 XmlSchemaCompilationSettings 클래스는 예를 들어는 <xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>속성을 지정 하는 <xref:System.Xml.Schema.XmlSchemaSet>Unique Particle Attribution UPA () 위반에 대 한 확인 해야 경우에 포함 된 스키마는 <xref:System.Xml.Schema.XmlSchemaSet>컴파일됩니다.</xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>"
  syntax:
    content: public sealed class XmlSchemaCompilationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  id: '#ctor'
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Xml.Schema.XmlSchemaCompilationSettings&quot;> </xref> 클래스입니다."
  syntax:
    content: public XmlSchemaCompilationSettings ();
    parameters: []
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  id: EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "나타내는 값을 가져오거나 여부는 <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> Unique Particle Attribution UPA () 위반에 대 한 확인 해야 합니다."
  remarks: "EnableUpaCheck 속성이로 설정 되 면 `false`, 유효성 검사는 다음 규칙을 기준으로 수행 됩니다.      1.  강력한 형식 사이의 와일드 카드를 선택 하는 경우는 <xref:System.Xml.Schema.XmlSchemaSet>다음 스키마와 Xml 예제에 설명 된 대로 강력한 형식의 파티클을 선택 합니다.</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:any namespace=&quot;##any&quot;/>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `</xs:sequence>`다음 Xml에는 `A` 요소 연관 될 `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>` 스키마에 있습니다.       `<A>some text</A>`      1.  강력한 형식의 두 요소 사이의 선택 하는 경우는 <xref:System.Xml.Schema.XmlSchemaSet>첫 번째 선택 됩니다.</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot;/>`       `</xs:sequence>`다음 Xml에는 `B` 요소 연관 될 `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>` 스키마에 있습니다.       `<A/>`       `<B/>`"
  syntax:
    content: public bool EnableUpaCheck { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>경우는 <xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;> </xref> 위반 Unique Particle Attribution UPA ();를 확인 하 고, 그러지 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다. 기본값은 <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
