### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  id: SecurityIdentifierElement
  children:
  - System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor
  - System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor(System.Security.Principal.SecurityIdentifier)
  - System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  - System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  langs:
  - csharp
  name: SecurityIdentifierElement
  nameWithType: SecurityIdentifierElement
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  type: Class
  summary: "WCF 서비스를 호스팅하고 공유 서비스에 대 한 연결 액세스를 부여 하는 프로세스에 대 한 사용자 계정을 포함 하는 구성 요소를 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "보안 식별자는 사용자 계정을 식별 하는 데 사용 되는 고유 식별자를 지정 합니다. 기본 값에는 LocalSystem, Administrators, NS, LS 및 IIS_USRS은입니다."
  syntax:
    content: 'public sealed class SecurityIdentifierElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  langs:
  - csharp
  name: SecurityIdentifierElement()
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement()
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Activation.Configuration.SecurityIdentifierElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public SecurityIdentifierElement ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor(System.Security.Principal.SecurityIdentifier)
  id: '#ctor(System.Security.Principal.SecurityIdentifier)'
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  langs:
  - csharp
  name: SecurityIdentifierElement(SecurityIdentifier)
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement(SecurityIdentifier)
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement(SecurityIdentifier)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Activation.Configuration.SecurityIdentifierElement&quot;> </xref> 클래스 wit 지정된 된 보안 식별자입니다."
  syntax:
    content: public SecurityIdentifierElement (System.Security.Principal.SecurityIdentifier sid);
    parameters:
    - id: sid
      type: System.Security.Principal.SecurityIdentifier
      description: "보안 식별자입니다."
  overload: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  id: Properties
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  langs:
  - csharp
  name: Properties
  nameWithType: SecurityIdentifierElement.Properties
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  id: SecurityIdentifier
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  langs:
  - csharp
  name: SecurityIdentifier
  nameWithType: SecurityIdentifierElement.SecurityIdentifier
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "이 요소와 연결 된 보안 식별자를 가져오거나 설정 합니다."
  syntax:
    content: public System.Security.Principal.SecurityIdentifier SecurityIdentifier { get; set; }
    return:
      type: System.Security.Principal.SecurityIdentifier
      description: "이 요소와 연결 된 보안 식별자입니다."
  overload: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifierElement()
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement()
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement()
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor(System.Security.Principal.SecurityIdentifier)
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifierElement(SecurityIdentifier)
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement(SecurityIdentifier)
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement(SecurityIdentifier)
- uid: System.Security.Principal.SecurityIdentifier
  parent: System.Security.Principal
  isExternal: false
  name: SecurityIdentifier
  nameWithType: SecurityIdentifier
  fullName: System.Security.Principal.SecurityIdentifier
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: Properties
  nameWithType: SecurityIdentifierElement.Properties
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifier
  nameWithType: SecurityIdentifierElement.SecurityIdentifier
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor*
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifierElement
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties*
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: Properties
  nameWithType: SecurityIdentifierElement.Properties
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier*
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifier
  nameWithType: SecurityIdentifierElement.SecurityIdentifier
