### YamlMime:ManagedReference
items:
- uid: System.Configuration.LongValidatorAttribute
  id: LongValidatorAttribute
  children:
  - System.Configuration.LongValidatorAttribute.#ctor
  - System.Configuration.LongValidatorAttribute.ExcludeRange
  - System.Configuration.LongValidatorAttribute.MaxValue
  - System.Configuration.LongValidatorAttribute.MinValue
  - System.Configuration.LongValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: LongValidatorAttribute
  nameWithType: LongValidatorAttribute
  fullName: System.Configuration.LongValidatorAttribute
  type: Class
  summary: "구성 속성에 long 정수 유효성 검사를 수행 하려면.NET Framework를 선언적으로 지시 합니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "구성 속성을 데코레이팅합니다 LongValidatorAttribute 특성을 사용 합니다. 이.NET Framework를 사용 하 여 속성의 유효성을 검사 하도록 지시 하려면을 <xref:System.Configuration.LongValidator>개체를 데코레이팅 매개 변수의 값을 전달 합니다.</xref:System.Configuration.LongValidator>       속성 형식에만 LongValidatorAttribute 특성을 적용할 수 있습니다."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the LongValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/t-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/t-system.configuration.l_0_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class LongValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: LongValidatorAttribute()
  nameWithType: LongValidatorAttribute.LongValidatorAttribute()
  fullName: System.Configuration.LongValidatorAttribute.LongValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.LongValidatorAttribute&quot;> </xref> 클래스입니다."
  remarks: "특성 사용 모델에서 관련된 속성에 할당 된 값이 정수 (long) 되도록이 생성자를 사용 합니다."
  syntax:
    content: public LongValidatorAttribute ();
    parameters: []
  overload: System.Configuration.LongValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
  fullName: System.Configuration.LongValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "포함할지으로 정의 된 범위에 있는 정수를 제외할지 여부를 나타내는 값을 가져오거나 설정 합니다.는 <> </> *> 및 <> </> *> 속성 값입니다."
  remarks: "범위는 포함 된 <xref:System.Configuration.LongValidatorAttribute.MinValue%2A>및 <xref:System.Configuration.LongValidatorAttribute.MaxValue%2A>속성 값.</xref:System.Configuration.LongValidatorAttribute.MaxValue%2A> </xref:System.Configuration.LongValidatorAttribute.MinValue%2A> 제외 범위 속성 값이 `false`, 허용 되는 값은 범위를 벗어납니다."
  example:
  - "The following example shows how to use the <xref:System.Configuration.IntegerValidatorAttribute.ExcludeRange%2A> property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_0_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>값을 제외 해야 하는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다. 기본값은 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Configuration.LongValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
  fullName: System.Configuration.LongValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "속성에 대해 허용 되는 최대값을 가져오거나 설정 합니다."
  remarks: "MaxValue 속성 값은 허용 되는 범위에 포함 됩니다."
  example:
  - "The following example shows how to use the MaxValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_1_1.cs)]"
  syntax:
    content: public long MaxValue { get; set; }
    return:
      type: System.Int64
      description: "허용 되는 최대값을 나타내는 정수 (long)입니다."
  overload: System.Configuration.LongValidatorAttribute.MaxValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "선택한 값이 <xref:System.Configuration.LongValidatorAttribute.MinValue*>.</xref:System.Configuration.LongValidatorAttribute.MinValue*> 보다 작은"
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
  fullName: System.Configuration.LongValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "속성에 대해 허용 되는 최소값을 가져오거나 설정 합니다."
  remarks: "MinValue 속성 값은 허용 되는 범위에 포함 됩니다."
  example:
  - "The following example shows how to use the MinValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/visualbasic/p-system.configuration.l_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/csharp/p-system.configuration.l_2_1.cs)]"
  syntax:
    content: public long MinValue { get; set; }
    return:
      type: System.Int64
      description: "허용 되는 최소값을 나타내는 정수입니다."
  overload: System.Configuration.LongValidatorAttribute.MinValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "선택한 값 <xref:System.Configuration.LongValidatorAttribute.MaxValue*>.</xref:System.Configuration.LongValidatorAttribute.MaxValue*> 보다 큽니다."
  platform:
  - net462
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.LongValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "인스턴스를 가져옵니다는 <xref href=&quot;System.Configuration.LongValidator&quot;> </xref> 클래스입니다."
  remarks: "ValidatorInstance 속성 값을 사용 하 여 호출 하 여 문자열 유효성 검사를 수행 하려면 해당 <xref:System.Configuration.LongValidator.Validate%2A>메서드.</xref:System.Configuration.LongValidator.Validate%2A>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "<xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> 유효성 검사기 인스턴스에 있습니다."
  overload: System.Configuration.LongValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.LongValidatorAttribute.#ctor
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: LongValidatorAttribute()
  nameWithType: LongValidatorAttribute.LongValidatorAttribute()
  fullName: System.Configuration.LongValidatorAttribute.LongValidatorAttribute()
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
  fullName: System.Configuration.LongValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.LongValidatorAttribute.MaxValue
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
  fullName: System.Configuration.LongValidatorAttribute.MaxValue
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.LongValidatorAttribute.MinValue
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
  fullName: System.Configuration.LongValidatorAttribute.MinValue
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.LongValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.LongValidatorAttribute.#ctor*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: LongValidatorAttribute
  nameWithType: LongValidatorAttribute.LongValidatorAttribute
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
- uid: System.Configuration.LongValidatorAttribute.MaxValue*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
- uid: System.Configuration.LongValidatorAttribute.MinValue*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
