### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.FtpCachePolicyElement
  id: FtpCachePolicyElement
  children:
  - System.Net.Configuration.FtpCachePolicyElement.#ctor
  - System.Net.Configuration.FtpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Net.Configuration.FtpCachePolicyElement.PolicyLevel
  - System.Net.Configuration.FtpCachePolicyElement.Properties
  - System.Net.Configuration.FtpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: FtpCachePolicyElement
  nameWithType: FtpCachePolicyElement
  fullName: System.Net.Configuration.FtpCachePolicyElement
  type: Class
  summary: "네트워크 리소스에 대 한 기본 FTP 캐시 정책을 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "This class corresponds to the [\\&lt;defaultFtpCachePolicy\\&gt; Element (Network Settings)](../Topic/%3CdefaultFtpCachePolicy%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify the FTP caching configuration that applies to network resources that are obtained by using the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class FtpCachePolicyElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.FtpCachePolicyElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.FtpCachePolicyElement
  langs:
  - csharp
  name: FtpCachePolicyElement()
  nameWithType: FtpCachePolicyElement.FtpCachePolicyElement()
  fullName: System.Net.Configuration.FtpCachePolicyElement.FtpCachePolicyElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Net.Configuration.FtpCachePolicyElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public FtpCachePolicyElement ();
    parameters: []
  overload: System.Net.Configuration.FtpCachePolicyElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.FtpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Net.Configuration.FtpCachePolicyElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: FtpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Net.Configuration.FtpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "추가할 수 있습니다."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.FtpCachePolicyElement.DeserializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.FtpCachePolicyElement.PolicyLevel
  id: PolicyLevel
  parent: System.Net.Configuration.FtpCachePolicyElement
  langs:
  - csharp
  name: PolicyLevel
  nameWithType: FtpCachePolicyElement.PolicyLevel
  fullName: System.Net.Configuration.FtpCachePolicyElement.PolicyLevel
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "FTP 캐싱 로컬 컴퓨터에 대 한 동작을 가져오거나 설정 합니다."
  remarks: "응용 프로그램은 일반적으로 사용 <xref:System.Net.Cache.RequestCacheLevel>캐시 정책 수준으로 됩니다.</xref:System.Net.Cache.RequestCacheLevel> <xref:System.Net.WebRequest.CachePolicy%2A>속성, 그렇지 않으면 `null`, 요청에 대해 적용할 캐시 정책을 결정 합니다.</xref:System.Net.WebRequest.CachePolicy%2A>"
  syntax:
    content: public System.Net.Cache.RequestCacheLevel PolicyLevel { get; set; }
    return:
      type: System.Net.Cache.RequestCacheLevel
      description: "A <xref href=&quot;System.Net.Cache.RequestCacheLevel&quot;> </xref> 캐시 동작을 지정 하는 값입니다."
  overload: System.Net.Configuration.FtpCachePolicyElement.PolicyLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.FtpCachePolicyElement.Properties
  id: Properties
  parent: System.Net.Configuration.FtpCachePolicyElement
  langs:
  - csharp
  name: Properties
  nameWithType: FtpCachePolicyElement.Properties
  fullName: System.Net.Configuration.FtpCachePolicyElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.FtpCachePolicyElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.FtpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.FtpCachePolicyElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: FtpCachePolicyElement.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.FtpCachePolicyElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.FtpCachePolicyElement.Reset*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.FtpCachePolicyElement.#ctor
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: FtpCachePolicyElement()
  nameWithType: FtpCachePolicyElement.FtpCachePolicyElement()
  fullName: System.Net.Configuration.FtpCachePolicyElement.FtpCachePolicyElement()
- uid: System.Net.Configuration.FtpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: FtpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Net.Configuration.FtpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.FtpCachePolicyElement.PolicyLevel
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: PolicyLevel
  nameWithType: FtpCachePolicyElement.PolicyLevel
  fullName: System.Net.Configuration.FtpCachePolicyElement.PolicyLevel
- uid: System.Net.Cache.RequestCacheLevel
  parent: System.Net.Cache
  isExternal: false
  name: RequestCacheLevel
  nameWithType: RequestCacheLevel
  fullName: System.Net.Cache.RequestCacheLevel
- uid: System.Net.Configuration.FtpCachePolicyElement.Properties
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: Properties
  nameWithType: FtpCachePolicyElement.Properties
  fullName: System.Net.Configuration.FtpCachePolicyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.FtpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: FtpCachePolicyElement.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.FtpCachePolicyElement.Reset(ConfigurationElement)
- uid: System.Net.Configuration.FtpCachePolicyElement.#ctor*
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: FtpCachePolicyElement
  nameWithType: FtpCachePolicyElement.FtpCachePolicyElement
- uid: System.Net.Configuration.FtpCachePolicyElement.DeserializeElement*
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: DeserializeElement
  nameWithType: FtpCachePolicyElement.DeserializeElement
- uid: System.Net.Configuration.FtpCachePolicyElement.PolicyLevel*
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: PolicyLevel
  nameWithType: FtpCachePolicyElement.PolicyLevel
- uid: System.Net.Configuration.FtpCachePolicyElement.Properties*
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: Properties
  nameWithType: FtpCachePolicyElement.Properties
- uid: System.Net.Configuration.FtpCachePolicyElement.Reset*
  parent: System.Net.Configuration.FtpCachePolicyElement
  isExternal: false
  name: Reset
  nameWithType: FtpCachePolicyElement.Reset
