### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpCachePolicyElement
  id: HttpCachePolicyElement
  children:
  - System.Net.Configuration.HttpCachePolicyElement.#ctor
  - System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  - System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  - System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  - System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  - System.Net.Configuration.HttpCachePolicyElement.Properties
  - System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: HttpCachePolicyElement
  nameWithType: HttpCachePolicyElement
  fullName: System.Net.Configuration.HttpCachePolicyElement
  type: Class
  summary: "네트워크 리소스에 대 한 기본 HTTP 캐시 정책을 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "This class corresponds to the [\\&lt;defaultHttpCachePolicy\\&gt; Element (Network Settings)](../Topic/%3CdefaultHttpCachePolicy%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify the HTTP caching configuration that applies to network resources obtained by using the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class HttpCachePolicyElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: HttpCachePolicyElement()
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement()
  fullName: System.Net.Configuration.HttpCachePolicyElement.HttpCachePolicyElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Net.Configuration.HttpCachePolicyElement&quot;> </xref> 클래스입니다."
  remarks: "추가 하는이 생성자는 <xref:System.Net.Configuration.HttpCachePolicyElement.MaximumAge%2A>, <xref:System.Net.Configuration.HttpCachePolicyElement.MaximumStale%2A>, <xref:System.Net.Configuration.HttpCachePolicyElement.MinimumFresh%2A>, 및 <xref:System.Net.Configuration.HttpCachePolicyElement.PolicyLevel%2A>속성 컬렉션을.</xref:System.Net.Configuration.HttpCachePolicyElement.PolicyLevel%2A> </xref:System.Net.Configuration.HttpCachePolicyElement.MinimumFresh%2A> </xref:System.Net.Configuration.HttpCachePolicyElement.MaximumStale%2A> </xref:System.Net.Configuration.HttpCachePolicyElement.MaximumAge%2A>"
  syntax:
    content: public HttpCachePolicyElement ();
    parameters: []
  overload: System.Net.Configuration.HttpCachePolicyElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "추가할 수 있습니다."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  id: MaximumAge
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "캐시에서 반환 되는 리소스에 대해 허용 되는 최대 기간을 가져오거나 설정 합니다."
  remarks: "리소스의 캐시 된 복사본을 지정된 된 시간 값 보다 오래 된 경우 서버에서 리소스에 캐시 된 리소스를 비교 하 여 리소스를 다시 검사 해야 합니다."
  syntax:
    content: public TimeSpan MaximumAge { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>값에 대 한 최대 기간을 지정 하는 캐시 구성 파일에 리소스를 지정 합니다.</xref:System.TimeSpan>"
  overload: System.Net.Configuration.HttpCachePolicyElement.MaximumAge*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  id: MaximumStale
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "캐시에서 반환 되는 리소스에 허용 된 최대 부실 값을 가져오거나 설정 합니다."
  remarks: "이 속성에는 리소스의 캐시 된 복사본은 허용 되는 콘텐츠 만료 된 후 시간의 양을 지정 합니다."
  syntax:
    content: public TimeSpan MaximumStale { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>구성 파일에 지정 된 최대 부실 값으로 설정 된 값.</xref:System.TimeSpan>"
  overload: System.Net.Configuration.HttpCachePolicyElement.MaximumStale*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  id: MinimumFresh
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
  fullName: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "캐시에서 반환 되는 리소스에 허용 된 최소 새로 고침을 가져오거나 설정 합니다."
  remarks: "이 값이 리소스의 캐시 된 복사본은 허용 되는 콘텐츠 만료 전에 시간을 지정 합니다."
  syntax:
    content: public TimeSpan MinimumFresh { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>구성 파일에 지정 된 최소 새로 고침을 지정 하는 값입니다.</xref:System.TimeSpan>"
  overload: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  id: PolicyLevel
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
  fullName: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "HTTP 캐싱 로컬 컴퓨터에 대 한 동작을 가져오거나 설정 합니다."
  remarks: "응용 프로그램은 일반적으로 사용 <xref:System.Net.Cache.HttpRequestCacheLevel>캐시 정책 수준으로 됩니다.</xref:System.Net.Cache.HttpRequestCacheLevel> <xref:System.Net.WebRequest.CachePolicy%2A>속성, 그렇지 않으면 `null`, 요청에 대해 적용할 캐시 정책을 결정 합니다.</xref:System.Net.WebRequest.CachePolicy%2A>"
  syntax:
    content: public System.Net.Cache.HttpRequestCacheLevel PolicyLevel { get; set; }
    return:
      type: System.Net.Cache.HttpRequestCacheLevel
      description: "A <xref href=&quot;System.Net.Cache.HttpRequestCacheLevel&quot;> </xref> 캐시 동작을 지정 하는 값입니다."
  overload: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
  fullName: System.Net.Configuration.HttpCachePolicyElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.HttpCachePolicyElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: HttpCachePolicyElement.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.HttpCachePolicyElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.HttpCachePolicyElement.Reset*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: HttpCachePolicyElement()
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement()
  fullName: System.Net.Configuration.HttpCachePolicyElement.HttpCachePolicyElement()
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
  fullName: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
  fullName: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
- uid: System.Net.Cache.HttpRequestCacheLevel
  parent: System.Net.Cache
  isExternal: false
  name: HttpRequestCacheLevel
  nameWithType: HttpRequestCacheLevel
  fullName: System.Net.Cache.HttpRequestCacheLevel
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
  fullName: System.Net.Configuration.HttpCachePolicyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: HttpCachePolicyElement.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.HttpCachePolicyElement.Reset(ConfigurationElement)
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: HttpCachePolicyElement
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: DeserializeElement
  nameWithType: HttpCachePolicyElement.DeserializeElement
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Reset
  nameWithType: HttpCachePolicyElement.Reset
