### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Converters.GeometryValueSerializer
  id: GeometryValueSerializer
  children:
  - System.Windows.Media.Converters.GeometryValueSerializer.#ctor
  - System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: GeometryValueSerializer
  nameWithType: GeometryValueSerializer
  fullName: System.Windows.Media.Converters.GeometryValueSerializer
  type: Class
  summary: "인스턴스를 변환 <xref:System.String>의 인스턴스 간에 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref>.</xref:System.String>"
  remarks: "이 클래스는 일반적으로 사용 하 여는 <xref:System.Windows.Markup.Primitives.MarkupWriter>serialization 위해.</xref:System.Windows.Markup.Primitives.MarkupWriter>"
  syntax:
    content: 'public class GeometryValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: GeometryValueSerializer()
  nameWithType: GeometryValueSerializer.GeometryValueSerializer()
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.GeometryValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Windows.Media.Converters.GeometryValueSerializer&quot;> </xref> 클래스입니다."
  syntax:
    content: public GeometryValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Converters.GeometryValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "있는지 여부를 확인에서 변환 된 주어진 <xref:System.String>의 인스턴스로 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> 수.</xref:System.String>"
  remarks: "이 메서드는 항상 반환 `true`합니다."
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "변환을 위해 평가할 문자열입니다."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>값을 변환할 수 있으면 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "인스턴스를 결정 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> <xref:System.String>.</xref:System.String> 로 변환할 수"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "인스턴스 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> 변환을 위해 평가할 수 있습니다."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>경우 <code> value </code> 으로 변환할 수는 <xref:System.String>, 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Occurs when <code>value</code> is not a <xref href=&quot;System.Windows.Media.Geometry&quot;></xref>."
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "변환 된 <xref:System.String>에 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "<xref:System.String>값으로 변환 하는 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref>합니다.</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    return:
      type: System.Object
      description: "새 인스턴스 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> 제공 된 기준 <code> value </code>합니다."
  overload: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "인스턴스를 변환 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "인스턴스 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> 변환을 위해 평가할 수 있습니다."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "변환에 사용 되는 컨텍스트 정보입니다."
    return:
      type: System.String
      description: "A <xref:System.String>표현을 제공 된 <xref href=&quot;System.Windows.Media.Geometry&quot;> </xref> 개체입니다.</xref:System.String>"
  overload: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Windows.Media.Converters.GeometryValueSerializer.#ctor
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: GeometryValueSerializer()
  nameWithType: GeometryValueSerializer.GeometryValueSerializer()
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.GeometryValueSerializer()
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: GeometryValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Converters.GeometryValueSerializer.#ctor*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: GeometryValueSerializer
  nameWithType: GeometryValueSerializer.GeometryValueSerializer
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: GeometryValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Converters.GeometryValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: GeometryValueSerializer.CanConvertToString
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: GeometryValueSerializer.ConvertFromString
- uid: System.Windows.Media.Converters.GeometryValueSerializer.ConvertToString*
  parent: System.Windows.Media.Converters.GeometryValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: GeometryValueSerializer.ConvertToString
