### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ProxyElement
  id: ProxyElement
  children:
  - System.Net.Configuration.ProxyElement.#ctor
  - System.Net.Configuration.ProxyElement.AutoDetect
  - System.Net.Configuration.ProxyElement.BypassOnLocal
  - System.Net.Configuration.ProxyElement.Properties
  - System.Net.Configuration.ProxyElement.ProxyAddress
  - System.Net.Configuration.ProxyElement.ScriptLocation
  - System.Net.Configuration.ProxyElement.UseSystemDefault
  langs:
  - csharp
  name: ProxyElement
  nameWithType: ProxyElement
  fullName: System.Net.Configuration.ProxyElement
  type: Class
  summary: "웹 프록시 서버에 대 한 구성 설정을 식별합니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "The following table shows the configuration attributes of the [\\&lt;proxy\\&gt; Element (Network Settings)](../Topic/%3Cproxy%3E%20Element%20\\(Network%20Settings\\).md) configuration element to which this class corresponds.  \n  \n|Element|Description|  \n|-------------|-----------------|  \n|`proxyaddress`|A URI that identifies the Web proxy server to use.|  \n|`bypassonlocal`|Determines whether the Web proxy is bypassed for local resources.|  \n|`usesystemdefault`|Controls whether the Internet Explorer Web proxy settings are used.|  \n|`useDefaultCredentialsForScriptDownload`|Controls whether default credentials are used when accessing the configuration script.|  \n|`scriptDownloadInterval`|Specifies the number of seconds that elapse before the configuration script is refreshed.|  \n|`scriptDownloadTimeout`|Specifies the number of seconds allowed for the configuration script to be downloaded.|  \n|`useDefaultCredentials`|Controls whether default credentials are used when accessing the Web proxy.|  \n  \n This class is used to specify and configure the Web proxy server to use for requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ProxyElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ProxyElement()
  nameWithType: ProxyElement.ProxyElement()
  fullName: System.Net.Configuration.ProxyElement.ProxyElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Net.Configuration.ProxyElement&quot;> </xref> 클래스입니다."
  remarks: '-'
  syntax:
    content: public ProxyElement ();
    parameters: []
  overload: System.Net.Configuration.ProxyElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.AutoDetect
  id: AutoDetect
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: AutoDetect
  nameWithType: ProxyElement.AutoDetect
  fullName: System.Net.Configuration.ProxyElement.AutoDetect
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "가져오거나는 <xref:System.Net.Configuration.ProxyElement.AutoDetectValues>웹 프록시를 자동으로 검색할지 여부를 제어 하 값.</xref:System.Net.Configuration.ProxyElement.AutoDetectValues>"
  syntax:
    content: public System.Net.Configuration.ProxyElement.AutoDetectValues AutoDetect { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.AutoDetectValues
      description: "<xref:System.Net.Configuration.ProxyElement.AutoDetectValues>경우는 <xref href=&quot;System.Net.WebProxy&quot;> </xref> 자동으로 검색 됩니다. <xref:System.Net.Configuration.ProxyElement.AutoDetectValues>경우는 <xref href=&quot;System.Net.WebProxy&quot;> </xref> 은 자동으로 검색 되지 않으면 나 <xref:System.Net.Configuration.ProxyElement.AutoDetectValues>.</xref:System.Net.Configuration.ProxyElement.AutoDetectValues> </xref:System.Net.Configuration.ProxyElement.AutoDetectValues></xref:System.Net.Configuration.ProxyElement.AutoDetectValues>"
  overload: System.Net.Configuration.ProxyElement.AutoDetect*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.BypassOnLocal
  id: BypassOnLocal
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: BypassOnLocal
  nameWithType: ProxyElement.BypassOnLocal
  fullName: System.Net.Configuration.ProxyElement.BypassOnLocal
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "웹 프록시 서버를 사용 하 여 로컬 리소스 검색 되는지 여부를 나타내는 값을 가져오거나 설정 합니다."
  remarks: "이 구성 요소에는 LAN에 있는 리소스에 대 한 요청이 프록시 서버에 발신 이나 리소스가 있는 호스트에 직접 전송 여부를 제어 합니다."
  syntax:
    content: public System.Net.Configuration.ProxyElement.BypassOnLocalValues BypassOnLocal { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.BypassOnLocalValues
      description: "A <xref:System.Net.Configuration.ProxyElement.BypassOnLocalValues>.</xref:System.Net.Configuration.ProxyElement.BypassOnLocalValues>       웹 프록시 서버를 사용 하 여 로컬 리소스 검색 되는지 여부를 나타내는 값을 선택 합니다."
  overload: System.Net.Configuration.ProxyElement.BypassOnLocal*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.Properties
  id: Properties
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProxyElement.Properties
  fullName: System.Net.Configuration.ProxyElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Net.Configuration.ProxyElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.ProxyAddress
  id: ProxyAddress
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ProxyAddress
  nameWithType: ProxyElement.ProxyAddress
  fullName: System.Net.Configuration.ProxyElement.ProxyAddress
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "사용 하도록 웹 프록시 서버를 식별 하는 URI를 가져오거나 설정 합니다."
  syntax:
    content: public Uri ProxyAddress { get; set; }
    return:
      type: System.Uri
      description: "A <xref:System.String>URI가 포함 된.</xref:System.String>"
  overload: System.Net.Configuration.ProxyElement.ProxyAddress*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.ScriptLocation
  id: ScriptLocation
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ScriptLocation
  nameWithType: ProxyElement.ScriptLocation
  fullName: System.Net.Configuration.ProxyElement.ScriptLocation
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "가져오거나는 <xref:System.Uri>프록시 자동 검색의 위치를 지정 하는 값 스크립트</xref:System.Uri>"
  syntax:
    content: public Uri ScriptLocation { get; set; }
    return:
      type: System.Uri
      description: "A <xref:System.Uri>프록시 자동 검색의 위치 지정 스크립트로</xref:System.Uri>"
  overload: System.Net.Configuration.ProxyElement.ScriptLocation*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.UseSystemDefault
  id: UseSystemDefault
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: UseSystemDefault
  nameWithType: ProxyElement.UseSystemDefault
  fullName: System.Net.Configuration.ProxyElement.UseSystemDefault
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "가져오거나는 <xref:System.Boolean>Internet Explorer 웹 프록시 설정이 사용 되는지 여부를 제어 하 값.</xref:System.Boolean>"
  syntax:
    content: public System.Net.Configuration.ProxyElement.UseSystemDefaultValues UseSystemDefault { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.UseSystemDefaultValues
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Internet Explorer LAN 설정 검색 하 고 기본 구성에 익숙한 경우 <xref href=&quot;System.Net.WebProxy&quot;> </xref> 요청에 사용 되 고, 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Net.Configuration.ProxyElement.UseSystemDefault*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ProxyElement.#ctor
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyElement()
  nameWithType: ProxyElement.ProxyElement()
  fullName: System.Net.Configuration.ProxyElement.ProxyElement()
- uid: System.Net.Configuration.ProxyElement.AutoDetect
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: AutoDetect
  nameWithType: ProxyElement.AutoDetect
  fullName: System.Net.Configuration.ProxyElement.AutoDetect
- uid: System.Net.Configuration.ProxyElement.AutoDetectValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+AutoDetectValues
  nameWithType: ProxyElement+AutoDetectValues
  fullName: System.Net.Configuration.ProxyElement+AutoDetectValues
- uid: System.Net.Configuration.ProxyElement.BypassOnLocal
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: BypassOnLocal
  nameWithType: ProxyElement.BypassOnLocal
  fullName: System.Net.Configuration.ProxyElement.BypassOnLocal
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+BypassOnLocalValues
  nameWithType: ProxyElement+BypassOnLocalValues
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues
- uid: System.Net.Configuration.ProxyElement.Properties
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: Properties
  nameWithType: ProxyElement.Properties
  fullName: System.Net.Configuration.ProxyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ProxyElement.ProxyAddress
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyAddress
  nameWithType: ProxyElement.ProxyAddress
  fullName: System.Net.Configuration.ProxyElement.ProxyAddress
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Net.Configuration.ProxyElement.ScriptLocation
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ScriptLocation
  nameWithType: ProxyElement.ScriptLocation
  fullName: System.Net.Configuration.ProxyElement.ScriptLocation
- uid: System.Net.Configuration.ProxyElement.UseSystemDefault
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: UseSystemDefault
  nameWithType: ProxyElement.UseSystemDefault
  fullName: System.Net.Configuration.ProxyElement.UseSystemDefault
- uid: System.Net.Configuration.ProxyElement.UseSystemDefaultValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+UseSystemDefaultValues
  nameWithType: ProxyElement+UseSystemDefaultValues
  fullName: System.Net.Configuration.ProxyElement+UseSystemDefaultValues
- uid: System.Net.Configuration.ProxyElement.#ctor*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyElement
  nameWithType: ProxyElement.ProxyElement
- uid: System.Net.Configuration.ProxyElement.AutoDetect*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: AutoDetect
  nameWithType: ProxyElement.AutoDetect
- uid: System.Net.Configuration.ProxyElement.BypassOnLocal*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: BypassOnLocal
  nameWithType: ProxyElement.BypassOnLocal
- uid: System.Net.Configuration.ProxyElement.Properties*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: Properties
  nameWithType: ProxyElement.Properties
- uid: System.Net.Configuration.ProxyElement.ProxyAddress*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyAddress
  nameWithType: ProxyElement.ProxyAddress
- uid: System.Net.Configuration.ProxyElement.ScriptLocation*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ScriptLocation
  nameWithType: ProxyElement.ScriptLocation
- uid: System.Net.Configuration.ProxyElement.UseSystemDefault*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: UseSystemDefault
  nameWithType: ProxyElement.UseSystemDefault
