### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.UrlMapping
  id: UrlMapping
  children:
  - System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  - System.Web.Configuration.UrlMapping.MappedUrl
  - System.Web.Configuration.UrlMapping.Properties
  - System.Web.Configuration.UrlMapping.Url
  langs:
  - csharp
  name: UrlMapping
  nameWithType: UrlMapping
  fullName: System.Web.Configuration.UrlMapping
  type: Class
  summary: "웹 응용 프로그램에서 페이지의 URL 사용자에 게 표시 되는 URL을 매핑합니다. 이 클래스는 상속 될 수 없습니다."
  remarks: "UrlMapping 클래스를 사용 하면 웹 응용 프로그램에 존재 하는 URL로 사용자에 게 표시 되는 URL을 매핑할 수 있습니다. UrlMapping 개체를 추가 <xref:System.Web.Configuration.UrlMappingCollection>포함 파일에 해당 하는 프로그래밍 방식으로 `add` 요소에는 `urlMappings` 구성 파일의 섹션.</xref:System.Web.Configuration.UrlMappingCollection>       각 UrlMapping 개체는 URL을 식별 하는 두 개의 속성을 포함 합니다. 속성 하나; 사용자에 게 표시 URL을 지정 합니다. 다른 웹 응용 프로그램에서 URL을 지정합니다. 후행 공백 문자는 모두 무시 됩니다는 <xref:System.Web.Configuration.UrlMapping.Url%2A>및 <xref:System.Web.Configuration.UrlMapping.MappedUrl%2A>속성.</xref:System.Web.Configuration.UrlMapping.MappedUrl%2A> </xref:System.Web.Configuration.UrlMapping.Url%2A>      > [!NOTE] > The UrlMapping 속성의 <xref:System.Configuration.SectionInformation.AllowDefinition%2A>값은 <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> 섹션 속성은에 정의 된 제한에 따라 구성 파일의 관련된 섹션에 정보를 쓸 수 데이터를 계층 구조에서 사용할 수 없습니다 수준에서 구성 파일에 쓸 파서에서 생성 하는 오류가 발생 합니다. 그러나 계층의 모든 수준에서 구성 정보를 읽을이 클래스를 사용할 수 있습니다."
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/csharp/t-system.web.configurati_10_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/visualbasic/t-system.web.configurati_10_2.aspx)]"
  syntax:
    content: 'public sealed class UrlMapping : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Web.Configuration.UrlMapping&quot;> </xref> 클래스입니다."
  remarks: "ASP.NET UrlMapping 생성자는 내부 사용을 위한 것입니다. 이 클래스에서 파생 해야 하 고 코드에서 사용 하지 않을 할 Web.config 파일을 수정 하는 사용할 수 있습니다, 때문에 합니다."
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/csharp/m-system.web.configurati_60_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/visualbasic/m-system.web.configurati_60_2.aspx)]"
  syntax:
    content: public UrlMapping (string url, string mappedUrl);
    parameters:
    - id: url
      type: System.String
      description: "사용자에 게 표시할 URL입니다."
    - id: mappedUrl
      type: System.String
      description: "웹 응용 프로그램에 존재 하는 URL입니다."
  overload: System.Web.Configuration.UrlMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  id: MappedUrl
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "웹 응용 프로그램의 URL입니다."
  remarks: "MappedUrl 속성은 해당 하는 프로그래밍 방식으로 `mappedUrl` 특성에는 `add` 요소에는 `urlMappings` 구성 파일의 섹션입니다.      > [!NOTE] > IIS 5.0에서 지원 되지 않는 페이지 형식 (예:.asp 페이지)는 지원 되는 페이지 형식 (예:.aspx 파일)에서 매핑할 MappedUrl 속성을 사용 하는 경우를 사용할 때 오류가 발생 합니다. 이러한 유형의 매핑은 IIS 버전 6.0에서에서 지원 됩니다."
  example:
  - "The following code example shows how to obtain the MappedUrl property. This example is from a larger example for the <xref:System.Web.Configuration.UrlMapping> class.  \n  \n [!code-cs[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/csharp/p-system.web.configurati_113_1.aspx)]\n [!code-vb[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/visualbasic/p-system.web.configurati_113_1.aspx)]"
  syntax:
    content: public string MappedUrl { get; }
    return:
      type: System.String
      description: "에 지정 된 값에 매핑되지 않았습니다. 웹 응용 프로그램에서 URL의 <xref:System.Web.Configuration.UrlMapping.Url*>속성.</xref:System.Web.Configuration.UrlMapping.Url*>"
  overload: System.Web.Configuration.UrlMapping.MappedUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.Properties
  id: Properties
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Web.Configuration.UrlMapping.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.Url
  id: Url
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "사용자에 게 표시 되는 URL을 가져옵니다."
  remarks: "Url 속성은 해당 하는 프로그래밍 방식으로 `Url` 특성에는 `add` 요소에는 `urlMappings` 구성 파일의 섹션입니다."
  example:
  - For an example, see the <xref:System.Web.Configuration.UrlMapping> class overview.
  syntax:
    content: public string Url { get; }
    return:
      type: System.String
      description: "사용자에 게 표시 되는 URL입니다."
  overload: System.Web.Configuration.UrlMapping.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.UrlMapping.Url
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
- uid: System.Web.Configuration.UrlMapping.#ctor*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping
  nameWithType: UrlMapping.UrlMapping
- uid: System.Web.Configuration.UrlMapping.MappedUrl*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
- uid: System.Web.Configuration.UrlMapping.Url*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
