### YamlMime:ManagedReference
items:
- uid: System.Web.Compilation.AppSettingsExpressionBuilder
  id: AppSettingsExpressionBuilder
  children:
  - System.Web.Compilation.AppSettingsExpressionBuilder.#ctor
  - System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression(System.Object,System.Web.UI.BoundPropertyEntry,System.Object,System.Web.Compilation.ExpressionBuilderContext)
  - System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(System.String)
  - System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(System.String,System.Type,System.String)
  - System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression(System.Web.UI.BoundPropertyEntry,System.Object,System.Web.Compilation.ExpressionBuilderContext)
  - System.Web.Compilation.AppSettingsExpressionBuilder.SupportsEvaluate
  langs:
  - csharp
  name: AppSettingsExpressionBuilder
  nameWithType: AppSettingsExpressionBuilder
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder
  type: Class
  summary: "선언적 식에 지정 된 대로 값을 검색 된 <xref uid=&quot;langword_csharp_&lt;appSettings&gt;&quot; name=&quot;&lt;appSettings&gt;&quot; href=&quot;&quot;> </xref> Web.config 파일의 섹션입니다."
  remarks: "AppSettingsExpressionBuilder 클래스의 값에 액세스할 수는 `<appSettings>` Web.config 파일의 섹션입니다. `<appSettings>` Web.config 파일의 섹션에 키/값 쌍의 응용 프로그램별 값이 포함 되어 있습니다.       폼의 식을 배치 하 여 검색 되는 응용 프로그램 값 `<%$ AppSettings: appSettingsKey %>` 속성 컨트롤 선언에 있습니다. 콜론 의미 키 후 콜론 (:)의 일부 검색 되는 식과 파트의 종류를 지정 합니다. 이전 식에서 Web.config 파일에서 다음 값을 검색 합니다.       `<appSettings>`       `<add key=&quot;appSettingsKey&quot; value=&quot;appSettingsValue&quot;/>`       `</appSettings>`페이지 나타나면 수 없는 식으로는 `AppSettings` 는 식을 처리 하기 위한 AppSettingsExpressionBuilder 클래스의 인스턴스를 만들고 접두사입니다.       컴파일되는 페이지에는 식에 오류가 발생 하면 AppSettingsExpressionBuilder 개체 Web.config 파일에서 지정된 된 값을 검색 하는 코드를 생성 합니다. 이 코드는 생성된 된 페이지 클래스를 실행 하는 동안 실행 됩니다. 식을 컴파일하지 않을 하는 페이지에서 발생 하는 경우 페이지를 구문 분석 하 고 실행할 때 AppSettingsExpressionBuilder 개체 Web.config 파일에서 값을 반환 합니다."
  example:
  - "The following code example demonstrates how to retrieve an application settings value in a page that is not compiled.  \n  \n [!code-vb[System.Web.Compilation.AppSettingsExpressionBuilder#1](~/add/codesnippet/visualbasic/t-system.web.compilation_6_1.aspx)]\n [!code-cs[System.Web.Compilation.AppSettingsExpressionBuilder#1](~/add/codesnippet/csharp/t-system.web.compilation_6_1.aspx)]  \n  \n This code retrieves the following expression from the Web.config file.  \n  \n `<configuration xmlns=\"http://schemas.microsoft.com/.NetConfiguration/v2.0\">`  \n  \n `<appSettings>`  \n  \n `<add key=\"thisSeason\" value=\"Fall\"/>`  \n  \n `</appSettings>`  \n  \n `</configuration>`"
  syntax:
    content: >-
      [System.Web.Compilation.ExpressionEditor("System.Web.UI.Design.AppSettingsExpressionEditor, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]

      [System.Web.Compilation.ExpressionPrefix("AppSettings")]

      public class AppSettingsExpressionBuilder : System.Web.Compilation.ExpressionBuilder
  inheritance:
  - System.Object
  - System.Web.Compilation.ExpressionBuilder
  implements: []
  inheritedMembers:
  - System.Web.Compilation.ExpressionBuilder.ParseExpression(System.String,System.Type,System.Web.Compilation.ExpressionBuilderContext)
  platform:
  - net462
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.#ctor
  id: '#ctor'
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  langs:
  - csharp
  name: AppSettingsExpressionBuilder()
  nameWithType: AppSettingsExpressionBuilder.AppSettingsExpressionBuilder()
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.AppSettingsExpressionBuilder()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Compilation
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Web.Compilation.AppSettingsExpressionBuilder&quot;> </xref> 클래스입니다."
  syntax:
    content: public AppSettingsExpressionBuilder ();
    parameters: []
  overload: System.Web.Compilation.AppSettingsExpressionBuilder.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression(System.Object,System.Web.UI.BoundPropertyEntry,System.Object,System.Web.Compilation.ExpressionBuilderContext)
  id: EvaluateExpression(System.Object,System.Web.UI.BoundPropertyEntry,System.Object,System.Web.Compilation.ExpressionBuilderContext)
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  langs:
  - csharp
  name: EvaluateExpression(Object,BoundPropertyEntry,Object,ExpressionBuilderContext)
  nameWithType: AppSettingsExpressionBuilder.EvaluateExpression(Object,BoundPropertyEntry,Object,ExpressionBuilderContext)
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression(Object,BoundPropertyEntry,Object,ExpressionBuilderContext)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Compilation
  summary: "값을 반환 된 <xref uid=&quot;langword_csharp_&lt;appSettings&gt;&quot; name=&quot;&lt;appSettings&gt;&quot; href=&quot;&quot;> </xref> Web.config 파일의 섹션입니다."
  remarks: '이 메서드는 폼의 식을 `<%$ AppSettings: someApplicationSetting %>` 컴파일되지 않은 페이지에 발생 합니다. 키/값 쌍에 적절 한 값을 검색 하는 것은 `<appSettings>` Web.config 파일의 섹션입니다. 이 메서드를 재정의 <xref:System.Web.Compilation.ExpressionBuilder.EvaluateExpression%2A>호출 하 여는 <xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting%2A>사용 하 여 메서드는 <xref:System.Web.UI.BoundPropertyEntry.Expression%2A>속성으로는 `key` 매개 변수를는 <xref:System.Web.UI.PropertyEntry.Name%2A>속성에는 <xref:System.Web.UI.PropertyEntry.PropertyInfo%2A?displayProperty=fullName>속성으로는 `propertyName` 매개 변수를 및 <xref:System.Type>의 `target` 으로 매개 변수는 `targetType` 매개 변수.</xref:System.Type> </xref:System.Web.UI.PropertyEntry.PropertyInfo%2A?displayProperty=fullName> </xref:System.Web.UI.PropertyEntry.Name%2A> </xref:System.Web.UI.BoundPropertyEntry.Expression%2A> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting%2A> </xref:System.Web.Compilation.ExpressionBuilder.EvaluateExpression%2A>'
  syntax:
    content: public override object EvaluateExpression (object target, System.Web.UI.BoundPropertyEntry entry, object parsedData, System.Web.Compilation.ExpressionBuilderContext context);
    parameters:
    - id: target
      type: System.Object
      description: "속성 항목을 포함 하는 개체입니다."
    - id: entry
      type: System.Web.UI.BoundPropertyEntry
      description: "식은 연결 된 속성..."
    - id: parsedData
      type: System.Object
      description: "나타내는 <xref:System.Web.Compilation.ExpressionBuilder.ParseExpression*>.</xref:System.Web.Compilation.ExpressionBuilder.ParseExpression*> 에서 반환 된 데이터를 구문 분석"
    - id: context
      type: System.Web.Compilation.ExpressionBuilderContext
      description: "컨트롤 또는 페이지에 대 한 속성입니다."
    return:
      type: System.Object
      description: "<xref:System.Object>에 키와 연결 된는 <xref uid=&quot;langword_csharp_&lt;appSettings&gt;&quot; name=&quot;&lt;appSettings&gt;&quot; href=&quot;&quot;> </xref> Web.config 파일의 섹션.</xref:System.Object>"
  overload: System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(System.String)
  id: GetAppSetting(System.String)
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  langs:
  - csharp
  name: GetAppSetting(String)
  nameWithType: AppSettingsExpressionBuilder.GetAppSetting(String)
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Compilation
  summary: "값을 반환 된 <xref uid=&quot;langword_csharp_&lt;appSettings&gt;&quot; name=&quot;&lt;appSettings&gt;&quot; href=&quot;&quot;> </xref> Web.config 파일의 섹션입니다."
  remarks: "키/값 쌍에 해당 값을 검색 하는이 메서드는 `<appSettings>` Web.config 파일의 섹션입니다. 값을 가져와서 검색는 <xref:System.Configuration.ConfigurationManager.AppSettings%2A>인덱스와 키를 사용 하 여 속성.</xref:System.Configuration.ConfigurationManager.AppSettings%2A> <xref:System.Object>반환 되는 형식 <xref:System.String>.</xref:System.String> </xref:System.Object>"
  syntax:
    content: public static object GetAppSetting (string key);
    parameters:
    - id: key
      type: System.String
      description: "구성 파일에서 검색할 값에 대 한 키입니다."
    return:
      type: System.Object
      description: "<xref:System.Object>에 키와 연결 된는 <xref uid=&quot;langword_csharp_&lt;appSettings&gt;&quot; name=&quot;&lt;appSettings&gt;&quot; href=&quot;&quot;> </xref> Web.config 파일의 섹션.</xref:System.Object>"
  overload: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Web.config에서이 키를 찾을 수 없습니다."
  platform:
  - net462
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(System.String,System.Type,System.String)
  id: GetAppSetting(System.String,System.Type,System.String)
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  langs:
  - csharp
  name: GetAppSetting(String,Type,String)
  nameWithType: AppSettingsExpressionBuilder.GetAppSetting(String,Type,String)
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(String,Type,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Compilation
  summary: "값을 반환 된 <xref uid=&quot;langword_csharp_&lt;appSettings&gt;&quot; name=&quot;&lt;appSettings&gt;&quot; href=&quot;&quot;> </xref> 값 사용 Web.config 파일의 대상 형식으로 변환 합니다."
  remarks: "키/값 쌍에 해당 값을 검색 하는이 메서드는 `<appSettings>` Web.config 파일의 섹션입니다. 값을 가져와서 검색 되는 <xref:System.Configuration.ConfigurationManager.AppSettings%2A>인덱스와 키를 가진 속성입니다.</xref:System.Configuration.ConfigurationManager.AppSettings%2A> 결과 문자열 값에 따라 새 형식으로 변환 되는 `targetType` 및 `propertyName` 매개 변수입니다."
  syntax:
    content: public static object GetAppSetting (string key, Type targetType, string propertyName);
    parameters:
    - id: key
      type: System.String
      description: "구성 파일에서 검색할 값에 대 한 키입니다."
    - id: targetType
      type: System.Type
      description: "속성 항목을 포함 하는 개체의 형식입니다."
    - id: propertyName
      type: System.String
      description: "식은 연결 된 속성의 이름입니다."
    return:
      type: System.Object
      description: "<xref:System.Object>에 키와 연결 된는 <xref uid=&quot;langword_csharp_&lt;appSettings&gt;&quot; name=&quot;&lt;appSettings&gt;&quot; href=&quot;&quot;> </xref> Web.config 파일의 섹션.</xref:System.Object>"
  overload: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "The key is not found in Web.config.  \n  \n \\- or -  \n  \n The return value could not be converted."
  platform:
  - net462
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression(System.Web.UI.BoundPropertyEntry,System.Object,System.Web.Compilation.ExpressionBuilderContext)
  id: GetCodeExpression(System.Web.UI.BoundPropertyEntry,System.Object,System.Web.Compilation.ExpressionBuilderContext)
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  langs:
  - csharp
  name: GetCodeExpression(BoundPropertyEntry,Object,ExpressionBuilderContext)
  nameWithType: AppSettingsExpressionBuilder.GetCodeExpression(BoundPropertyEntry,Object,ExpressionBuilderContext)
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression(BoundPropertyEntry,Object,ExpressionBuilderContext)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Compilation
  summary: "생성된 된 페이지 클래스에 속성 할당을 수행 하는 데 사용 되는 코드 식을 반환 합니다."
  remarks: "이 메서드는 페이지 또는 컨트롤에 대 한 CodeDOM 생성 하는 동안 호출 됩니다. 반환 된 <xref:System.CodeDom.CodeExpression>개체의 속성 할당에 생성 된 페이지 클래스에 추가 하려면 코드 식을 나타냅니다</xref:System.CodeDom.CodeExpression>"
  syntax:
    content: public override System.CodeDom.CodeExpression GetCodeExpression (System.Web.UI.BoundPropertyEntry entry, object parsedData, System.Web.Compilation.ExpressionBuilderContext context);
    parameters:
    - id: entry
      type: System.Web.UI.BoundPropertyEntry
      description: "식은 연결 된 속성입니다."
    - id: parsedData
      type: System.Object
      description: "나타내는 <xref:System.Web.Compilation.ExpressionBuilder.ParseExpression*>.</xref:System.Web.Compilation.ExpressionBuilder.ParseExpression*> 에서 반환 된 데이터를 구문 분석"
    - id: context
      type: System.Web.Compilation.ExpressionBuilderContext
      description: "컨트롤 또는 페이지에 대 한 속성입니다."
    return:
      type: System.CodeDom.CodeExpression
      description: "A <xref href=&quot;System.CodeDom.CodeExpression&quot;> </xref> 속성 할당에 사용 되는 합니다."
  overload: System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.SupportsEvaluate
  id: SupportsEvaluate
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  langs:
  - csharp
  name: SupportsEvaluate
  nameWithType: AppSettingsExpressionBuilder.SupportsEvaluate
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.SupportsEvaluate
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Compilation
  summary: "컴파일되지 않은 페이지에는 식이 계산 될 수 있는지 여부를 나타내는 값을 반환 합니다."
  remarks: "SupportsEvaluate 속성은 표시 여부는 <xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>클래스에서 구현 된 메서드와 식에 대 한 값을 반환할 수 있습니다.</xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A> <xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>컴파일되지 않은 페이지에서 계산 되는 식에 대 한 식 작성기 내에서 구현 되어야 합니다.</xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A> <xref:System.Web.Compilation.AppSettingsExpressionBuilder>클래스 항상 반환 하도록 컴파일되지 않은 페이지에서 응용 프로그램 설정의 계산을 지원 `true`.</xref:System.Web.Compilation.AppSettingsExpressionBuilder>"
  syntax:
    content: public override bool SupportsEvaluate { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>모든 경우"
  overload: System.Web.Compilation.AppSettingsExpressionBuilder.SupportsEvaluate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Compilation.ExpressionBuilder
  isExternal: false
  name: System.Web.Compilation.ExpressionBuilder
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.#ctor
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: AppSettingsExpressionBuilder()
  nameWithType: AppSettingsExpressionBuilder.AppSettingsExpressionBuilder()
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.AppSettingsExpressionBuilder()
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression(System.Object,System.Web.UI.BoundPropertyEntry,System.Object,System.Web.Compilation.ExpressionBuilderContext)
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: EvaluateExpression(Object,BoundPropertyEntry,Object,ExpressionBuilderContext)
  nameWithType: AppSettingsExpressionBuilder.EvaluateExpression(Object,BoundPropertyEntry,Object,ExpressionBuilderContext)
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression(Object,BoundPropertyEntry,Object,ExpressionBuilderContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.UI.BoundPropertyEntry
  parent: System.Web.UI
  isExternal: false
  name: BoundPropertyEntry
  nameWithType: BoundPropertyEntry
  fullName: System.Web.UI.BoundPropertyEntry
- uid: System.Web.Compilation.ExpressionBuilderContext
  parent: System.Web.Compilation
  isExternal: false
  name: ExpressionBuilderContext
  nameWithType: ExpressionBuilderContext
  fullName: System.Web.Compilation.ExpressionBuilderContext
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(System.String)
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: GetAppSetting(String)
  nameWithType: AppSettingsExpressionBuilder.GetAppSetting(String)
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(System.String,System.Type,System.String)
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: GetAppSetting(String,Type,String)
  nameWithType: AppSettingsExpressionBuilder.GetAppSetting(String,Type,String)
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting(String,Type,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression(System.Web.UI.BoundPropertyEntry,System.Object,System.Web.Compilation.ExpressionBuilderContext)
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: GetCodeExpression(BoundPropertyEntry,Object,ExpressionBuilderContext)
  nameWithType: AppSettingsExpressionBuilder.GetCodeExpression(BoundPropertyEntry,Object,ExpressionBuilderContext)
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression(BoundPropertyEntry,Object,ExpressionBuilderContext)
- uid: System.CodeDom.CodeExpression
  parent: System.CodeDom
  isExternal: false
  name: CodeExpression
  nameWithType: CodeExpression
  fullName: System.CodeDom.CodeExpression
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.SupportsEvaluate
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: SupportsEvaluate
  nameWithType: AppSettingsExpressionBuilder.SupportsEvaluate
  fullName: System.Web.Compilation.AppSettingsExpressionBuilder.SupportsEvaluate
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.#ctor*
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: AppSettingsExpressionBuilder
  nameWithType: AppSettingsExpressionBuilder.AppSettingsExpressionBuilder
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression*
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: EvaluateExpression
  nameWithType: AppSettingsExpressionBuilder.EvaluateExpression
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting*
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: GetAppSetting
  nameWithType: AppSettingsExpressionBuilder.GetAppSetting
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression*
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: GetCodeExpression
  nameWithType: AppSettingsExpressionBuilder.GetCodeExpression
- uid: System.Web.Compilation.AppSettingsExpressionBuilder.SupportsEvaluate*
  parent: System.Web.Compilation.AppSettingsExpressionBuilder
  isExternal: false
  name: SupportsEvaluate
  nameWithType: AppSettingsExpressionBuilder.SupportsEvaluate
