### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.HostElement
  id: HostElement
  children:
  - System.ServiceModel.Configuration.HostElement.#ctor
  - System.ServiceModel.Configuration.HostElement.BaseAddresses
  - System.ServiceModel.Configuration.HostElement.Properties
  - System.ServiceModel.Configuration.HostElement.Timeouts
  langs:
  - csharp
  name: HostElement
  nameWithType: HostElement
  fullName: System.ServiceModel.Configuration.HostElement
  type: Class
  summary: "서비스 호스트에 대 한 설정을 지정 하는 구성 요소를 나타냅니다. 이 클래스는 상속 될 수 없습니다."
  syntax:
    content: 'public sealed class HostElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HostElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.HostElement
  langs:
  - csharp
  name: HostElement()
  nameWithType: HostElement.HostElement()
  fullName: System.ServiceModel.Configuration.HostElement.HostElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.Configuration.HostElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public HostElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.HostElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HostElement.BaseAddresses
  id: BaseAddresses
  parent: System.ServiceModel.Configuration.HostElement
  langs:
  - csharp
  name: BaseAddresses
  nameWithType: HostElement.BaseAddresses
  fullName: System.ServiceModel.Configuration.HostElement.BaseAddresses
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "서비스 호스트에서 사용 되는 기본 주소를 가져옵니다."
  syntax:
    content: public System.ServiceModel.Configuration.BaseAddressElementCollection BaseAddresses { get; }
    return:
      type: System.ServiceModel.Configuration.BaseAddressElementCollection
      description: "기본 주소 컬렉션입니다."
  overload: System.ServiceModel.Configuration.HostElement.BaseAddresses*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HostElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.HostElement
  langs:
  - csharp
  name: Properties
  nameWithType: HostElement.Properties
  fullName: System.ServiceModel.Configuration.HostElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.HostElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.HostElement.Timeouts
  id: Timeouts
  parent: System.ServiceModel.Configuration.HostElement
  langs:
  - csharp
  name: Timeouts
  nameWithType: HostElement.Timeouts
  fullName: System.ServiceModel.Configuration.HostElement.Timeouts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "서비스 호스트가 열리거나 닫히는 데 허용 되는 시간 간격을 지정 하는 구성 요소를 가져옵니다."
  syntax:
    content: public System.ServiceModel.Configuration.HostTimeoutsElement Timeouts { get; }
    return:
      type: System.ServiceModel.Configuration.HostTimeoutsElement
      description: "서비스 호스트가 열리거나 닫히는 데 허용 되는 시간 간격을 지정 하는 구성 요소입니다."
  overload: System.ServiceModel.Configuration.HostElement.Timeouts*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.HostElement.#ctor
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: HostElement()
  nameWithType: HostElement.HostElement()
  fullName: System.ServiceModel.Configuration.HostElement.HostElement()
- uid: System.ServiceModel.Configuration.HostElement.BaseAddresses
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: BaseAddresses
  nameWithType: HostElement.BaseAddresses
  fullName: System.ServiceModel.Configuration.HostElement.BaseAddresses
- uid: System.ServiceModel.Configuration.BaseAddressElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BaseAddressElementCollection
  nameWithType: BaseAddressElementCollection
  fullName: System.ServiceModel.Configuration.BaseAddressElementCollection
- uid: System.ServiceModel.Configuration.HostElement.Properties
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: Properties
  nameWithType: HostElement.Properties
  fullName: System.ServiceModel.Configuration.HostElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.HostElement.Timeouts
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: Timeouts
  nameWithType: HostElement.Timeouts
  fullName: System.ServiceModel.Configuration.HostElement.Timeouts
- uid: System.ServiceModel.Configuration.HostTimeoutsElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HostTimeoutsElement
  nameWithType: HostTimeoutsElement
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement
- uid: System.ServiceModel.Configuration.HostElement.#ctor*
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: HostElement
  nameWithType: HostElement.HostElement
- uid: System.ServiceModel.Configuration.HostElement.BaseAddresses*
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: BaseAddresses
  nameWithType: HostElement.BaseAddresses
- uid: System.ServiceModel.Configuration.HostElement.Properties*
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: Properties
  nameWithType: HostElement.Properties
- uid: System.ServiceModel.Configuration.HostElement.Timeouts*
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: Timeouts
  nameWithType: HostElement.Timeouts
