### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyWrongTypeException
  id: SettingsPropertyWrongTypeException
  children:
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException
  nameWithType: SettingsPropertyWrongTypeException
  fullName: System.Configuration.SettingsPropertyWrongTypeException
  type: Class
  summary: "잘못 된 형식이 함께 사용 하면 throw 되는 예외를 제공는 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> 개체입니다."
  syntax:
    content: 'public class SettingsPropertyWrongTypeException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException()
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.SettingsPropertyWrongTypeException&quot;> </xref> 클래스입니다."
  syntax:
    content: public SettingsPropertyWrongTypeException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(String)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.SettingsPropertyWrongTypeException&quot;> </xref> 클래스 제공 된 매개 변수 기반으로 합니다."
  syntax:
    content: public SettingsPropertyWrongTypeException (string message);
    parameters:
    - id: message
      type: System.String
      description: "예외 메시지를 포함 하는 문자열입니다."
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.SettingsPropertyWrongTypeException&quot;> </xref> 클래스 제공된 된 매개 변수 기반으로 합니다."
  syntax:
    content: protected SettingsPropertyWrongTypeException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> throw 되는 예외에 대 한 직렬화 된 개체 데이터를 보유 하 합니다."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>소스 또는 serialize 된 스트림의 대상에 대 한 컨텍스트 정보를 포함 하는.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyWrongTypeException
  langs:
  - csharp
  name: SettingsPropertyWrongTypeException(String,Exception)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Configuration.SettingsPropertyWrongTypeException&quot;> </xref> 클래스 제공된 된 매개 변수 기반으로 합니다."
  syntax:
    content: public SettingsPropertyWrongTypeException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "예외 메시지를 포함 하는 문자열입니다."
    - id: innerException
      type: System.Exception
      description: "현재 예외의 원인인 예외입니다."
  overload: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException()
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException()
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(String)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException(String,Exception)
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
  fullName: System.Configuration.SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException(String,Exception)
- uid: System.Configuration.SettingsPropertyWrongTypeException.#ctor*
  parent: System.Configuration.SettingsPropertyWrongTypeException
  isExternal: false
  name: SettingsPropertyWrongTypeException
  nameWithType: SettingsPropertyWrongTypeException.SettingsPropertyWrongTypeException
