### YamlMime:ManagedReference
items:
- uid: System.Management.ComparisonSettings
  id: ComparisonSettings
  children:
  - System.Management.ComparisonSettings.IgnoreCase
  - System.Management.ComparisonSettings.IgnoreClass
  - System.Management.ComparisonSettings.IgnoreDefaultValues
  - System.Management.ComparisonSettings.IgnoreFlavor
  - System.Management.ComparisonSettings.IgnoreObjectSource
  - System.Management.ComparisonSettings.IgnoreQualifiers
  - System.Management.ComparisonSettings.IncludeAll
  langs:
  - csharp
  name: ComparisonSettings
  nameWithType: ComparisonSettings
  fullName: System.Management.ComparisonSettings
  type: Enum
  summary: "<xref:System.Management.ManagementBaseObject.CompareTo*>.</xref:System.Management.ManagementBaseObject.CompareTo*> 사용할 수 있는 개체 비교 모드를 설명 합니다. 참고가 이러한 값을 결합할 수 있습니다."
  syntax:
    content: >-
      [System.Flags]

      public enum ComparisonSettings
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreCase
  id: IgnoreCase
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreCase
  nameWithType: ComparisonSettings.IgnoreCase
  fullName: System.Management.ComparisonSettings.IgnoreCase
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: '소문자에서 문자열 값을 비교 하는 모드입니다. 문자열에 한정자 값이 적용 됩니다. 속성 및 한정자 이름 또는 not이 플래그가 지정 되어 있는지 여부를 항상 대/소문자 구분 방식으로 비교 됩니다. 값: 16입니다.'
  syntax:
    content: IgnoreCase
    return:
      type: System.Management.ComparisonSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreClass
  id: IgnoreClass
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreClass
  nameWithType: ComparisonSettings.IgnoreClass
  fullName: System.Management.ComparisonSettings.IgnoreClass
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: '비교 되는 개체는 동일한 클래스의 인스턴스는 가정 하는 모드입니다. 따라서이 값은 인스턴스 관련 정보에 비교 합니다. 이 플래그를 사용 하 여 성능을 최적화 합니다. 동일한 클래스의 개체가 없는 경우 결과가 정의 되지 않습니다. 값: 8입니다.'
  syntax:
    content: IgnoreClass
    return:
      type: System.Management.ComparisonSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreDefaultValues
  id: IgnoreDefaultValues
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreDefaultValues
  nameWithType: ComparisonSettings.IgnoreDefaultValues
  fullName: System.Management.ComparisonSettings.IgnoreDefaultValues
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: '속성의 기본값을 무시 하는 모드입니다. 이 값은 클래스를 비교할 때에 의미가 있습니다. 값: 4입니다.'
  syntax:
    content: IgnoreDefaultValues
    return:
      type: System.Management.ComparisonSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreFlavor
  id: IgnoreFlavor
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreFlavor
  nameWithType: ComparisonSettings.IgnoreFlavor
  fullName: System.Management.ComparisonSettings.IgnoreFlavor
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: '한정자를 무시 하는 모드 *버전*합니다. 이 플래그 여전히 고려 한정자 값 하지만 특색 전파 규칙 등의 차이 무시 하 고 제한을 무시 합니다. 값: 32입니다.'
  syntax:
    content: IgnoreFlavor
    return:
      type: System.Management.ComparisonSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreObjectSource
  id: IgnoreObjectSource
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreObjectSource
  nameWithType: ComparisonSettings.IgnoreObjectSource
  fullName: System.Management.ComparisonSettings.IgnoreObjectSource
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: '개체, 즉: 서버 및 다른 개체에 대 한 비교에서 많았습니다 네임 스페이스의 소스를 무시 하는 모드입니다. 값: 2입니다.'
  syntax:
    content: IgnoreObjectSource
    return:
      type: System.Management.ComparisonSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreQualifiers
  id: IgnoreQualifiers
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreQualifiers
  nameWithType: ComparisonSettings.IgnoreQualifiers
  fullName: System.Management.ComparisonSettings.IgnoreQualifiers
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: '무시 하 고 개체를 비교 하는 모드 *한정자*합니다. 값: 1입니다.'
  syntax:
    content: IgnoreQualifiers
    return:
      type: System.Management.ComparisonSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IncludeAll
  id: IncludeAll
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IncludeAll
  nameWithType: ComparisonSettings.IncludeAll
  fullName: System.Management.ComparisonSettings.IncludeAll
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: '비교 되는 개체의 모든 요소를 비교 하는 모드입니다. 값: 0.'
  syntax:
    content: IncludeAll
    return:
      type: System.Management.ComparisonSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.ComparisonSettings.IgnoreCase
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreCase
  nameWithType: ComparisonSettings.IgnoreCase
  fullName: System.Management.ComparisonSettings.IgnoreCase
- uid: System.Management.ComparisonSettings
  parent: System.Management
  isExternal: false
  name: ComparisonSettings
  nameWithType: ComparisonSettings
  fullName: System.Management.ComparisonSettings
- uid: System.Management.ComparisonSettings.IgnoreClass
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreClass
  nameWithType: ComparisonSettings.IgnoreClass
  fullName: System.Management.ComparisonSettings.IgnoreClass
- uid: System.Management.ComparisonSettings.IgnoreDefaultValues
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreDefaultValues
  nameWithType: ComparisonSettings.IgnoreDefaultValues
  fullName: System.Management.ComparisonSettings.IgnoreDefaultValues
- uid: System.Management.ComparisonSettings.IgnoreFlavor
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreFlavor
  nameWithType: ComparisonSettings.IgnoreFlavor
  fullName: System.Management.ComparisonSettings.IgnoreFlavor
- uid: System.Management.ComparisonSettings.IgnoreObjectSource
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreObjectSource
  nameWithType: ComparisonSettings.IgnoreObjectSource
  fullName: System.Management.ComparisonSettings.IgnoreObjectSource
- uid: System.Management.ComparisonSettings.IgnoreQualifiers
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreQualifiers
  nameWithType: ComparisonSettings.IgnoreQualifiers
  fullName: System.Management.ComparisonSettings.IgnoreQualifiers
- uid: System.Management.ComparisonSettings.IncludeAll
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IncludeAll
  nameWithType: ComparisonSettings.IncludeAll
  fullName: System.Management.ComparisonSettings.IncludeAll
