### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlSchemaContextSettings
  id: XamlSchemaContextSettings
  children:
  - System.Xaml.XamlSchemaContextSettings.#ctor
  - System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  - System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  - System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  langs:
  - csharp
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
  type: Class
  summary: "에 대 한 선택적 설정을 제공는 <xref href=&quot;System.Xaml.XamlSchemaContext&quot;> </xref>합니다."
  syntax:
    content: public class XamlSchemaContextSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> 클래스입니다."
  syntax:
    content: public XamlSchemaContextSettings ();
    parameters: []
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  id: '#ctor(System.Xaml.XamlSchemaContextSettings)'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> 클래스는 기존 열의 값을 복사 하 여 <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> 인스턴스."
  syntax:
    content: public XamlSchemaContextSettings (System.Xaml.XamlSchemaContextSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlSchemaContextSettings
      description: "기존 <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref>합니다."
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  id: FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "XAML 스키마와 해당 컨텍스트 조회 API에 의해 반환 되는 값에 정규화 된 어셈블리 이름을 사용 하는지 여부를 지정 하는 값을 가져오거나 설정 합니다."
  remarks: "이 속성의 값에 의해 반환 된 문자열에 영향을 줍니다 <xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A>생성 된 스키마 컨텍스트에서.</xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A> 경우 <xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A>은 `true`, assembly 부분 문자열의 <xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName>.</xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName> 을 해당 하는 보고</xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A>"
  syntax:
    content: public bool FullyQualifyAssemblyNamesInClrNamespaces { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>XAML 스키마와 해당 컨텍스트 조회 Api;에 의해 반환 되는 값에서 정규화 된 어셈블리 이름을 사용 하는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  id: SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "XAML 스키마 컨텍스트를 동일한 인자 수 (입력된 매개 변수 수)를 갖는 두 명의 생성자가 있는 태그 확장에 대 한 허용 하는지 여부를 지정 하는 값을 가져오거나 설정 합니다."
  remarks: "<xref:System.Xaml.XamlSchemaContext>, 설정을 직접 읽을 수 없습니다.</xref:System.Xaml.XamlSchemaContext> 대신 값에서에서 받은 특정 읽기 전용 속성을 같은 <xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>, 설정을 기반으로 값을 보고 있는.</xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>"
  syntax:
    content: public bool SupportMarkupExtensionsWithDuplicateArity { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>스키마 컨텍스트; 중복 인자가 있는 태그 확장에 대 한 허용 하는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
- uid: System.Xaml.XamlSchemaContextSettings
  parent: System.Xaml
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
- uid: System.Xaml.XamlSchemaContextSettings.#ctor*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
