### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCookiesSection
  id: HttpCookiesSection
  children:
  - System.Web.Configuration.HttpCookiesSection.#ctor
  - System.Web.Configuration.HttpCookiesSection.Domain
  - System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  - System.Web.Configuration.HttpCookiesSection.Properties
  - System.Web.Configuration.HttpCookiesSection.RequireSSL
  langs:
  - csharp
  name: HttpCookiesSection
  nameWithType: HttpCookiesSection
  fullName: System.Web.Configuration.HttpCookiesSection
  type: Class
  summary: "웹 응용 프로그램에서 사용 하는 쿠키의 속성을 구성 합니다."
  remarks: "HttpCookiesSection 클래스에는 프로그래밍 방식으로 액세스 하 고 수정 하는 방법을 제공는 `httpCookies` 구성 파일의 섹션입니다.       이러한 쿠키를 발급 하는 코드는 재정의 하지 않는 한 응용 프로그램에 의해 발급 된 모든 쿠키에 기본적으로 적용 되는 설정을 정의 합니다.       목적 중 하나는 `httpCookies` 의 사용을 지 원하는 요소는 `HttpOnly` 쿠키입니다. `HttpOnly`쿠키 (있는 쿠키는 `HttpOnly` 특성) 사이트 간 스크립팅의 위험을 완화 하려면 Internet Explorer 6에서 도입 되었습니다. `HttpOnly` 특성 쿠키를 사용 하지 못하게 클라이언트 쪽 스크립트를 통해 액세스 합니다. 에 포함 된 모든 정보는 `HttpOnly` 쿠키는 해커가 또는 악성 웹 사이트에 공개 될 가능성이 더 낮아집니다. &quot;HttpOnly&quot;에 대 한 자세한 내용은 MSDN (msdn.microsoft.com)을 검색      > [!NOTE] > The HttpCookiesSection 수 정보 읽기 및 쓰기과 섹션 속성은 <xref:System.Configuration.SectionInformation.AllowDefinition%2A>의 값은 <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> 에 따라 구성 파일의 관련된 섹션"
  example:
  - "The following code example shows how to obtain the HttpCookiesSection object from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_7_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#1](~/add/codesnippet/csharp/t-system.web.configurati_7_1.cs)]"
  syntax:
    content: 'public sealed class HttpCookiesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: HttpCookiesSection()
  nameWithType: HttpCookiesSection.HttpCookiesSection()
  fullName: System.Web.Configuration.HttpCookiesSection.HttpCookiesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Web.Configuration.HttpCookiesSection&quot;> </xref> 클래스입니다."
  remarks: "이 생성자는 사용자 코드에서 직접 사용할 수 없습니다. ASP.NET 구성 시스템에 의해 호출 됩니다. 인스턴스를 가져올 수는 <xref:System.Web.Configuration.HttpCookiesSection>클래스를 사용 하 여는 <xref:System.Configuration.Configuration.GetSection%2A>메서드.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.HttpCookiesSection>"
  syntax:
    content: public HttpCookiesSection ();
    parameters: []
  overload: System.Web.Configuration.HttpCookiesSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.Domain
  id: Domain
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: Domain
  nameWithType: HttpCookiesSection.Domain
  fullName: System.Web.Configuration.HttpCookiesSection.Domain
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "쿠키의 도메인 이름을 설정 하거나 가져옵니다."
  remarks: ''
  example:
  - "The following code example shows how to use the Domain property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_9_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#2](~/add/codesnippet/csharp/p-system.web.configurati_9_1.cs)]"
  syntax:
    content: public string Domain { get; set; }
    return:
      type: System.String
      description: "쿠키의 도메인 이름입니다."
  overload: System.Web.Configuration.HttpCookiesSection.Domain*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  id: HttpOnlyCookies
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
  fullName: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "나타내는 값을 가져오거나 여부는 브라우저에 대 한 지원 <xref uid=&quot;langword_csharp_HttpOnly&quot; name=&quot;HttpOnly&quot; href=&quot;&quot;> </xref> 쿠키를 사용할 수 있습니다."
  remarks: "`httpCookies` 요소 사용을 지원 `HttpOnly` 쿠키입니다. `HttpOnly`쿠키 (있는 쿠키는 `HttpOnly` 특성) 사이트 간 스크립팅의 위험을 완화 하려면 Internet Explorer 6에서 도입 되었습니다. `HttpOnly` 특성 쿠키를 사용 하지 못하게 클라이언트 쪽 스크립트를 통해 액세스 합니다. 에 포함 된 모든 정보는 `HttpOnly` 쿠키는 해커가 또는 악성 웹 사이트에 공개 될 가능성이 더 낮아집니다. &quot;HttpOnly&quot;에 대 한 자세한 내용은 MSDN (msdn.microsoft.com)을 검색"
  example:
  - "The following code example shows how to use the HttpOnlyCookies property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_227_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#4](~/add/codesnippet/csharp/p-system.web.configurati_227_1.cs)]"
  syntax:
    content: public bool HttpOnlyCookies { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>경우에 대 한 지원의 <xref uid=&quot;langword_csharp_HttpOnly&quot; name=&quot;HttpOnly&quot; href=&quot;&quot;> </xref> 그렇지 않으면 쿠키는 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다. 기본값은 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.Properties
  id: Properties
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: Properties
  nameWithType: HttpCookiesSection.Properties
  fullName: System.Web.Configuration.HttpCookiesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Web.Configuration.HttpCookiesSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL
  id: RequireSSL
  parent: System.Web.Configuration.HttpCookiesSection
  langs:
  - csharp
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
  fullName: System.Web.Configuration.HttpCookiesSection.RequireSSL
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "(SECURE Sockets Layer) 통신에 필요한 지 여부를 나타내는 값을 가져오거나 설정 합니다."
  remarks: "RequireSSL 속성 하거나 RFC 2109에 설명 된 대로 보안 쿠키 특성의 출력을 사용 하지 않도록 설정 합니다. 표준 규격의 브라우저에서 사용 하는 경우 쿠키만 SSL/TLS를 사용 하 여 연결을 통해 다시 전송 됩니다. 기본값은 `false`합니다."
  example:
  - "The following code example shows how to use the RequireSSL property.  \n  \n [!code-vb[System.Web.Configuration.HttpCookiesSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_82_1.vb)]\n [!code-cs[System.Web.Configuration.HttpCookiesSection#3](~/add/codesnippet/csharp/p-system.web.configurati_82_1.cs)]"
  syntax:
    content: public bool RequireSSL { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>SSL을 사용 하면 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다. 기본값은 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Web.Configuration.HttpCookiesSection.RequireSSL*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HttpCookiesSection.#ctor
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpCookiesSection()
  nameWithType: HttpCookiesSection.HttpCookiesSection()
  fullName: System.Web.Configuration.HttpCookiesSection.HttpCookiesSection()
- uid: System.Web.Configuration.HttpCookiesSection.Domain
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Domain
  nameWithType: HttpCookiesSection.Domain
  fullName: System.Web.Configuration.HttpCookiesSection.Domain
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
  fullName: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.HttpCookiesSection.Properties
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Properties
  nameWithType: HttpCookiesSection.Properties
  fullName: System.Web.Configuration.HttpCookiesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
  fullName: System.Web.Configuration.HttpCookiesSection.RequireSSL
- uid: System.Web.Configuration.HttpCookiesSection.#ctor*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpCookiesSection
  nameWithType: HttpCookiesSection.HttpCookiesSection
- uid: System.Web.Configuration.HttpCookiesSection.Domain*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Domain
  nameWithType: HttpCookiesSection.Domain
- uid: System.Web.Configuration.HttpCookiesSection.HttpOnlyCookies*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: HttpOnlyCookies
  nameWithType: HttpCookiesSection.HttpOnlyCookies
- uid: System.Web.Configuration.HttpCookiesSection.Properties*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: Properties
  nameWithType: HttpCookiesSection.Properties
- uid: System.Web.Configuration.HttpCookiesSection.RequireSSL*
  parent: System.Web.Configuration.HttpCookiesSection
  isExternal: false
  name: RequireSSL
  nameWithType: HttpCookiesSection.RequireSSL
