### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  id: WorkflowIdleElement
  children:
  - System.ServiceModel.Activities.Configuration.WorkflowIdleElement.#ctor
  - System.ServiceModel.Activities.Configuration.WorkflowIdleElement.BehaviorType
  - System.ServiceModel.Activities.Configuration.WorkflowIdleElement.CreateBehavior
  - System.ServiceModel.Activities.Configuration.WorkflowIdleElement.Properties
  - System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToPersist
  - System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToUnload
  langs:
  - csharp
  name: WorkflowIdleElement
  nameWithType: WorkflowIdleElement
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  type: Class
  summary: "워크플로 정의 유휴 요소의 속성을 처리 합니다. 유휴 요소는 워크플로 인스턴스가 유휴 상태로 될 때 프로세스를 정의 합니다. 클래스는 봉인된 클래스입니다."
  syntax:
    content: 'public sealed class WorkflowIdleElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  langs:
  - csharp
  name: WorkflowIdleElement()
  nameWithType: WorkflowIdleElement.WorkflowIdleElement()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.WorkflowIdleElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.ServiceModel.Activities.Configuration.WorkflowIdleElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public WorkflowIdleElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: WorkflowIdleElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "워크플로 인스턴스가 메모리에서 언로드합니다 또는 워크플로 인스턴스가 유휴 상태가 지속 여부를 가져옵니다."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "동작의 형식을 나타내는 개체입니다."
  overload: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: WorkflowIdleElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  langs:
  - csharp
  name: Properties
  nameWithType: WorkflowIdleElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToPersist
  id: TimeToPersist
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  langs:
  - csharp
  name: TimeToPersist
  nameWithType: WorkflowIdleElement.TimeToPersist
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToPersist
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "워크플로 인스턴스를 유지 하는 데 할당 된 시간을 가져오거나 설정 합니다."
  syntax:
    content: public TimeSpan TimeToPersist { get; set; }
    return:
      type: System.TimeSpan
      description: "Timespan 개체입니다."
  overload: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToPersist*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToUnload
  id: TimeToUnload
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  langs:
  - csharp
  name: TimeToUnload
  nameWithType: WorkflowIdleElement.TimeToUnload
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToUnload
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "워크플로 인스턴스가 언로드에 할당 된 시간 기간을 가져오거나 설정 합니다."
  syntax:
    content: public TimeSpan TimeToUnload { get; set; }
    return:
      type: System.TimeSpan
      description: "Timespan 개체입니다."
  overload: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToUnload*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: WorkflowIdleElement()
  nameWithType: WorkflowIdleElement.WorkflowIdleElement()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.WorkflowIdleElement()
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.BehaviorType
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: BehaviorType
  nameWithType: WorkflowIdleElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: WorkflowIdleElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.Properties
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: Properties
  nameWithType: WorkflowIdleElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToPersist
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: TimeToPersist
  nameWithType: WorkflowIdleElement.TimeToPersist
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToPersist
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToUnload
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: TimeToUnload
  nameWithType: WorkflowIdleElement.TimeToUnload
  fullName: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToUnload
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: WorkflowIdleElement
  nameWithType: WorkflowIdleElement.WorkflowIdleElement
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.BehaviorType*
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: BehaviorType
  nameWithType: WorkflowIdleElement.BehaviorType
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.CreateBehavior*
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: CreateBehavior
  nameWithType: WorkflowIdleElement.CreateBehavior
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: Properties
  nameWithType: WorkflowIdleElement.Properties
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToPersist*
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: TimeToPersist
  nameWithType: WorkflowIdleElement.TimeToPersist
- uid: System.ServiceModel.Activities.Configuration.WorkflowIdleElement.TimeToUnload*
  parent: System.ServiceModel.Activities.Configuration.WorkflowIdleElement
  isExternal: false
  name: TimeToUnload
  nameWithType: WorkflowIdleElement.TimeToUnload
