### YamlMime:ManagedReference
items:
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  id: DeclaredTypeElement
  children:
  - System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor
  - System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor(System.String)
  - System.Runtime.Serialization.Configuration.DeclaredTypeElement.KnownTypes
  - System.Runtime.Serialization.Configuration.DeclaredTypeElement.PostDeserialize
  - System.Runtime.Serialization.Configuration.DeclaredTypeElement.Properties
  - System.Runtime.Serialization.Configuration.DeclaredTypeElement.Type
  langs:
  - csharp
  name: DeclaredTypeElement
  nameWithType: DeclaredTypeElement
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  type: Class
  summary: "에 <xref:System.Runtime.Serialization.DataContractSerializer>.</xref:System.Runtime.Serialization.DataContractSerializer> serialization에 사용 되는 알려진된 형식을 추가 하는 데 사용 하는 XML 요소를 처리"
  remarks: "This class is used to handle the XML element that specifies the declared type and contains its collection of known types.  \n  \n For an example of adding known types to the collection using configuration, see [\\&lt;declaredTypes\\&gt;](../Topic/%3CdeclaredTypes%3E.md)."
  syntax:
    content: 'public sealed class DeclaredTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor
  id: '#ctor'
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  langs:
  - csharp
  name: DeclaredTypeElement()
  nameWithType: DeclaredTypeElement.DeclaredTypeElement()
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.DeclaredTypeElement()
  type: Constructor
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Serialization.Configuration.DeclaredTypeElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public DeclaredTypeElement ();
    parameters: []
  overload: System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  langs:
  - csharp
  name: DeclaredTypeElement(String)
  nameWithType: DeclaredTypeElement.DeclaredTypeElement(String)
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.DeclaredTypeElement(String)
  type: Constructor
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Serialization.Configuration.DeclaredTypeElement&quot;> </xref> 지정 된 형식 이름 사용 합니다."
  syntax:
    content: public DeclaredTypeElement (string typeName);
    parameters:
    - id: typeName
      type: System.String
      description: "알려진 형식 컬렉션이 필요한 형식의 이름입니다."
  overload: System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.KnownTypes
  id: KnownTypes
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  langs:
  - csharp
  name: KnownTypes
  nameWithType: DeclaredTypeElement.KnownTypes
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.KnownTypes
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "알려진 형식 컬렉션을 가져옵니다."
  syntax:
    content: public System.Runtime.Serialization.Configuration.TypeElementCollection KnownTypes { get; }
    return:
      type: System.Runtime.Serialization.Configuration.TypeElementCollection
      description: "A <xref href=&quot;System.Runtime.Serialization.Configuration.TypeElementCollection&quot;> </xref> 하는 알려진된 형식을 포함 합니다."
  overload: System.Runtime.Serialization.Configuration.DeclaredTypeElement.KnownTypes*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.PostDeserialize
  id: PostDeserialize
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: DeclaredTypeElement.PostDeserialize()
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.PostDeserialize()
  type: Method
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Runtime.Serialization.Configuration.DeclaredTypeElement.PostDeserialize*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Properties
  id: Properties
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: DeclaredTypeElement.Properties
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Properties
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Type
  id: Type
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  langs:
  - csharp
  name: Type
  nameWithType: DeclaredTypeElement.Type
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Type
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "알려진 형식 컬렉션이 필요한 선언 형식의 이름을 가져오거나 설정 합니다."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "선언한 형식의 이름입니다."
  overload: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: DeclaredTypeElement()
  nameWithType: DeclaredTypeElement.DeclaredTypeElement()
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.DeclaredTypeElement()
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor(System.String)
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: DeclaredTypeElement(String)
  nameWithType: DeclaredTypeElement.DeclaredTypeElement(String)
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.DeclaredTypeElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.KnownTypes
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: KnownTypes
  nameWithType: DeclaredTypeElement.KnownTypes
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.KnownTypes
- uid: System.Runtime.Serialization.Configuration.TypeElementCollection
  parent: System.Runtime.Serialization.Configuration
  isExternal: false
  name: TypeElementCollection
  nameWithType: TypeElementCollection
  fullName: System.Runtime.Serialization.Configuration.TypeElementCollection
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.PostDeserialize
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: PostDeserialize()
  nameWithType: DeclaredTypeElement.PostDeserialize()
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.PostDeserialize()
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Properties
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: Properties
  nameWithType: DeclaredTypeElement.Properties
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Type
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: Type
  nameWithType: DeclaredTypeElement.Type
  fullName: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Type
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.#ctor*
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: DeclaredTypeElement
  nameWithType: DeclaredTypeElement.DeclaredTypeElement
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.KnownTypes*
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: KnownTypes
  nameWithType: DeclaredTypeElement.KnownTypes
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.PostDeserialize*
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: PostDeserialize
  nameWithType: DeclaredTypeElement.PostDeserialize
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Properties*
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: Properties
  nameWithType: DeclaredTypeElement.Properties
- uid: System.Runtime.Serialization.Configuration.DeclaredTypeElement.Type*
  parent: System.Runtime.Serialization.Configuration.DeclaredTypeElement
  isExternal: false
  name: Type
  nameWithType: DeclaredTypeElement.Type
