### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.DefaultPortElement
  id: DefaultPortElement
  children:
  - System.ServiceModel.Configuration.DefaultPortElement.#ctor
  - System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  - System.ServiceModel.Configuration.DefaultPortElement.Port
  - System.ServiceModel.Configuration.DefaultPortElement.Properties
  - System.ServiceModel.Configuration.DefaultPortElement.Scheme
  langs:
  - csharp
  name: DefaultPortElement
  nameWithType: DefaultPortElement
  fullName: System.ServiceModel.Configuration.DefaultPortElement
  type: Class
  summary: "통신 끝점에 대 한 기본 설정을 정의 하는 구성 요소를 나타냅니다."
  remarks: "기본 포트는 클라이언트 응용 프로그램에서 수신 하는 기본 통신 끝점입니다."
  syntax:
    content: 'public sealed class DefaultPortElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: DefaultPortElement()
  nameWithType: DefaultPortElement.DefaultPortElement()
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.ServiceModel.Configuration.DefaultPortElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public DefaultPortElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  id: '#ctor(System.ServiceModel.Configuration.DefaultPortElement)'
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: DefaultPortElement(DefaultPortElement)
  nameWithType: DefaultPortElement.DefaultPortElement(DefaultPortElement)
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement(DefaultPortElement)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "새 인스턴스를 만듭니다는 <xref href=&quot;System.ServiceModel.Configuration.DefaultPortElement&quot;> </xref> 지정된 된 <xref href=&quot;System.ServiceModel.Configuration.DefaultPortElement&quot;> </xref>합니다."
  syntax:
    content: public DefaultPortElement (System.ServiceModel.Configuration.DefaultPortElement other);
    parameters:
    - id: other
      type: System.ServiceModel.Configuration.DefaultPortElement
      description: "현재 기본 포트 요소에 대 한 설정을 제공 하는 기본 포트 요소입니다."
  overload: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port
  id: Port
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Port
  nameWithType: DefaultPortElement.Port
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Port
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "기본 통신 포트 번호를 가져오거나 설정 합니다."
  syntax:
    content: public int Port { get; set; }
    return:
      type: System.Int32
      description: "통신 포트입니다."
  overload: System.ServiceModel.Configuration.DefaultPortElement.Port*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Properties
  nameWithType: DefaultPortElement.Properties
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.ServiceModel.Configuration.DefaultPortElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  id: Scheme
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "통신 포트와 연결 된 프로토콜 설정 그룹을 가져오거나 설정 합니다."
  syntax:
    content: public string Scheme { get; set; }
    return:
      type: System.String
      description: "통신 프로토콜 설정 합니다."
  overload: System.ServiceModel.Configuration.DefaultPortElement.Scheme*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement()
  nameWithType: DefaultPortElement.DefaultPortElement()
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement()
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement(DefaultPortElement)
  nameWithType: DefaultPortElement.DefaultPortElement(DefaultPortElement)
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement(DefaultPortElement)
- uid: System.ServiceModel.Configuration.DefaultPortElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: DefaultPortElement
  nameWithType: DefaultPortElement
  fullName: System.ServiceModel.Configuration.DefaultPortElement
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Port
  nameWithType: DefaultPortElement.Port
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Port
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Properties
  nameWithType: DefaultPortElement.Properties
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Scheme
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement
  nameWithType: DefaultPortElement.DefaultPortElement
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Port
  nameWithType: DefaultPortElement.Port
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Properties
  nameWithType: DefaultPortElement.Properties
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
