### YamlMime:ManagedReference
items:
- uid: System.Web.UnvalidatedRequestValues
  id: UnvalidatedRequestValues
  children:
  - System.Web.UnvalidatedRequestValues.Cookies
  - System.Web.UnvalidatedRequestValues.Files
  - System.Web.UnvalidatedRequestValues.Form
  - System.Web.UnvalidatedRequestValues.Headers
  - System.Web.UnvalidatedRequestValues.Item(System.String)
  - System.Web.UnvalidatedRequestValues.Path
  - System.Web.UnvalidatedRequestValues.PathInfo
  - System.Web.UnvalidatedRequestValues.QueryString
  - System.Web.UnvalidatedRequestValues.RawUrl
  - System.Web.UnvalidatedRequestValues.Url
  langs:
  - csharp
  name: UnvalidatedRequestValues
  nameWithType: UnvalidatedRequestValues
  fullName: System.Web.UnvalidatedRequestValues
  type: Class
  summary: "ASP.NET 요청 유효성 검사를 트리거하지 않고 HTTP 요청 값에 대 한 액세스를 제공 합니다."
  remarks: "ASP.NET 컬렉션을 요청 하는 HTTP의 값을 읽을 때 (같은 <xref:System.Web.HttpRequest.Form%2A>, <xref:System.Web.HttpRequest.QueryString%2A>, 및 <xref:System.Web.HttpRequest.Cookies%2A>컬렉션), 수행 *요청 유효성 검사를*.</xref:System.Web.HttpRequest.Cookies%2A> </xref:System.Web.HttpRequest.QueryString%2A> </xref:System.Web.HttpRequest.Form%2A> 요청 유효성 검사 중 ASP.NET 게시 된 값을 검사 하 고 태그, 스크립트 또는 예약 된 문자를 포함 되어 있는지 여부를 결정 합니다. 기본적으로 ASP.NET의 이러한 유형의 입력을 발견 하면 throw 된 <xref:System.Web.HttpRequestValidationException>예외.</xref:System.Web.HttpRequestValidationException> 이렇게 하면 웹 사이트에 악성 스크립트 삽입 공격을 방지할 수 있습니다.       하지만, 경우에 따라 ASP.NET 요청 유효성 검사를 무시 하 고 태그, 스크립트 또는 예약 된 문자를 포함 하는 값을 허용 하려면 필요할 수 있습니다.  예를 들어 응용 프로그램에서 형식이 지정 된 내용으로 HTML 태그를 제출할 수 있도록 하는 서식 있는 텍스트 편집기를 사용 하는 경우 기본 ASP.NET 요청 유효성 검사를 트리거하지 않고 서식 있는 텍스트 요청 값을 검색 하 여 UnvalidatedRequestValues 클래스의 멤버를 사용할 수 있습니다. 코드를 사용 하 여이 클래스의 멤버 액세스는 <xref:System.Web.HttpRequest.Unvalidated%2A>속성.</xref:System.Web.HttpRequest.Unvalidated%2A>      > [!IMPORTANT] >이 클래스를 사용 하는 경우 수동으로 잠재적인 교차 사이트 스크립팅 공격에 대 한 데이터를 확인 해야 합니다."
  syntax:
    content: public sealed class UnvalidatedRequestValues
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Cookies
  id: Cookies
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Cookies
  nameWithType: UnvalidatedRequestValues.Cookies
  fullName: System.Web.UnvalidatedRequestValues.Cookies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "ASP.NET 요청 유효성 검사를 트리거하지 않고 클라이언트가 보낸 쿠키의 컬렉션을 가져옵니다."
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Web.HttpCookieCollection Cookies { get; }
    return:
      type: System.Web.HttpCookieCollection
      description: The cookies from the HTTP request.
  overload: System.Web.UnvalidatedRequestValues.Cookies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Files
  id: Files
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Files
  nameWithType: UnvalidatedRequestValues.Files
  fullName: System.Web.UnvalidatedRequestValues.Files
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the collection of files that the client uploaded, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Web.HttpFileCollection Files { get; }
    return:
      type: System.Web.HttpFileCollection
      description: The files from the HTTP request.
  overload: System.Web.UnvalidatedRequestValues.Files*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Form
  id: Form
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Form
  nameWithType: UnvalidatedRequestValues.Form
  fullName: System.Web.UnvalidatedRequestValues.Form
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the collection of form variables that the client submitted, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Collections.Specialized.NameValueCollection Form { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: The form variables from the HTTP request.
  overload: System.Web.UnvalidatedRequestValues.Form*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Headers
  id: Headers
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Headers
  nameWithType: UnvalidatedRequestValues.Headers
  fullName: System.Web.UnvalidatedRequestValues.Headers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the collection of HTTP headers that the client sent, without triggering request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Collections.Specialized.NameValueCollection Headers { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: The headers from the HTTP request.
  overload: System.Web.UnvalidatedRequestValues.Headers*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Item(System.String)
  id: Item(System.String)
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Item(String)
  nameWithType: UnvalidatedRequestValues.Item(String)
  fullName: System.Web.UnvalidatedRequestValues.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the specified object from the <xref:System.Web.HttpRequest.Form*>, <xref:System.Web.HttpRequest.Cookies*>, <xref:System.Web.HttpRequest.QueryString*>, or <xref:System.Web.HttpRequest.ServerVariables*> collection, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public string this[string field] { get; }
    parameters:
    - id: field
      type: System.String
      description: The key of the object to retrieve.
    return:
      type: System.String
      description: The requested object, or <xref uid="langword_csharp_null" name="null" href=""></xref> if the object is not found.
  overload: System.Web.UnvalidatedRequestValues.Item*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Path
  id: Path
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Path
  nameWithType: UnvalidatedRequestValues.Path
  fullName: System.Web.UnvalidatedRequestValues.Path
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the virtual path of the requested resource without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: The virtual path.
  overload: System.Web.UnvalidatedRequestValues.Path*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.PathInfo
  id: PathInfo
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: PathInfo
  nameWithType: UnvalidatedRequestValues.PathInfo
  fullName: System.Web.UnvalidatedRequestValues.PathInfo
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets additional path information for a resource that has a URL extension, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public string PathInfo { get; }
    return:
      type: System.String
      description: A string that contains additional path information for a resource.
  overload: System.Web.UnvalidatedRequestValues.PathInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.QueryString
  id: QueryString
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: QueryString
  nameWithType: UnvalidatedRequestValues.QueryString
  fullName: System.Web.UnvalidatedRequestValues.QueryString
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the collection of HTTP query string variables that the client submitted, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Collections.Specialized.NameValueCollection QueryString { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: The collection of query string variables sent by the client.
  overload: System.Web.UnvalidatedRequestValues.QueryString*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.RawUrl
  id: RawUrl
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: RawUrl
  nameWithType: UnvalidatedRequestValues.RawUrl
  fullName: System.Web.UnvalidatedRequestValues.RawUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the part of the requested URL that follows the website name, without triggering ASP.NET request validation.
  remarks: "> [!IMPORTANT]>이 속성을 사용 하는 경우 잠재적인 교차 사이트 스크립팅 공격에 대 한 데이터를 수동으로 확인 해야 합니다.  \n  \n If the complete request URL is `http://www.contoso.com/default.aspx?id=44`, the value of RawUrl is `/default.aspx?id=44`."
  syntax:
    content: public string RawUrl { get; }
    return:
      type: System.String
      description: The part of the URL that follows the website name.
  overload: System.Web.UnvalidatedRequestValues.RawUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Url
  id: Url
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Url
  nameWithType: UnvalidatedRequestValues.Url
  fullName: System.Web.UnvalidatedRequestValues.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the URL data for the request without triggering ASP.NET request validation.
  remarks: "> [!IMPORTANT]\n>  If you use this property, you must manually check the data for potential cross-site scripting attacks.  \n  \n You can retrieve URL data such as the port number, host name, path information, and data about the user from the <xref:System.Uri> object that this property returns."
  syntax:
    content: public Uri Url { get; }
    return:
      type: System.Uri
      description: An object that contains the URL data for the request.
  overload: System.Web.UnvalidatedRequestValues.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.UnvalidatedRequestValues.Cookies
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValues.Cookies
  fullName: System.Web.UnvalidatedRequestValues.Cookies
- uid: System.Web.HttpCookieCollection
  parent: System.Web
  isExternal: false
  name: HttpCookieCollection
  nameWithType: HttpCookieCollection
  fullName: System.Web.HttpCookieCollection
- uid: System.Web.UnvalidatedRequestValues.Files
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValues.Files
  fullName: System.Web.UnvalidatedRequestValues.Files
- uid: System.Web.HttpFileCollection
  parent: System.Web
  isExternal: false
  name: HttpFileCollection
  nameWithType: HttpFileCollection
  fullName: System.Web.HttpFileCollection
- uid: System.Web.UnvalidatedRequestValues.Form
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValues.Form
  fullName: System.Web.UnvalidatedRequestValues.Form
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.UnvalidatedRequestValues.Headers
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValues.Headers
  fullName: System.Web.UnvalidatedRequestValues.Headers
- uid: System.Web.UnvalidatedRequestValues.Item(System.String)
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Item(String)
  nameWithType: UnvalidatedRequestValues.Item(String)
  fullName: System.Web.UnvalidatedRequestValues.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UnvalidatedRequestValues.Path
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValues.Path
  fullName: System.Web.UnvalidatedRequestValues.Path
- uid: System.Web.UnvalidatedRequestValues.PathInfo
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValues.PathInfo
  fullName: System.Web.UnvalidatedRequestValues.PathInfo
- uid: System.Web.UnvalidatedRequestValues.QueryString
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValues.QueryString
  fullName: System.Web.UnvalidatedRequestValues.QueryString
- uid: System.Web.UnvalidatedRequestValues.RawUrl
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValues.RawUrl
  fullName: System.Web.UnvalidatedRequestValues.RawUrl
- uid: System.Web.UnvalidatedRequestValues.Url
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValues.Url
  fullName: System.Web.UnvalidatedRequestValues.Url
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Web.UnvalidatedRequestValues.Cookies*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValues.Cookies
- uid: System.Web.UnvalidatedRequestValues.Files*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValues.Files
- uid: System.Web.UnvalidatedRequestValues.Form*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValues.Form
- uid: System.Web.UnvalidatedRequestValues.Headers*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValues.Headers
- uid: System.Web.UnvalidatedRequestValues.Item*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Item
  nameWithType: UnvalidatedRequestValues.Item
- uid: System.Web.UnvalidatedRequestValues.Path*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValues.Path
- uid: System.Web.UnvalidatedRequestValues.PathInfo*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValues.PathInfo
- uid: System.Web.UnvalidatedRequestValues.QueryString*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValues.QueryString
- uid: System.Web.UnvalidatedRequestValues.RawUrl*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValues.RawUrl
- uid: System.Web.UnvalidatedRequestValues.Url*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValues.Url
