### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.DiagnosticsElement
  id: DiagnosticsElement
  children:
  - System.Web.Services.Configuration.DiagnosticsElement.#ctor
  - System.Web.Services.Configuration.DiagnosticsElement.Properties
  - System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  langs:
  - csharp
  name: DiagnosticsElement
  nameWithType: DiagnosticsElement
  fullName: System.Web.Services.Configuration.DiagnosticsElement
  type: Class
  summary: "나타냅니다는 [ &lt;진단&gt; ](http://msdn.microsoft.com/en-us/e4ca05d1-1e10-4873-9ef6-75e55851d888) Web.config 구성 파일의 요소입니다."
  remarks: "DiagnosticsElement 클래스 나타냅니다는 [ \\<진단 >](http://msdn.microsoft.com/en-us/e4ca05d1-1e10-4873-9ef6-75e55851d888) Web.config 파일의 요소입니다. 설정 된 <xref:System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions%2A>속성을 true로 디버깅을 위해 클라이언트에 예외를 반환 하기 위해.</xref:System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions%2A>"
  syntax:
    content: 'public sealed class DiagnosticsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: DiagnosticsElement()
  nameWithType: DiagnosticsElement.DiagnosticsElement()
  fullName: System.Web.Services.Configuration.DiagnosticsElement.DiagnosticsElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Web.Services.Configuration.DiagnosticsElement&quot;> </xref> 클래스입니다."
  syntax:
    content: public DiagnosticsElement ();
    parameters: []
  overload: System.Web.Services.Configuration.DiagnosticsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: System.Web.Services.Configuration.DiagnosticsElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "추가할 수 있습니다."
  overload: System.Web.Services.Configuration.DiagnosticsElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  id: SuppressReturningExceptions
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "서비스에서 예외를 반환 하는지 여부를 나타내는 값을 가져오거나 설정 합니다."
  syntax:
    content: public bool SuppressReturningExceptions { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>서비스 예외를 반환 하는 경우 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다. 기본값은 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: DiagnosticsElement()
  nameWithType: DiagnosticsElement.DiagnosticsElement()
  fullName: System.Web.Services.Configuration.DiagnosticsElement.DiagnosticsElement()
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: System.Web.Services.Configuration.DiagnosticsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: DiagnosticsElement
  nameWithType: DiagnosticsElement.DiagnosticsElement
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: Properties
  nameWithType: DiagnosticsElement.Properties
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
