### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.BasicHttpMessageSecurity
  id: BasicHttpMessageSecurity
  children:
  - System.ServiceModel.BasicHttpMessageSecurity.#ctor
  - System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
  - System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
  - System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  - System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  langs:
  - csharp
  name: BasicHttpMessageSecurity
  nameWithType: BasicHttpMessageSecurity
  fullName: System.ServiceModel.BasicHttpMessageSecurity
  type: Class
  summary: "<xref:System.ServiceModel.BasicHttpBinding>.</xref:System.ServiceModel.BasicHttpBinding> 에 대 한 메시지 수준 보안 설정을 구성합니다."
  remarks: ''
  example:
  - >-
    [!code-cs[S_UEBasicHttpBinding#5](~/add/codesnippet/csharp/t-system.servicemodel.ba_1.cs)]
     [!code-vb[S_UEBasicHttpBinding#5](~/add/codesnippet/visualbasic/t-system.servicemodel.ba_1.vb)]
  syntax:
    content: public sealed class BasicHttpMessageSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: BasicHttpMessageSecurity()
  nameWithType: BasicHttpMessageSecurity.BasicHttpMessageSecurity()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.BasicHttpMessageSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.ServiceModel.BasicHttpMessageSecurity&quot;> </xref> 클래스입니다."
  syntax:
    content: public BasicHttpMessageSecurity ();
    parameters: []
  overload: System.ServiceModel.BasicHttpMessageSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.AlgorithmSuite
  fullName: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "알고리즘 모음을 사용 하면 지정 <xref href=&quot;System.ServiceModel.BasicHttpMessageSecurity&quot;> </xref>합니다."
  remarks: "<xref:System.ServiceModel.Security.SecurityAlgorithmSuite>반환 되는 개체에는 특정 조건에서 사용할 보안 알고리즘을 지정 하는 여러 속성이 포함 되어 있습니다.</xref:System.ServiceModel.Security.SecurityAlgorithmSuite> 또한 서비스의 다양 한 보안 기능을 설명 합니다."
  example:
  - >-
    [!code-cs[S_UEBasicHttpBinding#7](~/add/codesnippet/csharp/p-system.servicemodel.ba_0_1.cs)]
     [!code-vb[S_UEBasicHttpBinding#7](~/add/codesnippet/visualbasic/p-system.servicemodel.ba_0_1.vb)]
  syntax:
    content: public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: "A <xref href=&quot;System.ServiceModel.Security.SecurityAlgorithmSuite&quot;></xref>. 기본값은 <xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256*>.</xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256*>"
  overload: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ClientCredentialType
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "클라이언트를 인증 하는 자격 증명의 유형을 지정 합니다."
  remarks: "반환 값은 다음 열거형 멤버 중 하나일 수 있습니다.- <xref:System.ServiceModel.BasicHttpMessageCredentialType>- <xref:System.ServiceModel.BasicHttpMessageCredentialType></xref:System.ServiceModel.BasicHttpMessageCredentialType> </xref:System.ServiceModel.BasicHttpMessageCredentialType>"
  example:
  - >-
    [!code-cs[S_UEBasicHttpBinding#6](~/add/codesnippet/csharp/p-system.servicemodel.ba_1_1.cs)]
     [!code-vb[S_UEBasicHttpBinding#6](~/add/codesnippet/visualbasic/p-system.servicemodel.ba_1_1.vb)]
  syntax:
    content: public System.ServiceModel.BasicHttpMessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.BasicHttpMessageCredentialType
      description: "멤버는 <xref:System.ServiceModel.BasicHttpMessageCredentialType>열거형.</xref:System.ServiceModel.BasicHttpMessageCredentialType> 기본값은 <xref:System.ServiceModel.BasicHttpMessageCredentialType>.</xref:System.ServiceModel.BasicHttpMessageCredentialType>"
  overload: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  id: ShouldSerializeAlgorithmSuite
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: ShouldSerializeAlgorithmSuite()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "SOAP 수준에서 메시지를 보호에 사용할 알고리즘 모음을 serialize 해야 하는지 여부를 반환 합니다."
  syntax:
    content: public bool ShouldSerializeAlgorithmSuite ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>알고리즘 모음을 serialize 해야 합니다. 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  id: ShouldSerializeClientCredentialType
  parent: System.ServiceModel.BasicHttpMessageSecurity
  langs:
  - csharp
  name: ShouldSerializeClientCredentialType()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "클라이언트 자격 증명 형식을 serialize 해야 하는지 여부를 반환 합니다."
  remarks: '클라이언트 자격 증명 형식의 두 예제는: id 및 전송 합니다.'
  syntax:
    content: public bool ShouldSerializeClientCredentialType ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>클라이언트 자격 증명 형식을 serialize 해야 합니다. 그렇지 않으면 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>합니다."
  overload: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.BasicHttpMessageSecurity.#ctor
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: BasicHttpMessageSecurity()
  nameWithType: BasicHttpMessageSecurity.BasicHttpMessageSecurity()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.BasicHttpMessageSecurity()
- uid: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.AlgorithmSuite
  fullName: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ClientCredentialType
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType
- uid: System.ServiceModel.BasicHttpMessageCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: BasicHttpMessageCredentialType
  nameWithType: BasicHttpMessageCredentialType
  fullName: System.ServiceModel.BasicHttpMessageCredentialType
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ShouldSerializeAlgorithmSuite()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ShouldSerializeClientCredentialType()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
  fullName: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
- uid: System.ServiceModel.BasicHttpMessageSecurity.#ctor*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: BasicHttpMessageSecurity
  nameWithType: BasicHttpMessageSecurity.BasicHttpMessageSecurity
- uid: System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.AlgorithmSuite
- uid: System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ClientCredentialType
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ShouldSerializeAlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
- uid: System.ServiceModel.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType*
  parent: System.ServiceModel.BasicHttpMessageSecurity
  isExternal: false
  name: ShouldSerializeClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
