### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  id: AssemblyReferenceType
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
  langs:
  - csharp
  name: AssemblyReferenceType
  nameWithType: AssemblyReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  type: Enum
  summary: "이 클래스는 어셈블리 참조의 유형을 나타냅니다."
  syntax:
    content: public enum AssemblyReferenceType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
  id: ClickOnceManifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  langs:
  - csharp
  name: ClickOnceManifest
  nameWithType: AssemblyReferenceType.ClickOnceManifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "ClickOnce 매니페스트를 지정합니다."
  syntax:
    content: ClickOnceManifest
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
  id: ManagedAssembly
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  langs:
  - csharp
  name: ManagedAssembly
  nameWithType: AssemblyReferenceType.ManagedAssembly
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: ".NET Framework 어셈블리를 지정합니다."
  syntax:
    content: ManagedAssembly
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
  id: NativeAssembly
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  langs:
  - csharp
  name: NativeAssembly
  nameWithType: AssemblyReferenceType.NativeAssembly
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Win32 네이티브 어셈블리를 지정합니다."
  syntax:
    content: NativeAssembly
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
  id: Unspecified
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  langs:
  - csharp
  name: Unspecified
  nameWithType: AssemblyReferenceType.Unspecified
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "어셈블리의 형식 지정 되지 않으며에 의해 결정 됩니다는 <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.UpdateFileInfo*>메서드에.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.UpdateFileInfo*>"
  syntax:
    content: Unspecified
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  isExternal: false
  name: ClickOnceManifest
  nameWithType: AssemblyReferenceType.ClickOnceManifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyReferenceType
  nameWithType: AssemblyReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  isExternal: false
  name: ManagedAssembly
  nameWithType: AssemblyReferenceType.ManagedAssembly
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  isExternal: false
  name: NativeAssembly
  nameWithType: AssemblyReferenceType.NativeAssembly
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  isExternal: false
  name: Unspecified
  nameWithType: AssemblyReferenceType.Unspecified
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
