### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.BuildEngine.BuildSettings
  id: BuildSettings
  children:
  - Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  - Microsoft.Build.BuildEngine.BuildSettings.None
  langs:
  - csharp
  name: BuildSettings
  nameWithType: BuildSettings
  fullName: Microsoft.Build.BuildEngine.BuildSettings
  type: Enum
  summary: "빌드에 대 한 설정을 지정합니다."
  syntax:
    content: >-
      [System.Flags]

      public enum BuildSettings
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  id: DoNotResetPreviouslyBuiltTargets
  parent: Microsoft.Build.BuildEngine.BuildSettings
  langs:
  - csharp
  name: DoNotResetPreviouslyBuiltTargets
  nameWithType: BuildSettings.DoNotResetPreviouslyBuiltTargets
  fullName: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "없는 중요 한 외부 상태가 변경 이전에 작성 된 대상이 없습니다를 다시 작성 되도록 지정 합니다."
  syntax:
    content: DoNotResetPreviouslyBuiltTargets
    return:
      type: Microsoft.Build.BuildEngine.BuildSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.BuildSettings.None
  id: None
  parent: Microsoft.Build.BuildEngine.BuildSettings
  langs:
  - csharp
  name: None
  nameWithType: BuildSettings.None
  fullName: Microsoft.Build.BuildEngine.BuildSettings.None
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "빌드가 정상적으로 실행 되도록 지정 합니다."
  syntax:
    content: None
    return:
      type: Microsoft.Build.BuildEngine.BuildSettings
      description: "추가할 수 있습니다."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  parent: Microsoft.Build.BuildEngine.BuildSettings
  isExternal: false
  name: DoNotResetPreviouslyBuiltTargets
  nameWithType: BuildSettings.DoNotResetPreviouslyBuiltTargets
  fullName: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
- uid: Microsoft.Build.BuildEngine.BuildSettings
  parent: Microsoft.Build.BuildEngine
  isExternal: false
  name: BuildSettings
  nameWithType: BuildSettings
  fullName: Microsoft.Build.BuildEngine.BuildSettings
- uid: Microsoft.Build.BuildEngine.BuildSettings.None
  parent: Microsoft.Build.BuildEngine.BuildSettings
  isExternal: false
  name: None
  nameWithType: BuildSettings.None
  fullName: Microsoft.Build.BuildEngine.BuildSettings.None
